"use client";

/**
 * Affiliate Detail — Stitch conversion (view-id: `affiliate-detail`)
 *
 * Source: stitch_screens/affiliate_detail_alpha_capital_media
 * Spec: [NEW] · overlay states: 2/2 wired
 * States: affiliate_detail_edit_profile_sheet_state✓, affiliate_detail_suspend_affiliate_alertdialog_state✓
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import * as React from "react";
import { MsIcon } from "@/components/stitch/stitch";

export function AffiliateDetailStitchPage() {
  const [so0, setSo0] = React.useState(false);
  const [so1, setSo1] = React.useState(false);
  return (
    <>
      <div className="flex flex-col w-full">
        <div className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl mb-6 shadow-sm flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2 text-on-surface-variant font-medium">
            <span className="text-[10px] tracking-wider uppercase font-semibold text-tsc">OPERATIONS CORE</span>
            <span className="text-outline-variant">/</span>
            <span className="text-tsc">GROWTH &amp; ECOSYSTEM</span>
            <span className="text-outline-variant">/</span>
            <span className="text-tsc">AFFILIATES &amp; PARTNERS</span>
            <span className="text-outline-variant">/</span>
            <span className="text-primary font-semibold font-mono">AFFILIATE DETAIL (ACM-8921)</span>
          </div>
          <div className="flex items-center gap-4 flex-wrap text-[11px] font-mono">
            <div className="flex items-center gap-1.5 bg-surface-container px-2.5 py-1 rounded-md text-on-surface">
              <span className="h-2 w-2 rounded-full bg-primary animate-pulse"></span>
              <span className="font-semibold text-primary">ACTIVE TIER-1 MASTER</span>
            </div>
            <div className="flex items-center gap-1 text-tsc">
              <span>Attribution Latency:</span>
              <span className="text-on-surface font-semibold text-primary">0.42ms</span>
            </div>
            <div className="flex items-center gap-1 text-tsc">
              <span>WORM Ledger:</span>
              <span className="text-on-surface bg-surface-container px-1.5 py-0.5 rounded">0x9f2a4b88</span>
            </div>
            <div className="flex items-center gap-1.5 text-tsc">
              <span>Auto-Settlement:</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-primary/10 text-primary">ENABLED</span>
            </div>
          </div>
        </div>
        <div className="bg-surface-container-lowest rounded-2xl p-6 mb-8 shadow-sm relative overflow-hidden">
          <div className="absolute -right-16 -top-16 w-64 h-64 bg-primary/5 rounded-full blur-2xl pointer-events-none"></div>
          <div className="relative z-10 flex flex-col gap-5">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <a className="inline-flex items-center gap-1.5 text-xs font-semibold text-tsc hover:text-primary transition-colors group" href="#" onClick={(e) => e.preventDefault()}>
<MsIcon name="arrow_back" className="text-[18px] group-hover:-translate-x-0.5 transition-transform" />
                <span>Back to Affiliates Directory</span>
              </a>
              <div className="flex items-center gap-3">
                <button className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold bg-surface-container hover:bg-surface-container-high text-on-surface transition-colors">
<MsIcon name="person_add" className="text-[16px] text-tertiary" />
                  <span>Send Invite to Refer Partner</span>
                </button>
                <button className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold bg-primary text-on-primary hover:bg-primary/90 transition-all shadow-sm">
<MsIcon name="download" className="text-[16px]" />
                  <span>Export Affiliate Dossier</span>
                </button>
              </div>
            </div>
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pt-2">
              <div className="space-y-1.5">
                <div className="flex items-center gap-3 flex-wrap">
                  <h1 className="text-2xl lg:text-3xl font-headline font-bold text-on-surface tracking-tight">Alpha Capital Media</h1>
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary/15 text-primary">
<MsIcon name="verified" className="text-[14px]" />
                    <span>VERIFIED INSTITUTIONAL</span>
                  </span>
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary text-on-primary">
                    <span className="h-1.5 w-1.5 rounded-full bg-on-primary"></span>
                    <span>ACTIVE PARTNER</span>
                  </span>
                </div>
                <div className="flex items-center gap-2.5 flex-wrap text-xs text-tsc pt-1">
                  <span className="font-medium text-on-surface flex items-center gap-1">
<MsIcon name="workspace_premium" className="text-[16px] text-tertiary" />
                    <span>Platinum Institutional Master</span>
                  </span>
                  <span className="text-outline-variant">•</span>
                  <span>Ref Code: <span className="font-mono font-bold text-on-surface">ALPHACAP</span></span>
                  <span className="text-outline-variant">•</span>
                  <span><strong className="text-on-surface font-semibold">48,200</strong> Clicks (30d)</span>
                  <span className="text-outline-variant">•</span>
                  <span><strong className="text-on-surface font-semibold">1,480</strong> Conversions</span>
                  <span className="text-outline-variant">•</span>
                  <span><strong className="text-primary font-semibold">$284,500</strong> Attributed Vol</span>
                  <span className="text-outline-variant">•</span>
                  <span className="text-tsc">Partner since Oct 14, 2023</span>
                </div>
              </div>
              <div className="flex items-center gap-2 self-start md:self-auto bg-surface-container-low px-3 py-2 rounded-xl">
                <div className="text-right">
                  <div className="text-[10px] uppercase font-bold text-tsc tracking-wider">Health Index</div>
                  <div className="text-sm font-bold font-mono text-primary">99.8% ROUTE INTEGRITY</div>
                </div>
<MsIcon name="speed" className="text-primary text-[28px]" />
              </div>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          <div className="lg:col-span-8 flex flex-col gap-6">
            <div className="bg-surface-container-lowest rounded-2xl p-2 shadow-sm flex items-center gap-1.5 overflow-x-auto" id="affiliate-tab-strip">
              <button className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold transition-all bg-primary text-on-primary shadow-sm" id="tab-btn-overview">
<MsIcon name="dashboard" className="text-[16px]" />
                <span>Overview</span>
              </button>
              <button className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container transition-all" id="tab-btn-campaigns">
<MsIcon name="campaign" className="text-[16px]" />
                <span>Campaigns (4 Active)</span>
              </button>
              <button className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container transition-all" id="tab-btn-ledger">
<MsIcon name="receipt_long" className="text-[16px]" />
                <span>Commission Ledger (1,480 Rows)</span>
              </button>
              <button className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container transition-all" id="tab-btn-audit">
<MsIcon name="verified_user" className="text-[16px]" />
                <span>WORM Audit Trail (38 Events)</span>
              </button>
            </div>
            <div className="flex flex-col gap-6" id="tab-content-container">
              <div className="flex flex-col gap-6" id="tab-panel-overview">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="bg-surface-container-lowest rounded-2xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
                    <div className="flex items-center justify-between text-tsc mb-2">
                      <span className="text-xs font-semibold uppercase tracking-wider">Lifetime Commission</span>
<MsIcon name="account_balance_wallet" className="text-[20px] text-primary" />
                    </div>
                    <div>
                      <div className="text-2xl font-bold font-mono text-primary tracking-tight">$342,850.00</div>
                      <div className="flex items-center gap-1 text-[11px] font-semibold text-primary mt-1">
<MsIcon name="trending_up" className="text-[14px]" />
                        <span>+18.2% YoY growth</span>
                      </div>
                    </div>
                  </div>
                  <div className="bg-surface-container-lowest rounded-2xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
                    <div className="flex items-center justify-between text-tsc mb-2">
                      <span className="text-xs font-semibold uppercase tracking-wider">Pending Payout</span>
<MsIcon name="schedule" className="text-[20px] text-tertiary" />
                    </div>
                    <div>
                      <div className="text-2xl font-bold font-mono text-tertiary tracking-tight">$24,500.00</div>
                      <div className="text-[11px] text-tsc mt-1 flex items-center gap-1">
                        <span className="h-1.5 w-1.5 rounded-full bg-tertiary"></span>
                        <span>Net-15 settlement due May 25</span>
                      </div>
                    </div>
                  </div>
                  <div className="bg-surface-container-lowest rounded-2xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
                    <div className="flex items-center justify-between text-tsc mb-2">
                      <span className="text-xs font-semibold uppercase tracking-wider">Avg Conversion Rate</span>
<MsIcon name="pie_chart" className="text-[20px] text-primary" />
                    </div>
                    <div>
                      <div className="text-2xl font-bold font-mono text-on-surface tracking-tight">3.07%</div>
                      <div className="text-[11px] text-tsc mt-1">Benchmark: 2.0% – 4.0%</div>
                    </div>
                  </div>
                  <div className="bg-surface-container-lowest rounded-2xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
                    <div className="flex items-center justify-between text-tsc mb-2">
                      <span className="text-xs font-semibold uppercase tracking-wider">Active Tracking Links</span>
<MsIcon name="link" className="text-[20px] text-primary" />
                    </div>
                    <div>
                      <div className="text-2xl font-bold font-mono text-on-surface tracking-tight">6 URLs</div>
                      <div className="flex items-center gap-1 text-[11px] font-semibold text-primary mt-1">
<MsIcon name="check_circle" className="text-[14px]" />
                        <span>100% healthy ingress</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm flex flex-col gap-4">
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <div>
                      <h2 className="text-base font-headline font-bold text-on-surface">Commission Velocity (12-Month Trajectory)</h2>
                      <p className="text-xs text-tsc">Historical monthly disbursements from Jun 2024 to May 2025</p>
                    </div>
                    <div className="flex items-center gap-3 text-xs">
                      <div className="flex items-center gap-1.5">
                        <span className="w-3 h-3 rounded-full bg-primary"></span>
                        <span className="text-tsc font-medium">Attributed Commissions ($ USD)</span>
                      </div>
                      <span className="bg-surface-container px-2.5 py-1 rounded-lg text-xs font-mono font-semibold text-primary">Peak: $38.4k (May 25)</span>
                    </div>
                  </div>
                  <div className="w-full h-64 pt-4 relative">
                    <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 700 240">
                      <defs>
                        <linearGradient id="primaryGradient" x1="0%" x2="0%" y1="0%" y2="100%">
                          <stop offset="0%" stopColor="#4a7c59" stopOpacity={0.32}></stop>
                          <stop offset="70%" stopColor="#4a7c59" stopOpacity={0.06}></stop>
                          <stop offset="100%" stopColor="#4a7c59" stopOpacity={0.0}></stop>
                        </linearGradient>
                      </defs>
                      <line stroke="#e4e0d8" strokeDasharray="3,3" strokeWidth={1} x1={40} x2={680} y1={30} y2={30}></line>
                      <line stroke="#e4e0d8" strokeDasharray="3,3" strokeWidth={1} x1={40} x2={680} y1={80} y2={80}></line>
                      <line stroke="#e4e0d8" strokeDasharray="3,3" strokeWidth={1} x1={40} x2={680} y1={130} y2={130}></line>
                      <line stroke="#e4e0d8" strokeDasharray="3,3" strokeWidth={1} x1={40} x2={680} y1={180} y2={180}></line>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="end" x={32} y={34}>$40k</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="end" x={32} y={84}>$30k</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="end" x={32} y={134}>$20k</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="end" x={32} y={184}>$10k</text>
                      <path d="M 60 170                           C 115 160, 140 155, 175 145                          C 210 135, 235 140, 275 125                          C 315 110, 340 115, 385 100                          C 430 85, 460 92, 505 75                          C 550 58, 595 50, 660 38                          L 660 210 L 60 210 Z" fill="url(#primaryGradient)"></path>
                      <path d="M 60 170                           C 115 160, 140 155, 175 145                          C 210 135, 235 140, 275 125                          C 315 110, 340 115, 385 100                          C 430 85, 460 92, 505 75                          C 550 58, 595 50, 660 38" fill="none" stroke="#4a7c59" strokeLinecap="round" strokeWidth={3}></path>
                      <circle cx={60} cy={170} fill="#faf6f0" r={3.5} stroke="#4a7c59" strokeWidth={2.5}></circle>
                      <circle cx={175} cy={145} fill="#faf6f0" r={3.5} stroke="#4a7c59" strokeWidth={2.5}></circle>
                      <circle cx={275} cy={125} fill="#faf6f0" r={3.5} stroke="#4a7c59" strokeWidth={2.5}></circle>
                      <circle cx={385} cy={100} fill="#faf6f0" r={3.5} stroke="#4a7c59" strokeWidth={2.5}></circle>
                      <circle cx={505} cy={75} fill="#faf6f0" r={3.5} stroke="#4a7c59" strokeWidth={2.5}></circle>
                      <circle cx={660} cy={38} fill="#4a7c59" r={5} stroke="#ffffff" strokeWidth={2.5}></circle>
                      <g transform="translate(615, 8)">
                        <rect fill="#2e3230" height={20} rx={4} width={60} x={0} y={0}></rect>
                        <text fill="#ffffff" fontFamily="Nunito Sans" fontSize={10} fontWeight="bold" textAnchor="middle" x={30} y={14}>$38.4k</text>
                      </g>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={60} y={225}>Jun 24</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={175} y={225}>Aug 24</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={275} y={225}>Oct 24</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={385} y={225}>Dec 24</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={505} y={225}>Feb 25</text>
                      <text fill="#6b6358" fontFamily="Nunito Sans" fontSize={10} textAnchor="middle" x={660} y={225}>May 25</text>
                    </svg>
                  </div>
                </div>
                <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm flex flex-col gap-4">
                  <div className="flex items-center justify-between flex-wrap gap-2">
                    <div>
                      <h2 className="text-base font-headline font-bold text-on-surface">Recent Disbursements &amp; Settlements</h2>
                      <p className="text-xs text-tsc">Verified payouts with cryptographic receipt hashes</p>
                    </div>
                    <span className="text-xs font-semibold text-primary cursor-pointer hover:underline">View Full Ledger History →</span>
                  </div>
                  <div className="overflow-x-auto -mx-6 px-6">
                    <table className="w-full text-left text-xs whitespace-nowrap">
                      <thead>
                        <tr className="bg-surface-container-low text-tsc uppercase text-[10px] tracking-wider font-bold">
                          <th className="py-3 px-4 rounded-l-lg">DATE</th>
                          <th className="py-3 px-4">AMOUNT</th>
                          <th className="py-3 px-4">SETTLEMENT RAIL</th>
                          <th className="py-3 px-4">STATUS</th>
                          <th className="py-3 px-4">PAYMENT REFERENCE</th>
                          <th className="py-3 px-4 text-right rounded-r-lg">AUDIT RECEIPT</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-surface-container">
                        <tr className="hover:bg-surface-container-low/60 transition-colors">
                          <td className="py-3.5 px-4 font-medium text-on-surface">May 01, 2025</td>
                          <td className="py-3.5 px-4 font-mono font-bold text-primary">$38,400.00</td>
                          <td className="py-3.5 px-4 text-on-surface-variant flex items-center gap-1.5">
<MsIcon name="account_balance" className="text-[16px] text-tsc" />
                            <span>Wire Transfer (USD)</span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-primary/10 text-primary">
                              <span className="h-1.5 w-1.5 rounded-full bg-primary"></span>
                              Completed
                            </span>
                          </td>
                          <td className="py-3.5 px-4 font-mono text-tsc">PO-94102</td>
                          <td className="py-3.5 px-4 text-right">
                            <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline text-xs" href="#" onClick={(e) => e.preventDefault()}>
                              <span>Receipt</span>
<MsIcon name="north_east" className="text-[14px]" />
                            </a>
                          </td>
                        </tr>
                        <tr className="hover:bg-surface-container-low/60 transition-colors">
                          <td className="py-3.5 px-4 font-medium text-on-surface">Apr 01, 2025</td>
                          <td className="py-3.5 px-4 font-mono font-bold text-primary">$31,250.00</td>
                          <td className="py-3.5 px-4 text-on-surface-variant flex items-center gap-1.5">
<MsIcon name="account_balance" className="text-[16px] text-tsc" />
                            <span>Wire Transfer (USD)</span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-primary/10 text-primary">
                              <span className="h-1.5 w-1.5 rounded-full bg-primary"></span>
                              Completed
                            </span>
                          </td>
                          <td className="py-3.5 px-4 font-mono text-tsc">PO-91204</td>
                          <td className="py-3.5 px-4 text-right">
                            <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline text-xs" href="#" onClick={(e) => e.preventDefault()}>
                              <span>Receipt</span>
<MsIcon name="north_east" className="text-[14px]" />
                            </a>
                          </td>
                        </tr>
                        <tr className="hover:bg-surface-container-low/60 transition-colors">
                          <td className="py-3.5 px-4 font-medium text-on-surface">Mar 01, 2025</td>
                          <td className="py-3.5 px-4 font-mono font-bold text-primary">$28,900.00</td>
                          <td className="py-3.5 px-4 text-on-surface-variant flex items-center gap-1.5">
<MsIcon name="toll" className="text-[16px] text-tsc" />
                            <span>USDC (ERC-20)</span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-primary/10 text-primary">
                              <span className="h-1.5 w-1.5 rounded-full bg-primary"></span>
                              Completed
                            </span>
                          </td>
                          <td className="py-3.5 px-4 font-mono text-tsc">PO-88401</td>
                          <td className="py-3.5 px-4 text-right">
                            <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline text-xs" href="#" onClick={(e) => e.preventDefault()}>
                              <span>Receipt</span>
<MsIcon name="north_east" className="text-[14px]" />
                            </a>
                          </td>
                        </tr>
                        <tr className="hover:bg-surface-container-low/60 transition-colors">
                          <td className="py-3.5 px-4 font-medium text-on-surface">Feb 01, 2025</td>
                          <td className="py-3.5 px-4 font-mono font-bold text-primary">$26,100.00</td>
                          <td className="py-3.5 px-4 text-on-surface-variant flex items-center gap-1.5">
<MsIcon name="account_balance" className="text-[16px] text-tsc" />
                            <span>Wire Transfer (USD)</span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-primary/10 text-primary">
                              <span className="h-1.5 w-1.5 rounded-full bg-primary"></span>
                              Completed
                            </span>
                          </td>
                          <td className="py-3.5 px-4 font-mono text-tsc">PO-85921</td>
                          <td className="py-3.5 px-4 text-right">
                            <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline text-xs" href="#" onClick={(e) => e.preventDefault()}>
                              <span>Receipt</span>
<MsIcon name="north_east" className="text-[14px]" />
                            </a>
                          </td>
                        </tr>
                        <tr className="hover:bg-surface-container-low/60 transition-colors">
                          <td className="py-3.5 px-4 font-medium text-on-surface">Jan 01, 2025</td>
                          <td className="py-3.5 px-4 font-mono font-bold text-primary">$24,800.00</td>
                          <td className="py-3.5 px-4 text-on-surface-variant flex items-center gap-1.5">
<MsIcon name="account_balance" className="text-[16px] text-tsc" />
                            <span>Wire Transfer (USD)</span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-primary/10 text-primary">
                              <span className="h-1.5 w-1.5 rounded-full bg-primary"></span>
                              Completed
                            </span>
                          </td>
                          <td className="py-3.5 px-4 font-mono text-tsc">PO-82410</td>
                          <td className="py-3.5 px-4 text-right">
                            <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline text-xs" href="#" onClick={(e) => e.preventDefault()}>
                              <span>Receipt</span>
<MsIcon name="north_east" className="text-[14px]" />
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div className="hidden flex flex-col gap-4" id="tab-panel-campaigns">
                <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm">
                  <h2 className="text-base font-headline font-bold text-on-surface mb-4">Active Ecosystem Campaigns (4)</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="bg-surface-container-low p-4 rounded-xl flex flex-col justify-between gap-3">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-on-surface text-sm">Summer Scalper Accelerator 2025</span>
                        <span className="px-2 py-0.5 rounded bg-primary/15 text-primary text-[10px] font-bold">PRIMARY</span>
                      </div>
                      <p className="text-xs text-tsc">Targeting high-frequency tick and momentum prop traders with discounted Phase 1 fees.</p>
                      <div className="flex items-center justify-between pt-2 text-xs font-mono text-on-surface">
                        <span>Clicks: <strong>24,102</strong></span>
                        <span className="text-primary font-bold">Conv: 3.42%</span>
                      </div>
                    </div>
                    <div className="bg-surface-container-low p-4 rounded-xl flex flex-col justify-between gap-3">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-on-surface text-sm">Q2 FX Blitz Masterclass</span>
                        <span className="px-2 py-0.5 rounded bg-surface-container text-tsc text-[10px] font-bold">ACTIVE</span>
                      </div>
                      <p className="text-xs text-tsc">Educational portal integration offering 15% discount vouchers for funded FX accounts.</p>
                      <div className="flex items-center justify-between pt-2 text-xs font-mono text-on-surface">
                        <span>Clicks: <strong>11,840</strong></span>
                        <span className="text-primary font-bold">Conv: 2.85%</span>
                      </div>
                    </div>
                    <div className="bg-surface-container-low p-4 rounded-xl flex flex-col justify-between gap-3">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-on-surface text-sm">Discord Exclusive Alpha Desk</span>
                        <span className="px-2 py-0.5 rounded bg-surface-container text-tsc text-[10px] font-bold">ACTIVE</span>
                      </div>
                      <p className="text-xs text-tsc">Private 14,000 member Discord server custom bot integration with automated invite tracking.</p>
                      <div className="flex items-center justify-between pt-2 text-xs font-mono text-on-surface">
                        <span>Clicks: <strong>8,920</strong></span>
                        <span className="text-primary font-bold">Conv: 3.91%</span>
                      </div>
                    </div>
                    <div className="bg-surface-container-low p-4 rounded-xl flex flex-col justify-between gap-3">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-on-surface text-sm">ProTrader Scaling Live Webinar</span>
                        <span className="px-2 py-0.5 rounded bg-surface-container text-tsc text-[10px] font-bold">COHORT</span>
                      </div>
                      <p className="text-xs text-tsc">Bi-weekly livestream sponsored segments with dedicated landing page attribution.</p>
                      <div className="flex items-center justify-between pt-2 text-xs font-mono text-on-surface">
                        <span>Clicks: <strong>3,338</strong></span>
                        <span className="text-primary font-bold">Conv: 2.18%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="hidden flex flex-col gap-4" id="tab-panel-ledger">
                <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-base font-headline font-bold text-on-surface">Commission Attributed Log (1,480 Records)</h2>
                    <span className="text-xs text-tsc font-mono">Real-time ledger pipeline</span>
                  </div>
                  <div className="bg-surface-container-low p-4 rounded-xl text-xs space-y-3 font-mono">
                    <div className="flex items-center justify-between py-2 border-b border-surface-container-high">
                      <span>TX-984210 · Phase 1 $200k Scalper Challenge</span>
                      <span className="font-bold text-primary">+$180.00 (20.0%)</span>
                    </div>
                    <div className="flex items-center justify-between py-2 border-b border-surface-container-high">
                      <span>TX-984188 · Phase 1 $100k Standard Challenge</span>
                      <span className="font-bold text-primary">+$98.00 (20.0%)</span>
                    </div>
                    <div className="flex items-center justify-between py-2 border-b border-surface-container-high">
                      <span>TX-984021 · Phase 2 Reset &amp; Extend Add-on</span>
                      <span className="font-bold text-primary">+$45.00 (20.0%)</span>
                    </div>
                    <div className="flex items-center justify-between py-2">
                      <span>TX-983995 · Phase 1 $50k Micro Trader</span>
                      <span className="font-bold text-primary">+$54.00 (20.0%)</span>
                    </div>
                  </div>
                </div>
              </div>
              <div className="hidden flex flex-col gap-4" id="tab-panel-audit">
                <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm">
                  <h2 className="text-base font-headline font-bold text-on-surface mb-3">Cryptographic Write-Once-Read-Many Log</h2>
                  <p className="text-xs text-tsc mb-4">Immutable audit hash verified under SEC Rule 17a-4 and MiFID II RTS 25 compliance specifications.</p>
                  <div className="space-y-3 font-mono text-xs">
                    <div className="bg-surface-container-low p-3.5 rounded-xl flex items-start gap-3">
<MsIcon name="lock" className="text-primary text-[18px] mt-0.5" />
                      <div className="flex-1">
                        <div className="flex items-center justify-between text-on-surface font-semibold">
                          <span>AFFILIATE_PAYOUT_BATCH_DISPATCH</span>
                          <span className="text-tsc text-[11px]">2025-05-01 08:30:12 UTC</span>
                        </div>
                        <div className="text-[11px] text-tsc mt-1">Hash: 0x9f2a4b88d3f1092a83c79124401824efbca92837482a9d82e1c</div>
                      </div>
                    </div>
                    <div className="bg-surface-container-low p-3.5 rounded-xl flex items-start gap-3">
<MsIcon name="verified" className="text-primary text-[18px] mt-0.5" />
                      <div className="flex-1">
                        <div className="flex items-center justify-between text-on-surface font-semibold">
                          <span>RATE_RENEWAL_TIER_PLATINUM</span>
                          <span className="text-tsc text-[11px]">2025-04-14 12:00:00 UTC</span>
                        </div>
                        <div className="text-[11px] text-tsc mt-1">Hash: 0x82b9410940dcf92a188f40192a01948ba932400192aef1920ac</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="sticky bottom-4 z-30 bg-surface-container-lowest/95 backdrop-blur-md rounded-2xl p-4 shadow-md flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-2.5 flex-wrap">
                <button className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-surface-container hover:bg-surface-container-high text-on-surface transition-colors" onClick={() => setSo0(true)}>
<MsIcon name="edit" className="text-[16px]" />
                  <span>Edit Profile</span>
                </button>
                <button className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-primary hover:bg-primary/90 text-on-primary shadow-sm transition-all">
<MsIcon name="payments" className="text-[16px]" />
                  <span>Pay Outstanding Commission ($24.5k)</span>
                </button>
                <button className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-surface-container hover:bg-surface-container-high text-on-surface transition-colors">
<MsIcon name="mail" className="text-[16px]" />
                  <span>Send Message</span>
                </button>
              </div>
              <div className="flex items-center gap-2">
                <button className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-surface-container-low text-tertiary hover:bg-tertiary-container/30 transition-colors">
<MsIcon name="lock_reset" className="text-[16px]" />
                  <span>Reset Referral Code</span>
                </button>
                <button className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-error-container text-error hover:bg-error/15 transition-colors" onClick={() => setSo1(true)}>
<MsIcon name="block" className="text-[16px]" />
                  <span>Suspend Affiliate</span>
                </button>
              </div>
            </div>
          </div>
          <div className="lg:col-span-4 flex flex-col gap-6">
            <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm flex flex-col gap-5">
              <div className="flex items-center gap-3.5">
                <div className="w-13 h-13 w-12 h-12 rounded-2xl bg-primary/15 text-primary flex items-center justify-center font-headline font-bold text-lg shrink-0">                  ACM</div>
                <div className="flex flex-col min-w-0">
                  <div className="flex items-center gap-1.5">
                    <span className="font-headline font-bold text-on-surface truncate">Alpha Capital Media</span>
<MsIcon name="verified" className="text-[16px] text-primary" />
                  </div>
                  <span className="text-xs text-tsc font-mono">@alphacap</span>
                </div>
              </div>
              <div className="space-y-3 pt-2 text-xs">
                <div className="flex items-center justify-between py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Partner ID</span>
                  <span className="font-mono font-bold text-on-surface">ACM-8921</span>
                </div>
                <div className="flex items-center justify-between py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Primary Email</span>
                  <a className="font-medium text-primary hover:underline truncate max-w-[170px]" href="mailto:partners@alphacapitalmedia.com">partners@alphacapitalmedia.com</a>
                </div>
                <div className="flex items-center justify-between py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Phone</span>
                  <span className="text-on-surface font-mono">+1 (312) 555-0198</span>
                </div>
                <div className="flex items-center justify-between py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Jurisdiction</span>
                  <div className="flex items-center gap-1.5">
                    <span className="text-sm">🇺🇸</span>
                    <span className="font-semibold text-on-surface">United States</span>
                    <span className="px-1.5 py-0.5 rounded bg-surface-container text-[10px] font-mono">USA</span>
                  </div>
                </div>
                <div className="flex flex-col gap-1 py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Tier Level</span>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-on-surface">Platinum Institutional</span>
                    <span className="text-[11px] font-medium text-primary bg-primary/10 px-2 py-0.5 rounded">15% Base + 5% Accel</span>
                  </div>
                </div>
                <div className="flex flex-col gap-1 py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Commission Model</span>
                  <span className="font-semibold text-on-surface">20.0% Lifetime RevShare (Eval Accounts)</span>
                </div>
                <div className="flex flex-col gap-1.5 py-1.5 border-b border-surface-container">
                  <span className="text-tsc font-medium">Default Referral Ingress</span>
                  <div className="flex items-center gap-1.5 bg-surface-container-low p-2 rounded-xl">
                    <span className="font-mono text-[11px] text-on-surface truncate flex-1">trade.terradesk.com/r/ALPHACAP-SCALP</span>
                    <button className="p-1 rounded text-tsc hover:text-primary transition-colors" title="Copy URL"><MsIcon name="content_copy" className="text-[16px]" /></button>
                  </div>
                </div>
                <div className="flex flex-col gap-1 py-1.5">
                  <span className="text-tsc font-medium">Default Campaign</span>
                  <span className="font-semibold text-on-surface">Summer Scalper Accelerator 2025</span>
                </div>
              </div>
            </div>
            <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm flex flex-col gap-4">
              <div className="flex items-center gap-2">
<MsIcon name="badge" className="text-primary text-[20px]" />
                <h2 className="text-base font-headline font-bold text-on-surface">Primary Contact</h2>
              </div>
              <div className="bg-surface-container-low p-4 rounded-xl flex flex-col gap-3">
                <div>
                  <div className="text-sm font-bold text-on-surface">Marcus Sterling</div>
                  <div className="text-xs text-tsc font-medium">Head of Strategic Partnerships</div>
                </div>
                <div className="space-y-1.5 text-xs pt-1">
                  <div className="flex items-center gap-2 text-tsc">
<MsIcon name="mail" className="text-[16px] text-outline" />
                    <a className="text-primary hover:underline truncate" href="mailto:m.sterling@alphacapitalmedia.com">m.sterling@alphacapitalmedia.com</a>
                  </div>
                  <div className="flex items-center gap-2 text-tsc">
<MsIcon name="call" className="text-[16px] text-outline" />
                    <span className="font-mono text-on-surface">+1 (312) 840-2214 (Signal)</span>
                  </div>
                  <div className="flex items-center gap-2 text-tsc">
<MsIcon name="send" className="text-[16px] text-outline" />
                    <span className="text-on-surface">Telegram: <strong className="text-primary">@msterling_acm</strong></span>
                  </div>
                  <div className="flex items-center gap-2 text-tsc">
<MsIcon name="schedule" className="text-[16px] text-outline" />
                    <span className="text-on-surface">UTC-5 (Chicago · Current: 09:24 AM)</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1.5">
                <span className="text-xs font-bold uppercase tracking-wider text-tsc">Operational Notes</span>
                <div className="bg-surface-container-low p-3.5 rounded-xl text-xs text-on-surface-variant leading-relaxed">
                  High-value YouTube and Discord prop trading syndicate. Whitelisted for custom
                  <strong className="text-on-surface">$200k scaling tier promotions</strong>
                  and priority payout batching.
                </div>
              </div>
            </div>
            <div className="bg-surface-container-lowest rounded-2xl p-6 shadow-sm flex flex-col gap-4">
              <div className="flex items-center gap-2">
<MsIcon name="hub" className="text-primary text-[20px]" />
                <h2 className="text-base font-headline font-bold text-on-surface">Linked Ecosystem Resources</h2>
              </div>
              <div className="space-y-3 text-xs">
                <div className="bg-surface-container-low p-3 rounded-xl flex items-center justify-between">
                  <div className="flex items-center gap-2">
<MsIcon name="campaign" className="text-[18px] text-primary" />
                    <span className="font-semibold text-on-surface">Linked Campaigns</span>
                  </div>
                  <span className="font-mono font-bold text-primary bg-primary/10 px-2 py-0.5 rounded">4 Live</span>
                </div>
                <div className="bg-surface-container-low p-3 rounded-xl flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
<MsIcon name="loyalty" className="text-[18px] text-tertiary" />
                      <span className="font-semibold text-on-surface">Linked Coupon Codes</span>
                    </div>
                    <span className="font-mono text-tsc">2 Codes</span>
                  </div>
                  <div className="flex items-center gap-2 pt-1 font-mono">
                    <span className="px-2 py-1 rounded bg-surface-container text-[11px] font-bold text-on-surface">SUMMER20 (-20%)</span>
                    <span className="px-2 py-1 rounded bg-surface-container text-[11px] font-bold text-on-surface">ALPHACAP15 (-15%)</span>
                  </div>
                </div>
                <div className="bg-surface-container-low p-3 rounded-xl flex items-center justify-between">
                  <div className="flex items-center gap-2">
<MsIcon name="traffic" className="text-[18px] text-primary" />
                    <span className="font-semibold text-on-surface">Active Ingress Links</span>
                  </div>
                  <span className="font-mono font-bold text-on-surface">6 Tracking URLs</span>
                </div>
                <div className="p-3 rounded-xl bg-primary/5 flex items-start gap-2.5">
<MsIcon name="history_toggle_off" className="text-[18px] text-primary mt-0.5 shrink-0" />
                  <div className="flex flex-col gap-0.5">
                    <span className="font-bold text-on-surface text-[11px]">Last Activity Detected</span>
                    <span className="text-tsc text-[11px]">Inbound conversion recorded <strong>14 mins ago</strong> (Trader #TR-948210 · $100k Phase 1).</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-12 pt-6 pb-2 text-center flex flex-col items-center justify-center gap-1.5 text-xs text-tsc">
          <div className="flex items-center gap-2 flex-wrap justify-center">
<MsIcon name="verified_user" className="text-[16px] text-primary" />
            <span className="font-semibold text-on-surface">TerraDesk SEC Rule 17a-4 / MiFID II RTS 25 Compliant Institutional Affiliate Gateway</span>
            <span className="text-outline-variant">•</span>
            <span className="font-mono">Ledger State: SYNCHRONIZED</span>
          </div>
          <p className="text-[11px] text-tsc">All partner attribution events are cryptographically hashed and committed to non-rewriteable immutable storage.</p>
        </div>
      </div>
      {so0 && (
        <>
        <div className="fixed inset-0 z-50 bg-[#23201d]/65 backdrop-blur-sm transition-opacity duration-300" id="modal-overlay">
          <div className="relative w-full h-full flex justify-end">
            <div className="flex-1 h-full cursor-pointer"></div>
            <aside aria-label="Edit Profile Slide-Over" className="relative w-full max-w-[624px] h-full bg-surface-bright flex flex-col shadow-2xl z-20 overflow-hidden transform transition-all duration-300 ease-out">
              <header className="px-7 py-5 bg-surface-container-low shrink-0 shadow-sm flex items-center justify-between">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-primary"></span>
                    <h2 className="font-headline text-lg font-bold text-on-surface tracking-tight">                      Edit Affiliate Profile — Alpha Capital Media</h2>
                  </div>
                  <p className="text-xs text-tsc font-mono">
                    UID: #ACM-8921 ·
                    <span className="text-tertiary font-semibold">Tier 1 Master Partner</span>
                  </p>
                </div>
                <button aria-label="Close dialog" className="w-9 h-9 rounded-xl bg-surface-container hover:bg-surface-container-highest flex items-center justify-center text-on-surface-variant hover:text-on-surface transition-colors cursor-pointer" onClick={() => setSo0(false)}><MsIcon name="close" className="text-[20px]" /></button>
              </header>
              <div className="flex-1 overflow-y-auto px-7 py-6 space-y-7">
                <section className="space-y-4">
                  <div className="flex items-center gap-2">
<MsIcon name="corporate_fare" className="text-primary text-[18px]" />
                    <h3 className="font-headline text-sm font-bold text-on-surface">1. Organization &amp; Identity</h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5 md:col-span-2">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Partner Public Brand Name</label>
                      <div className="relative">
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-sm font-semibold text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all" type="text" defaultValue="Alpha Capital Media" />
                        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-primary font-bold">Verified</span>
                      </div>
                    </div>
                    <div className="space-y-1.5 md:col-span-2">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Partner Legal Entity</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-sm text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all" type="text" defaultValue="Alpha Capital Media LLC" />
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Primary Business Email</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-mono text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all" type="email" defaultValue="partners@alphacapitalmedia.com" />
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Contact Phone</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-mono text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all" type="tel" defaultValue="+1 (312) 555-0198" />
                    </div>
                    <div className="space-y-1.5 md:col-span-2">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Jurisdiction / Country</label>
                      <div className="relative">
                        <select className="w-full appearance-none bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all cursor-pointer" defaultValue="United States (USA)">
                          <option>United States (USA)</option>
                          <option>United Kingdom (UK)</option>
                          <option>United Arab Emirates (UAE)</option>
                          <option>Singapore (SG)</option>
                          <option>Switzerland (CH)</option>
                        </select>
<MsIcon name="expand_more" className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px]" />
                      </div>
                    </div>
                  </div>
                </section>
                <div className="h-px bg-surface-container-highest"></div>
                <section className="space-y-4">
                  <div className="flex items-center gap-2">
<MsIcon name="payments" className="text-tertiary text-[18px]" />
                    <h3 className="font-headline text-sm font-bold text-on-surface">2. Tier &amp; Compensation Terms</h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Tier Level Classification</label>
                      <div className="relative">
                        <select className="w-full appearance-none bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-semibold text-tertiary focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm cursor-pointer" defaultValue="Platinum Institutional Master">
                          <option>Bronze Syndicate</option>
                          <option>Silver Professional</option>
                          <option>Gold Institutional</option>
                          <option>Platinum Institutional Master</option>
                        </select>
<MsIcon name="expand_more" className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px]" />
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">RevShare Override Rate</label>
                      <div className="relative">
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-bold text-primary focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm" type="text" defaultValue="20.0%" />
<MsIcon name="lock_reset" className="absolute right-3 top-1/2 -translate-y-1/2 text-[16px] text-tertiary" />
                      </div>
                    </div>
                    <div className="md:col-span-2 bg-surface-container-low/70 rounded-xl p-3 flex items-start gap-2.5">
<MsIcon name="info" className="text-tertiary text-[18px] shrink-0 mt-0.5" />
                      <p className="text-[11px] leading-relaxed text-tsc">                        Standard Platinum tier rate is 15%. Overridden +5% per Q1 Executive Accord authorized by Marcus Vance.</p>
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Payment Terms</label>
                      <div className="relative">
                        <select className="w-full appearance-none bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm cursor-pointer" defaultValue="Net-15 End of Month">
                          <option>Weekly (Rolling Fridays)</option>
                          <option>Bi-Weekly (1st &amp; 15th)</option>
                          <option>Net-15 End of Month</option>
                          <option>Net-30 Standard</option>
                        </select>
<MsIcon name="expand_more" className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px]" />
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Preferred Settlement Method</label>
                      <div className="relative">
                        <select className="w-full appearance-none bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm cursor-pointer" defaultValue="Wire Transfer (USD)">
                          <option>Wire Transfer (USD)</option>
                          <option>USDC ERC-20 (Treasury Auto-Sweep)</option>
                          <option>EUR SEPA Institutional</option>
                        </select>
<MsIcon name="expand_more" className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px]" />
                      </div>
                    </div>
                  </div>
                </section>
                <div className="h-px bg-surface-container-highest"></div>
                <section className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
<MsIcon name="contact_page" className="text-primary text-[18px]" />
                      <h3 className="font-headline text-sm font-bold text-on-surface">3. Primary Contact Rep</h3>
                    </div>
                    <span className="text-[11px] font-semibold text-tsc">Account Assigned Desk Rep</span>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Contact Name</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-semibold text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm" type="text" defaultValue="Marcus Sterling" />
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Job Title</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm" type="text" defaultValue="Head of Strategic Partnerships" />
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Direct Email</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-mono text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm" type="email" defaultValue="m.sterling@alphacapitalmedia.com" />
                    </div>
                    <div className="space-y-1.5">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Telegram / Signal Handle</label>
<input className="w-full bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-mono text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm" type="text" defaultValue="@msterling_acm" />
                    </div>
                    <div className="space-y-1.5 md:col-span-2">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Timezone Affinity</label>
                      <div className="relative">
                        <select className="w-full appearance-none bg-surface-container-low px-4 py-2.5 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm cursor-pointer" defaultValue="America/Chicago (UTC-5 · Central Time)">
                          <option>America/Chicago (UTC-5 · Central Time)</option>
                          <option>America/New_York (UTC-4 · Eastern Time)</option>
                          <option>Europe/London (UTC+0 · GMT)</option>
                          <option>Asia/Dubai (UTC+4 · GST)</option>
                        </select>
<MsIcon name="expand_more" className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px]" />
                      </div>
                    </div>
                  </div>
                </section>
                <div className="h-px bg-surface-container-highest"></div>
                <section className="space-y-4">
                  <div className="flex items-center gap-2">
<MsIcon name="gavel" className="text-primary text-[18px]" />
                    <h3 className="font-headline text-sm font-bold text-on-surface">4. Operational Notes &amp; Compliance</h3>
                  </div>
                  <div className="space-y-1.5">
                    <div className="flex items-center justify-between">
                      <label className="block text-xs font-bold uppercase tracking-wider text-tsc">Compliance &amp; Execution Notes</label>
                      <span className="text-[10px] text-tsc">Confidential to Prop Desk</span>
                    </div>
<textarea className="w-full bg-surface-container-low p-3 rounded-xl text-xs leading-relaxed text-on-surface focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm transition-all resize-none" rows={3} defaultValue="High-value YouTube and Discord prop trading syndicate. Whitelisted for custom $200k scaling tier promotions and priority payout batching." />
                  </div>
                  <div className="space-y-3 pt-1">
                    <label className="flex items-center justify-between p-3.5 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
                      <div className="space-y-0.5 pr-4">
                        <div className="text-xs font-bold text-on-surface">Auto-approve referral link creation</div>
                        <div className="text-[11px] text-tsc">Allows partner sub-affiliates to generate custom UTM tags without compliance pre-screening.</div>
                      </div>
                      <div className="relative inline-flex items-center shrink-0">
<input defaultChecked className="sr-only peer" id="auto-link-toggle" type="checkbox" />
                        <div className="w-11 h-6 bg-surface-variant peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                      </div>
                    </label>
                    <label className="flex items-center justify-between p-3.5 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
                      <div className="space-y-0.5 pr-4">
                        <div className="text-xs font-bold text-on-surface">Exempt from minimum payout threshold ($500)</div>
                        <div className="text-[11px] text-tsc">Bypasses reserve constraints to disperse daily or ad-hoc test tranches upon demand.</div>
                      </div>
                      <div className="relative inline-flex items-center shrink-0">
<input defaultChecked className="sr-only peer" id="exempt-threshold-toggle" type="checkbox" />
                        <div className="w-11 h-6 bg-surface-variant peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                      </div>
                    </label>
                  </div>
                </section>
                <div className="bg-surface-container rounded-xl p-3 flex items-center gap-3">
<MsIcon name="history_edu" className="text-tsc text-[18px]" />
                  <div className="text-[11px] text-tsc">

              Last modified: <span className="font-mono font-medium text-on-surface">Feb 24, 2025 at 16:32 NY4</span> by <span className="font-medium text-on-surface">M. Vance</span>

                  </div>
                </div>
              </div>
              <footer className="px-7 py-4 bg-surface-container-low shrink-0 shadow-lg flex items-center justify-between gap-4">
                <button className="px-5 py-2.5 rounded-xl bg-surface-container hover:bg-surface-container-highest text-tsc hover:text-on-surface text-xs font-bold transition-all cursor-pointer" onClick={() => setSo0(false)}>                  Cancel</button>
                <div className="flex items-center gap-3">
                  <button className="px-6 py-2.5 rounded-xl bg-primary hover:opacity-90 active:scale-[0.98] text-on-primary text-xs font-bold shadow-md flex items-center gap-2 transition-all cursor-pointer" onClick={() => setSo0(false)}>
<MsIcon name="check" className="text-[16px]" />
                    Save Profile Changes
                  </button>
                </div>
              </footer>
            </aside>
          </div>
        </div>
        </>
      )}
      {so1 && (
        <>
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-inverse-surface/60 backdrop-blur-sm transition-all duration-200" id="modal-container">
          <div className="relative w-full max-w-[560px] bg-surface-container-lowest rounded-xl shadow-[0_20px_50px_rgba(46,50,48,0.22)] overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            <div className="h-1.5 w-full bg-error"></div>
            <div className="p-6 sm:p-7 space-y-6">
              <div className="flex items-start gap-4">
                <div className="w-11 h-11 rounded-full bg-error-container text-error flex items-center justify-center shrink-0 shadow-sm"><MsIcon name="gavel" className="text-[24px]" /></div>
                <div className="flex-1 min-w-0">
                  <div className="text-[10px] tracking-widest uppercase font-bold text-error">                    {"               PARTNER PROGRAM SURVEILLANCE // REGULATORY SUSPENSION             "}</div>
                  <h2 className="text-xl font-headline font-bold text-on-surface tracking-tight mt-1 leading-snug">                    Suspend Affiliate Partner Alpha Capital Media?</h2>
                  <div className="text-xs text-tsc mt-1 font-mono flex flex-wrap items-center gap-1.5">
                    <span>UID: #ACM-8921</span>
                    <span>·</span>
                    <span>Ref Code: ALPHACAP</span>
                    <span>·</span>
                    <span>4 Active Campaigns</span>
                    <span>·</span>
                    <span>6 Live Tracking Links</span>
                  </div>
                </div>
                <button className="text-tsc hover:text-on-surface p-1 rounded-lg hover:bg-surface-container transition-colors" title="Close dialog" onClick={() => setSo1(false)}><MsIcon name="close" className="text-[20px]" /></button>
              </div>
              <div className="bg-error-container/40 rounded-xl p-4 text-on-surface text-xs space-y-2.5 leading-relaxed">
                <div className="flex items-start gap-2.5 text-on-surface">
<MsIcon name="report_problem" className="text-error text-[16px] shrink-0 mt-0.5" />
                  <span>

<strong className="font-semibold text-error">Ingress Traffic Halt:</strong> All 6 public tracking URLs (including <span className="font-mono font-medium">ALPHACAP-SCALP</span>) will immediately cease redirecting and display a compliant program unavailable landing notice.
            
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-on-surface">
<MsIcon name="lock_clock" className="text-error text-[16px] shrink-0 mt-0.5" />
                  <span>

<strong className="font-semibold text-error">Commission Accrual Frozen:</strong> <span className="font-bold text-on-surface">$24,500.00</span> in pending payouts will be quarantined and held from the next scheduled disbursement batch.
            
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-on-surface-variant pt-1 border-t-0">
<MsIcon name="verified_user" className="text-primary text-[16px] shrink-0 mt-0.5" />
                  <span>
                    <strong className="font-semibold text-on-surface">Attribution Protection:</strong>
                    Historical attributed conversions and previous ledger records remain immutable in the WORM audit registry.
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-on-surface-variant">
<MsIcon name="replay" className="text-primary text-[16px] shrink-0 mt-0.5" />
                  <span>
                    <strong className="font-semibold text-on-surface">Reversibility:</strong>
                    Suspension can be lifted by Compliance Officers (Level 3+) following formal review.
                  </span>
                </div>
              </div>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <label className="block text-xs font-bold uppercase tracking-wider text-tsc" htmlFor="regulatory-reason">
                    Regulatory Suspension Reason
                    <span className="text-error">*</span>
                  </label>
                  <div className="relative">
                    <select className="w-full appearance-none bg-surface-container-low text-xs font-semibold text-on-surface px-3.5 py-2.5 rounded-lg focus:outline-none focus:ring-1 focus:ring-primary shadow-sm pr-9" id="regulatory-reason" defaultValue="audit">
                      <option value="audit">Affiliate Agreement Renewal &amp; Compliance Audit</option>
                      <option value="bot">Suspicious Traffic / Bot Activity</option>
                      <option value="disclosure">Regulatory Disclosure Violation</option>
                      <option value="breach">Agreement Breach</option>
                      <option value="complaint">Trader Complaint Escalation</option>
                    </select>
<MsIcon name="arrow_drop_down" className="absolute right-3 top-1/2 -translate-y-1/2 text-tsc pointer-events-none text-[18px]" />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="block text-xs font-bold uppercase tracking-wider text-tsc" htmlFor="compliance-note">
                      Internal Compliance Note
                      <span className="text-error">*</span>
                    </label>
                    <span className="text-[10px] text-tsc">Logged to SEC Rule 17a-4 Vault</span>
                  </div>
<textarea className="w-full bg-surface-container-low text-xs text-on-surface p-3 rounded-lg focus:outline-none focus:ring-1 focus:ring-primary shadow-sm resize-none leading-relaxed" id="compliance-note" rows={3} defaultValue="Initiating temporary operational suspension pending verification of Q2 promotional disclaimers on YouTube and Discord syndication channels." />
                </div>
                <div className="bg-surface-container-low rounded-lg p-3 flex items-start gap-3">
<input defaultChecked className="mt-0.5 h-4 w-4 rounded accent-primary bg-surface-container cursor-pointer" id="audit-ledger-confirm" type="checkbox" />
                  <label className="text-xs text-on-surface leading-snug cursor-pointer select-none" htmlFor="audit-ledger-confirm">
                    I confirm that this suspension has been reviewed with the
                    <strong className="font-semibold text-on-surface">Head of Compliance</strong>
                    and will be logged to SEC Rule 17a-4 audit ledger.
                  </label>
                </div>
              </div>
              <div className="flex flex-col-reverse sm:flex-row items-center justify-between gap-3 pt-2">
                <button className="w-full sm:w-auto px-4 py-2.5 text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container-high rounded-lg transition-colors text-center" type="button" onClick={() => setSo1(false)}>                  Cancel &amp; Keep Active</button>
                <button className="w-full sm:w-auto px-5 py-2.5 rounded-lg bg-error hover:opacity-90 active:scale-[0.99] text-on-error font-medium text-xs shadow-sm flex items-center justify-center gap-2 transition-all" id="confirm-suspend-btn" type="button" onClick={() => setSo1(false)}>
                  <span>Confirm &amp; Suspend Partner</span>
                  <span className="text-sm">🚫</span>
                </button>
              </div>
            </div>
            <div className="bg-surface-container-low px-6 py-2.5 text-[10px] text-tsc flex items-center justify-between">
              <span className="font-mono">SESSION: CRO-AUTH-NY4-8902</span>
              <span className="flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                Audit Ledger Immutable Write Mode
              </span>
            </div>
          </div>
        </div>
        </>
      )}
    </>
  );
}
