"use client";

/**
 * Training Data Export — Stitch conversion (view-id: `ai-training-export`)
 *
 * Source: stitch_screens/training_data_export
 * Spec: [NEW] · overlay states: 2/2 wired
 * States: training_data_export_cancel_active_export_confirmation_alertdialog_state✓, training_data_export_export_detail_anonymization_audit_sheet_state✓
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import * as React from "react";
import { MsIcon } from "@/components/stitch/stitch";

export function AiTrainingExportStitchPage() {
  const [so0, setSo0] = React.useState(false);
  const [so1, setSo1] = React.useState(false);
  return (
    <>
      <div className="flex flex-col w-full">
        <div className="px-8 py-3 bg-surface-container-low flex flex-wrap items-center justify-between gap-4">
          <div className="flex flex-wrap items-center gap-3 text-xs">
            <div className="flex items-center gap-1.5 font-medium text-outline uppercase tracking-wider text-[11px]">
              <span>Operations</span>
<MsIcon name="chevron_right" className="text-[14px]" />
              <span>AI &amp; Intelligence</span>
<MsIcon name="chevron_right" className="text-[14px]" />
              <span className="text-on-surface font-semibold">Training Data Export</span>
            </div>
            <span className="text-outline-variant font-light">|</span>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface-container text-on-surface text-[11px] font-medium shadow-sm">
              <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
              <span className="font-semibold text-primary uppercase tracking-wider">Export Pipeline: Active</span>
              <span className="text-outline">·</span>
              <span className="text-on-surface-variant">SHA-256 Verified</span>
              <span className="text-outline">·</span>
              <span className="text-on-surface-variant">ClickHouse &amp; S3 Parquet</span>
              <span className="text-outline">·</span>
              <span className="text-tertiary font-bold tracking-tight">WORM Audit: LOCKED</span>
            </div>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-surface-container-high text-xs font-medium text-on-surface shadow-sm cursor-pointer hover:bg-surface-variant transition-colors">
<MsIcon name="domain" className="text-[16px] text-primary" />
            <span className="font-semibold">Alpha Capital Media</span>
            <span className="text-[10px] px-1.5 py-0.5 rounded bg-surface-container font-mono text-outline">#TNT-104</span>
<MsIcon name="expand_more" className="text-[16px] text-outline" />
          </div>
        </div>
        <div className="px-8 py-6 space-y-6">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-2xl bg-primary-fixed flex items-center justify-center text-primary shadow-sm shrink-0"><MsIcon name="dataset" className="text-[28px]" fill /></div>
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-3">
                  <h1 className="font-headline font-bold text-2xl tracking-tight text-on-surface">Training Data Export</h1>
                  <span className="px-2.5 py-0.5 rounded-md bg-secondary-container text-on-secondary-container text-[11px] font-bold uppercase tracking-wider shadow-sm">                    SEC 17a-4 Compliant</span>
                  <span className="px-2 py-0.5 rounded-md bg-surface-container-high text-on-surface-variant text-[11px] font-medium flex items-center gap-1 font-mono">
<MsIcon name="lock" className="text-[13px] text-primary" />
                    WORM Storage Active
                  </span>
                </div>
                <p className="text-xs md:text-sm text-on-surface-variant max-w-3xl leading-relaxed">                  Curate, filter, and export high-integrity training datasets for frontier fine-tuning, retrieval augmentation, and compliance audit archives. Every dataset is immutably hashed and timestamped.</p>
              </div>
            </div>
            <div className="flex items-center gap-3 shrink-0">
              <button className="px-4 py-2.5 rounded-xl bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-semibold flex items-center gap-2 transition-all shadow-sm" type="button" onClick={() => setSo1(true)}>
<MsIcon name="menu_book" className="text-[16px] text-outline" />
                <span>Export History Docs ↗</span>
              </button>
              <button className="px-4 py-2.5 rounded-xl bg-primary hover:opacity-95 text-on-primary text-xs font-semibold flex items-center gap-2 shadow-md transition-all active:scale-95" id="toggle-drawer-btn" type="button">
<MsIcon name="add_circle" className="text-[18px]" />
                <span>+ New Export</span>
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="p-5 rounded-2xl bg-surface-container-low shadow-sm flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-outline">Total Exports</span>
                <div className="w-8 h-8 rounded-xl bg-primary-fixed/60 text-primary flex items-center justify-center"><MsIcon name="database" className="text-[18px]" /></div>
              </div>
              <div className="mt-3">
                <div className="flex items-baseline gap-2">
                  <span className="font-headline font-bold text-3xl text-on-surface tracking-tight">42</span>
                  <span className="text-xs font-bold text-primary flex items-center">
<MsIcon name="trending_up" className="text-[14px]" />
                    +8 this quarter
                  </span>
                </div>
                <p className="text-[11px] text-on-surface-variant mt-1 font-medium">Across 5 live data pipelines</p>
              </div>
              <div className="absolute -right-4 -bottom-4 w-20 h-20 bg-primary/5 rounded-full blur-xl group-hover:scale-125 transition-transform"></div>
            </div>
            <div className="p-5 rounded-2xl bg-surface-container-low shadow-sm flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-outline">Total Rows Exported</span>
                <div className="w-8 h-8 rounded-xl bg-secondary-container text-on-secondary-container flex items-center justify-center"><MsIcon name="stacks" className="text-[18px]" /></div>
              </div>
              <div className="mt-3">
                <div className="flex items-baseline gap-2">
                  <span className="font-headline font-bold text-3xl text-on-surface tracking-tight">3.48M</span>
                  <span className="text-[11px] font-mono text-outline">tokens ~1.8B</span>
                </div>
                <p className="text-[11px] text-on-surface-variant mt-1 font-medium">2.1M Chat &amp; Reasoning · 890k Risk Alerts</p>
              </div>
              <div className="absolute -right-4 -bottom-4 w-20 h-20 bg-tsc/5 rounded-full blur-xl group-hover:scale-125 transition-transform"></div>
            </div>
            <div className="p-5 rounded-2xl bg-surface-container-low shadow-sm flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-outline">Pending / Building</span>
                <div className="w-8 h-8 rounded-xl bg-tertiary-fixed text-on-tertiary-fixed flex items-center justify-center"><MsIcon name="progress_activity" className="text-[18px] animate-spin" /></div>
              </div>
              <div className="mt-3">
                <div className="flex items-baseline gap-2">                  <span className="font-headline font-bold text-3xl text-on-surface tracking-tight">2 In Queue</span></div>
                <div className="mt-1 flex items-center gap-1.5">
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-tertiary-fixed-dim/40 text-on-tertiary-container text-[10px] font-bold">
                    <span className="w-1.5 h-1.5 rounded-full bg-tertiary animate-ping"></span>
                    1 Building · 1 Queued in batch engine
                  </span>
                </div>
              </div>
              <div className="absolute -right-4 -bottom-4 w-20 h-20 bg-tertiary/5 rounded-full blur-xl group-hover:scale-125 transition-transform"></div>
            </div>
            <div className="p-5 rounded-2xl bg-surface-container-low shadow-sm flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-outline">Last Successful Export</span>
                <div className="w-8 h-8 rounded-xl bg-primary-fixed text-on-primary-fixed-variant flex items-center justify-center"><MsIcon name="verified" className="text-[18px]" /></div>
              </div>
              <div className="mt-3">
                <div className="flex items-baseline gap-2">
                  <span className="font-headline font-bold text-3xl text-on-surface tracking-tight">14m ago</span>
                  <span className="text-[10px] font-bold text-primary bg-primary-fixed px-1.5 py-0.5 rounded">Ready</span>
                </div>
                <p className="text-[11px] text-on-surface-variant mt-1 font-mono">Dataset #EXP-90412 · 420k rows</p>
              </div>
              <div className="absolute -right-4 -bottom-4 w-20 h-20 bg-primary/5 rounded-full blur-xl group-hover:scale-125 transition-transform"></div>
            </div>
          </div>
          <div className="rounded-2xl bg-surface-container-low p-4 shadow-sm flex flex-wrap items-center justify-between gap-4">
            <div className="flex flex-wrap items-center gap-3">
              <div className="relative">
                <label className="text-[10px] uppercase font-bold text-outline block mb-1">Source Stream</label>
                <div className="flex items-center gap-2 bg-surface px-3 py-2 rounded-xl shadow-sm text-xs font-medium text-on-surface cursor-pointer hover:bg-surface-container transition-colors">
<MsIcon name="filter_alt" className="text-[16px] text-primary" />
                  <span>All Sources</span>
<MsIcon name="expand_more" className="text-[16px] text-outline" />
                </div>
              </div>
              <div className="relative">
                <label className="text-[10px] uppercase font-bold text-outline block mb-1">Status</label>
                <div className="flex items-center gap-2 bg-surface px-3 py-2 rounded-xl shadow-sm text-xs font-medium text-on-surface cursor-pointer hover:bg-surface-container transition-colors">
                  <span>All Statuses (Ready, Building...)</span>
<MsIcon name="expand_more" className="text-[16px] text-outline" />
                </div>
              </div>
              <div className="relative">
                <label className="text-[10px] uppercase font-bold text-outline block mb-1">Format</label>
                <div className="flex items-center gap-2 bg-surface px-3 py-2 rounded-xl shadow-sm text-xs font-medium text-on-surface cursor-pointer hover:bg-surface-container transition-colors">
                  <span className="font-mono text-outline text-[11px]">&#123; &#125;</span>
                  <span>All Formats (JSONL, Parquet)</span>
<MsIcon name="expand_more" className="text-[16px] text-outline" />
                </div>
              </div>
              <div className="relative">
                <label className="text-[10px] uppercase font-bold text-outline block mb-1">Timeline</label>
                <div className="flex items-center gap-2 bg-surface px-3 py-2 rounded-xl shadow-sm text-xs font-medium text-on-surface cursor-pointer hover:bg-surface-container transition-colors">
<MsIcon name="calendar_today" className="text-[16px] text-outline" />
                  <span>Last 30 Days</span>
<MsIcon name="expand_more" className="text-[16px] text-outline" />
                </div>
              </div>
            </div>
            <div className="flex items-center gap-3 self-end">
              <span className="text-xs font-medium text-outline">
                Showing
                <span className="font-bold text-on-surface">6</span>
                of 42 datasets
              </span>
              <button className="px-3 py-2 rounded-xl bg-surface hover:bg-surface-container text-xs font-semibold text-on-surface-variant flex items-center gap-1.5 transition-colors shadow-sm" type="button">
<MsIcon name="restart_alt" className="text-[15px]" />
                <span>Reset Filters</span>
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
            <div className="xl:col-span-7 flex flex-col gap-4">
              <div className="bg-surface-container-low rounded-2xl p-5 shadow-sm">
                <div className="flex items-center justify-between pb-4">
                  <div className="flex items-center gap-2">
                    <h2 className="font-headline font-semibold text-base text-on-surface">Dataset Exports</h2>
                    <span className="px-2 py-0.5 rounded-full bg-surface-container-high text-xs font-bold text-outline font-mono">42 datasets</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="relative">
<MsIcon name="search" className="absolute left-2.5 top-2 text-[16px] text-outline" />
<input className="pl-8 pr-3 py-1.5 bg-surface text-xs text-on-surface rounded-xl placeholder:text-outline/70 focus:outline-none focus:bg-surface-container transition-all w-48" placeholder="Search export ID, hash, user..." type="text" />
                    </div>
                    <button className="p-1.5 rounded-xl bg-surface hover:bg-surface-container text-outline text-xs flex items-center justify-center"><MsIcon name="download_for_offline" className="text-[18px]" /></button>
                  </div>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs text-on-surface">
                    <thead>
                      <tr className="bg-surface-container text-[11px] uppercase font-bold text-outline tracking-wider">
                        <th className="py-3 px-3.5 rounded-l-xl">Export ID</th>
                        <th className="py-3 px-3">Source</th>
                        <th className="py-3 px-3">Filters Summary</th>
                        <th className="py-3 px-3 text-right">Rows</th>
                        <th className="py-3 px-3">Format</th>
                        <th className="py-3 px-3">Status</th>
                        <th className="py-3 px-3">Owner</th>
                        <th className="py-3 px-3.5 rounded-r-xl text-right">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-transparent space-y-2">
                      <tr className="hover:bg-surface-container/60 transition-colors group">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90412</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-surface-container-high text-on-surface font-medium text-[11px]">
<MsIcon name="chat" className="text-[13px] text-primary" />
                            Chat &amp; Reasoning
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-outline truncate" title="min_len: 250, ex_flagged: true, PII: redacted">                            min_len: 250, ex_flagged: true, PII: redacted</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold">420,000</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-tsc">JSONL</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[11px] font-bold">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                            Ready
                          </span>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-primary text-on-primary text-[10px] font-bold flex items-center justify-center">MV</div>
                            <span className="text-[11px] font-medium text-on-surface">M. Vance</span>
                          </div>
                          <span className="text-[10px] text-outline block font-mono">14m / 2m ago</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-95 text-on-primary text-[11px] font-semibold flex items-center gap-1 shadow-sm">
<MsIcon name="download" className="text-[13px]" />
                              <span>Export</span>
                            </button>
                            <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-outline" title="View Filters"><MsIcon name="filter_list" className="text-[15px]" /></button>
                          </div>
                        </td>
                      </tr>
                      <tr className="hover:bg-surface-container/60 transition-colors group">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90398</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-secondary-container text-on-secondary-container font-medium text-[11px]">
<MsIcon name="warning" className="text-[13px]" />
                            Risk Anomalies
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-outline truncate" title="score > 0.85, loss > $2k, verified_breach: true">                            score &gt; 0.85, loss &gt; $2k, verified_breach: true</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold">85,200</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-primary">PARQUET</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[11px] font-bold">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                            Ready
                          </span>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-primary text-on-primary text-[10px] font-bold flex items-center justify-center">MV</div>
                            <span className="text-[11px] font-medium text-on-surface">M. Vance</span>
                          </div>
                          <span className="text-[10px] text-outline block font-mono">2h / 1h ago</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-95 text-on-primary text-[11px] font-semibold flex items-center gap-1 shadow-sm">
<MsIcon name="download" className="text-[13px]" />
                              <span>Export</span>
                            </button>
                            <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-outline" title="View Filters"><MsIcon name="filter_list" className="text-[15px]" /></button>
                          </div>
                        </td>
                      </tr>
                      <tr className="hover:bg-surface-container/60 transition-colors bg-tertiary-fixed/10">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90374</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-surface-container-high text-on-surface font-medium text-[11px]">
<MsIcon name="query_stats" className="text-[13px] text-tertiary" />
                            Predictive Risk
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-outline truncate" title="cohort: 2025-Q1, drawdown_exceeded: true">                            cohort: 2025-Q1, drawdown_exceeded: true</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold">194,500</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-tsc">JSONL</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex flex-col gap-1">
                            <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-tertiary-fixed text-on-tertiary-fixed text-[10px] font-bold">
                              <span className="w-1.5 h-1.5 rounded-full bg-tertiary animate-spin"></span>
                              Building (64%)
                            </span>
                            <div className="w-20 bg-surface-container-high h-1 rounded-full overflow-hidden">                              <div className="bg-tertiary h-1 rounded-full w-[64%]"></div></div>
                          </div>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-tertiary text-on-tertiary text-[10px] font-bold flex items-center justify-center">EA</div>
                            <span className="text-[11px] font-medium text-on-surface">E. Althaus</span>
                          </div>
                          <span className="text-[10px] text-outline block font-mono">3h ago / Building</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">                          <div className="flex items-center justify-end gap-1.5">                            <button className="px-2.5 py-1 rounded-lg bg-surface-container-high hover:bg-error-container hover:text-on-error-container text-outline text-[11px] font-semibold transition-colors">                              Cancel</button></div></td>
                      </tr>
                      <tr className="hover:bg-surface-container/60 transition-colors group">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90350</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-surface-container-high text-on-surface font-medium text-[11px]">
<MsIcon name="lightbulb" className="text-[13px] text-primary" />
                            AI Insights
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-outline truncate" title="domain: Payout Compliance, status: Applied">                            domain: Payout Compliance, status: Applied</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold">24,800</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-outline">CSV</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[11px] font-bold">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                            Ready
                          </span>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-primary text-on-primary text-[10px] font-bold flex items-center justify-center">MV</div>
                            <span className="text-[11px] font-medium text-on-surface">Vance_M</span>
                          </div>
                          <span className="text-[10px] text-outline block font-mono">1d / 1d ago</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-95 text-on-primary text-[11px] font-semibold flex items-center gap-1 shadow-sm">
<MsIcon name="download" className="text-[13px]" />
                              <span>Export</span>
                            </button>
                            <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-outline" title="View Filters"><MsIcon name="filter_list" className="text-[15px]" /></button>
                          </div>
                        </td>
                      </tr>
                      <tr className="hover:bg-surface-container/60 transition-colors group">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90312</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-surface-container-high text-on-surface font-medium text-[11px]">
<MsIcon name="terminal" className="text-[13px] text-tsc" />
                            Custom SQL
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-outline truncate" title="query_hash: 0x9f2a...88, raw_ticks: pruned">                            query_hash: 0x9f2a...88, raw_ticks: pruned</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold">1,250,000</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-primary">PARQUET</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[11px] font-bold">
                            <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                            Ready
                          </span>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-tsc text-on-secondary text-[10px] font-bold flex items-center justify-center">🤖</div>
                            <span className="text-[11px] font-medium text-on-surface">DataOps Bot</span>
                          </div>
                          <span className="text-[10px] text-outline block font-mono">3d / 3d ago</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-95 text-on-primary text-[11px] font-semibold flex items-center gap-1 shadow-sm">
<MsIcon name="download" className="text-[13px]" />
                              <span>Export</span>
                            </button>
                            <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-outline" title="View Filters"><MsIcon name="filter_list" className="text-[15px]" /></button>
                          </div>
                        </td>
                      </tr>
                      <tr className="hover:bg-surface-container/60 transition-colors bg-error-container/20">
                        <td className="py-3.5 px-3.5 font-mono font-bold text-on-surface whitespace-nowrap">                          #EXP-90288</td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-surface-container-high text-on-surface font-medium text-[11px]">
<MsIcon name="chat" className="text-[13px] text-primary" />
                            Chat &amp; Reasoning
                          </span>
                        </td>
                        <td className="py-3.5 px-3 max-w-[200px]">                          <div className="font-mono text-[11px] text-error font-medium truncate" title="raw_unfiltered_debug (validation fail)">                            raw_unfiltered_debug (fail)</div></td>
                        <td className="py-3.5 px-3 text-right font-mono font-semibold text-outline">0</td>
                        <td className="py-3.5 px-3">                          <span className="px-2 py-0.5 rounded bg-surface-container font-mono text-[10px] font-bold text-tsc">JSONL</span></td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-error-container text-on-error-container text-[11px] font-bold">
<MsIcon name="error" className="text-[12px]" />
                            Failed
                          </span>
                        </td>
                        <td className="py-3.5 px-3 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-5 h-5 rounded-full bg-primary text-on-primary text-[10px] font-bold flex items-center justify-center">MV</div>
                            <span className="text-[11px] font-medium text-on-surface">Vance_M</span>
                          </div>
                          <span className="text-[10px] text-error font-mono font-semibold">Error: PII Leak</span>
                        </td>
                        <td className="py-3.5 px-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button className="px-2.5 py-1 rounded-lg bg-surface-container-high hover:bg-surface-variant text-on-surface-variant text-[11px] font-semibold flex items-center gap-1">
<MsIcon name="refresh" className="text-[13px]" />
                              <span>Retry</span>
                            </button>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="mt-4 pt-3 flex items-center justify-between text-xs text-outline">
                  <span className="font-medium">Showing 1 to 6 of 42 records</span>
                  <div className="flex items-center gap-1">
                    <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-on-surface disabled:opacity-40" disabled><MsIcon name="chevron_left" className="text-[16px]" /></button>
                    <button className="px-2.5 py-1 rounded-lg bg-primary text-on-primary font-bold text-[11px]">1</button>
                    <button className="px-2.5 py-1 rounded-lg bg-surface hover:bg-surface-container text-on-surface text-[11px]">2</button>
                    <button className="px-2.5 py-1 rounded-lg bg-surface hover:bg-surface-container text-on-surface text-[11px]">3</button>
                    <span className="px-1 text-outline">...</span>
                    <button className="px-2.5 py-1 rounded-lg bg-surface hover:bg-surface-container text-on-surface text-[11px]">7</button>
                    <button className="p-1 rounded-lg bg-surface hover:bg-surface-container text-on-surface"><MsIcon name="chevron_right" className="text-[16px]" /></button>
                  </div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-2xl p-5 shadow-sm">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
<MsIcon name="pie_chart" className="text-[18px] text-primary" />
                    <h3 className="font-headline font-semibold text-sm text-on-surface">Dataset Composition by Source Pipeline</h3>
                  </div>
                  <span className="text-[11px] font-mono text-outline">SHA-256 Merkle Ledger</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                  <div className="flex items-center justify-center p-2">
                    <div className="relative w-32 h-32 flex items-center justify-center">
                      <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                        <path className="text-surface-container-high" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth={4.5}></path>
                        <path className="text-primary" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeDasharray="60, 100" strokeLinecap="round" strokeWidth={4.5}></path>
                        <path className="text-tertiary" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeDasharray="25, 100" strokeDashoffset="-60" strokeLinecap="round" strokeWidth={4.5}></path>
                        <path className="text-tsc" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeDasharray="15, 100" strokeDashoffset="-85" strokeLinecap="round" strokeWidth={4.5}></path>
                      </svg>
                      <div className="absolute flex flex-col items-center justify-center text-center">
                        <span className="font-headline font-bold text-lg text-on-surface">3.48M</span>
                        <span className="text-[9px] uppercase tracking-wider text-outline font-bold">Rows Stored</span>
                      </div>
                    </div>
                  </div>
                  <div className="md:col-span-2 space-y-2 text-xs">
                    <div className="flex items-center justify-between p-2 rounded-xl bg-surface">
                      <div className="flex items-center gap-2">
                        <span className="w-3 h-3 rounded bg-primary"></span>
                        <span className="font-medium text-on-surface">Chat &amp; Multi-turn Reasoning</span>
                      </div>
                      <div className="text-right">
                        <span className="font-mono font-bold text-on-surface">2,088,000</span>
                        <span className="text-[10px] text-outline ml-1">(60%)</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between p-2 rounded-xl bg-surface">
                      <div className="flex items-center gap-2">
                        <span className="w-3 h-3 rounded bg-tertiary"></span>
                        <span className="font-medium text-on-surface">Risk Circuit &amp; Execution Anomalies</span>
                      </div>
                      <div className="text-right">
                        <span className="font-mono font-bold text-on-surface">870,000</span>
                        <span className="text-[10px] text-outline ml-1">(25%)</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between p-2 rounded-xl bg-surface">
                      <div className="flex items-center gap-2">
                        <span className="w-3 h-3 rounded bg-tsc"></span>
                        <span className="font-medium text-on-surface">Predictive Risk &amp; Custom SQL Data</span>
                      </div>
                      <div className="text-right">
                        <span className="font-mono font-bold text-on-surface">522,000</span>
                        <span className="text-[10px] text-outline ml-1">(15%)</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="xl:col-span-5 bg-surface-container-low rounded-2xl p-6 shadow-md transition-all" id="export-builder-sheet">
              <div className="flex items-start justify-between pb-4">
                <div>
                  <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[10px] font-bold uppercase tracking-wider mb-2">
<MsIcon name="bolt" className="text-[13px]" />
                    Interactive Builder
                  </div>
                  <h2 className="font-headline font-bold text-xl text-on-surface">New Training Dataset Export</h2>
                  <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">                    Curate domain-specific samples, define token boundaries, and verify regulatory anonymization.</p>
                </div>
                <button className="p-1 rounded-xl bg-surface-container hover:bg-surface-container-high text-outline transition-colors" title="Minimize / Close" type="button"><MsIcon name="close" className="text-[18px]" /></button>
              </div>
              <div className="space-y-5 pt-2">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-xs font-bold text-on-surface uppercase tracking-wider">1. Source Pipeline</label>
                    <span className="text-[10px] text-primary font-bold">5 Sources Available</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <label className="flex items-center gap-2.5 p-3 rounded-xl bg-primary text-on-primary cursor-pointer shadow-sm">
<input defaultChecked className="accent-on-primary" name="source_stream" type="radio" />
                      <div className="leading-tight">
                        <div className="font-semibold text-xs">Chat &amp; Reasoning</div>
                        <div className="text-[10px] text-on-primary-container">Desk conversational audit</div>
                      </div>
                    </label>
                    <label className="flex items-center gap-2.5 p-3 rounded-xl bg-surface hover:bg-surface-container cursor-pointer transition-colors">
<input className="accent-primary" name="source_stream" type="radio" />
                      <div className="leading-tight">
                        <div className="font-semibold text-xs text-on-surface">AI Insights</div>
                        <div className="text-[10px] text-outline">Synthesized recommendations</div>
                      </div>
                    </label>
                    <label className="flex items-center gap-2.5 p-3 rounded-xl bg-surface hover:bg-surface-container cursor-pointer transition-colors">
<input className="accent-primary" name="source_stream" type="radio" />
                      <div className="leading-tight">
                        <div className="font-semibold text-xs text-on-surface">Risk Anomalies</div>
                        <div className="text-[10px] text-outline">Breach triggers &amp; limits</div>
                      </div>
                    </label>
                    <label className="flex items-center gap-2.5 p-3 rounded-xl bg-surface hover:bg-surface-container cursor-pointer transition-colors">
<input className="accent-primary" name="source_stream" type="radio" />
                      <div className="leading-tight">
                        <div className="font-semibold text-xs text-on-surface">Predictive Analytics</div>
                        <div className="text-[10px] text-outline">Drawdown models</div>
                      </div>
                    </label>
                  </div>
                </div>
                <div>
                  <label className="text-xs font-bold text-on-surface uppercase tracking-wider block mb-2">2. Sampling Window</label>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-surface rounded-xl p-2.5 flex items-center justify-between">
                      <div>
                        <span className="text-[10px] font-bold uppercase text-outline block">Start Date</span>
                        <span className="font-mono text-xs font-semibold text-on-surface">2025-04-01</span>
                      </div>
<MsIcon name="calendar_today" className="text-[16px] text-outline" />
                    </div>
                    <div className="bg-surface rounded-xl p-2.5 flex items-center justify-between">
                      <div>
                        <span className="text-[10px] font-bold uppercase text-outline block">End Date</span>
                        <span className="font-mono text-xs font-semibold text-on-surface">2025-05-18</span>
                      </div>
<MsIcon name="event_available" className="text-[16px] text-outline" />
                    </div>
                  </div>
                  <div className="flex items-center justify-between mt-1 px-1">
                    <span className="text-[10px] text-outline font-medium">Selected duration: 47 calendar days</span>
                    <span className="text-[10px] text-primary font-bold cursor-pointer hover:underline">Quick: Last 30d</span>
                  </div>
                </div>
                <div className="p-3.5 rounded-xl bg-surface space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5">
<MsIcon name="tune" className="text-[15px] text-primary" />
                      3. Curated Parameters
                    </span>
                    <span className="text-[10px] font-mono text-primary font-bold">Domain: Proprietary Trading</span>
                  </div>
                  <div>
                    <div className="flex justify-between text-xs mb-1">
                      <span className="text-on-surface-variant font-medium">Minimum Token Sequence:</span>
                      <span className="font-mono font-bold text-primary">120 tokens</span>
                    </div>
<input className="w-full h-1.5 bg-surface-container-high rounded-lg appearance-none cursor-pointer accent-primary" max={500} min={30} type="range" defaultValue="120" />
                    <div className="flex justify-between text-[10px] text-outline mt-0.5">
                      <span>30 tokens (Short queries)</span>
                      <span>500 tokens (Deep reasoning)</span>
                    </div>
                  </div>
                  <div className="flex items-center justify-between pt-1">
                    <div className="flex flex-col">
                      <span className="text-xs font-semibold text-on-surface">Exclude Flagged / Toxic Conversations</span>
                      <span className="text-[10px] text-outline">Drops desk queries flagged by compliance ML</span>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
<input defaultChecked className="sr-only peer" type="checkbox" />
                      <div className="w-9 h-5 bg-surface-container-high peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-primary"></div>
                    </label>
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-outline uppercase block mb-1">Trader Tier Scope</label>
                    <select className="w-full bg-surface-container text-xs font-medium text-on-surface rounded-xl px-3 py-2 outline-none cursor-pointer" defaultValue="Funded & Master Traders Only (Level 3+)">
                      <option>Funded &amp; Master Traders Only (Level 3+)</option>
                      <option>All Evaluated Accounts</option>
                      <option>Risk Committee Members &amp; CROs</option>
                    </select>
                  </div>
                  <div className="flex items-center justify-between pt-1">
                    <span className="text-xs font-medium text-on-surface-variant">Min. Supervision Score:</span>
                    <span className="px-2 py-0.5 rounded-md bg-tertiary-fixed text-on-tertiary-fixed text-xs font-bold">★ 4.0 &amp; above</span>
                  </div>
                </div>
                <div>
                  <label className="text-xs font-bold text-on-surface uppercase tracking-wider block mb-2">4. Format &amp; Model Alignment</label>
                  <div className="grid grid-cols-1 gap-2.5">
                    <div className="bg-surface rounded-xl p-3 flex items-center justify-between">
                      <div className="space-y-0.5">
                        <div className="text-xs font-bold text-on-surface">JSONL Standard</div>
                        <div className="text-[10px] text-outline">OpenAI Fine-Tuning &amp; HuggingFace Alignment</div>
                      </div>
                      <span className="text-xs font-mono font-bold text-primary px-2 py-1 rounded bg-primary-fixed">Selected</span>
                    </div>
                    <div className="bg-surface rounded-xl p-3 flex items-center justify-between">
                      <div className="space-y-0.5">
                        <div className="text-xs font-bold text-on-surface">Tokenizer Instruction Template</div>
                        <div className="text-[10px] text-outline">Llama 3.1 &amp; Mistral Large Prompt Wrapping</div>
                      </div>
<MsIcon name="schema" className="text-[16px] text-outline" />
                    </div>
                  </div>
                </div>
                <div className="p-3.5 rounded-xl bg-surface-container space-y-3">
                  <div className="flex items-center gap-1.5">
<MsIcon name="security" className="text-[16px] text-primary" />
                    <span className="text-xs font-bold text-on-surface uppercase tracking-wider">5. Compliance &amp; Anonymization</span>
                  </div>
                  <div className="flex items-start justify-between gap-3">
                    <div className="space-y-0.5">
                      <div className="text-xs font-semibold text-on-surface">Cryptographic PII Redaction</div>
                      <p className="text-[10px] text-on-surface-variant leading-tight">                        Salts &amp; obscures trader email, broker auth tokens, IP addresses, and bank accounts.</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer shrink-0 mt-0.5">
<input defaultChecked className="sr-only peer" type="checkbox" />
                      <div className="w-9 h-5 bg-surface-container-high rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-primary"></div>
                    </label>
                  </div>
                  <div className="flex items-start justify-between gap-3">
                    <div className="space-y-0.5">
                      <div className="text-xs font-semibold text-on-surface">SEC 17a-4 WORM Mirror</div>
                      <p className="text-[10px] text-on-surface-variant leading-tight">                        Writes immutable cryptographic snapshot to AWS S3 Glacier Vault with Write-Once-Read-Many locks.</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer shrink-0 mt-0.5">
<input defaultChecked className="sr-only peer" type="checkbox" />
                      <div className="w-9 h-5 bg-surface-container-high rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-primary"></div>
                    </label>
                  </div>
                </div>
                <div className="p-3.5 rounded-xl bg-surface flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-primary-fixed flex items-center justify-center text-primary"><MsIcon name="analytics" className="text-[18px]" /></div>
                    <div>
                      <span className="text-[10px] font-bold uppercase text-outline block">Pre-computed Volume</span>
                      <span className="text-xs font-bold text-on-surface font-mono">~385,000 rows</span>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] font-bold uppercase text-outline block">Est. Footprint</span>
                    <span className="text-xs font-semibold text-primary font-mono">~460 MB JSONL</span>
                  </div>
                </div>
              </div>
              <div className="pt-5 mt-4 flex flex-col gap-2">
                <button className="w-full py-3 rounded-xl bg-primary hover:opacity-95 text-on-primary text-xs font-bold tracking-wide flex items-center justify-center gap-2 shadow-md transition-all active:scale-[0.99]" id="trigger-export-btn" type="button">
<MsIcon name="rocket_launch" className="text-[18px]" />
                  <span>Build Export (385k rows)</span>
                </button>
                <div className="grid grid-cols-2 gap-2">
                  <button className="py-2.5 rounded-xl bg-surface hover:bg-surface-container text-on-surface text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors" type="button">
<MsIcon name="science" className="text-[15px] text-outline" />
                    <span>Dry Run (10 rows)</span>
                  </button>
                  <button className="py-2.5 rounded-xl bg-surface hover:bg-surface-container text-outline text-xs font-semibold flex items-center justify-center transition-colors" type="button">                    Cancel</button>
                </div>
              </div>
            </div>
          </div>
          <div className="p-4 rounded-2xl bg-surface-container-low shadow-sm flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-primary-fixed flex items-center justify-center text-primary shrink-0"><MsIcon name="policy" className="text-[20px]" /></div>
              <div className="text-xs text-on-surface-variant">
                <span className="font-bold text-on-surface">SEC Rule 17a-4, FINRA Rule 4511 &amp; SOX 404 Data Provenance:</span>
                All training exports are hashed using SHA-256 and committed to immutable WORM storage with 7-year audit retention.
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3 shrink-0 font-mono text-[11px]">
              <div className="px-2.5 py-1 rounded-lg bg-surface text-outline">

<span>Merkle Root:</span> <span className="font-bold text-on-surface">0x8a91f...41e2</span>

              </div>
              <div className="px-2.5 py-1 rounded-lg bg-surface text-outline">

<span>Cluster Node:</span> <span className="font-bold text-primary">LDN-AI-EXPORT-01</span>

              </div>
              <span className="px-2 py-0.5 rounded bg-primary-fixed text-on-primary-fixed-variant font-bold text-[10px] tracking-wider uppercase">                Audit Ready</span>
            </div>
          </div>
        </div>
      </div>
      {so0 && (
        <div className="relative w-full max-w-[620px] rounded-2xl bg-surface-container-lowest shadow-2xl p-7 flex flex-col gap-5 text-on-surface transform transition-all animate-[fadeIn_0.2s_ease-out]">
            <div className="flex items-center justify-between">
              <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#f8e5dc] text-error font-bold text-[11px] tracking-wider uppercase">
<MsIcon name="warning" className="text-[15px]" />
                <span>{"Export Governance // Pipeline Interruption"}</span>
              </div>
              <span className="text-[11px] font-mono font-semibold text-tsc">FINRA REF #409-SEC</span>
            </div>
            <div className="flex flex-col gap-1.5">
              <h2 className="font-headline text-2xl font-bold text-on-surface tracking-tight leading-snug">                Cancel Active Dataset Export #EXP-90422?</h2>
              <p className="text-xs leading-relaxed text-on-surface-variant">
                <strong className="text-error font-semibold">Warning:</strong>
                Cancelling this running export pipeline will immediately abort worker execution across LD4 ClickHouse shards, discard in-progress Parquet partitions, and invalidate partial token serialization.
              </p>
            </div>
            <div className="rounded-xl bg-surface-container-low p-4 flex flex-col gap-3.5">
              <div className="flex items-start justify-between">
                <div className="flex flex-col">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-tsc">Export Target</span>
                  <span className="text-xs font-bold text-on-surface mt-0.5">Chat &amp; Multi-turn Reasoning Dataset (v2.8)</span>
                </div>
                <div className="text-right flex flex-col">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-tsc">Elapsed / Cluster</span>
                  <span className="text-xs font-mono font-semibold text-on-surface mt-0.5">04m 18s • 6 Nodes</span>
                </div>
              </div>
              <div className="flex flex-col gap-1.5">
                <div className="flex items-center justify-between text-[11px]">
                  <span className="font-medium text-on-surface flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-tertiary-container animate-pulse"></span>
                    Step 3 of 5: Cryptographic PII Salt &amp; Tokenization
                  </span>
                  <span className="font-mono font-bold text-on-surface">68%</span>
                </div>
                <div className="w-full h-2 rounded-full bg-surface-container-high overflow-hidden">                  <div className="h-full bg-primary rounded-full transition-all" style={{ width: '68%' }}></div></div>
                <div className="flex justify-between text-[10px] text-on-surface-variant font-mono">
                  <span>261,800 rows processed</span>
                  <span>Target: 385,000 rows</span>
                </div>
              </div>
              <div className="p-3 rounded-lg bg-surface-container flex items-start gap-2.5">
<MsIcon name="inventory_2" className="text-[16px] text-tertiary mt-0.5 shrink-0" />
                <p className="text-[11px] leading-relaxed text-on-surface-variant">
                  Partial export files in S3 staging bucket (
                  <code className="text-[10px] font-mono font-semibold text-on-surface">{"s3://terradesk-ai-exports/staged/exp-90422-part*"}</code>
                  ) will be safely quarantined and pruned per SEC 17a-4 zero-leak protocol.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <label className="text-[11px] font-bold uppercase tracking-wider text-tsc">Disposal Protocol &amp; Worker Handling</label>
              <div className="grid grid-cols-1 gap-2">
                <label className="relative flex items-start gap-3 p-3 rounded-xl bg-surface-container cursor-pointer hover:bg-surface-container-high transition-colors">
<input defaultChecked className="mt-0.5 accent-primary h-4 w-4 shrink-0" name="disposal-strategy" type="radio" />
                  <div className="flex flex-col">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-on-surface">Abort Job &amp; Prune Staging Artifacts</span>
                      <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-primary-fixed text-on-primary-fixed">Recommended</span>
                    </div>
                    <p className="text-[11px] text-on-surface-variant mt-0.5 leading-snug">                      Immediately stops workers, removes partial staging chunks, and logs the cancellation event to immutable disk without queue disruption.</p>
                  </div>
                </label>
                <label className="relative flex items-start gap-3 p-3 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
<input className="mt-0.5 accent-primary h-4 w-4 shrink-0" name="disposal-strategy" type="radio" />
                  <div className="flex flex-col">
                    <span className="text-xs font-bold text-on-surface">Terminate Worker Pods &amp; Purge Entire Queue</span>
                    <p className="text-[11px] text-on-surface-variant mt-0.5 leading-snug">                      Evacuates all pending exports in queue and resets batch worker slots across all LD4 ClickHouse partitions.</p>
                  </div>
                </label>
              </div>
            </div>
            <div className="flex flex-col gap-2.5">
              <div className="flex items-center justify-between">
                <label className="text-[11px] font-bold uppercase tracking-wider text-tsc flex items-center gap-1.5">
                  <span>Mandatory Operational Justification</span>
                  <span className="text-[10px] text-error font-bold">• WORM REQ</span>
                </label>
                <span className="text-[10px] text-on-surface-variant">Classified SEC 17a-4 Entry</span>
              </div>
              <select className="w-full px-3 py-2 bg-surface-container rounded-lg text-xs font-medium text-on-surface focus:outline-none focus:bg-surface-container-high transition-all" defaultValue="Data Pipeline Filter Reconfiguration / Token Limit Adjustment">
                <option>Data Pipeline Filter Reconfiguration / Token Limit Adjustment</option>
                <option>Upstream Data Contamination / Incorrect Time Horizon</option>
                <option>Compute Allocation Throttling / Emergency Resource Reclaim</option>
                <option>Model Training Hyperparameter Revision (Offline Target Changed)</option>
              </select>
<textarea className="w-full p-2.5 bg-surface-container rounded-lg text-xs font-normal text-on-surface focus:outline-none focus:bg-surface-container-high transition-all resize-none leading-relaxed" rows={2} defaultValue="Cancelling to adjust minimum token sequence length from 120 to 250 tokens and include Tier-2 trader challenge transcripts per Q2 model adaptation specs." />
              <label className="flex items-start gap-2.5 mt-1 cursor-pointer select-none">
<input defaultChecked className="mt-0.5 accent-primary rounded h-4 w-4 shrink-0" type="checkbox" />
                <span className="text-[11px] leading-snug text-on-surface-variant font-medium">
                  <strong className="text-on-surface font-semibold">Operator Attestation:</strong>
                  I confirm I hold Level-4 ML Data Governance authority and understand this cancellation is cryptographically recorded in the immutable WORM ledger.
                </span>
              </label>
            </div>
            <div className="pt-3 border-t-0 flex flex-col sm:flex-row items-center justify-between gap-4 mt-1">
              <div className="flex items-center gap-2 text-[11px] text-on-surface-variant">
                <span className="w-2 h-2 rounded-full bg-primary shrink-0"></span>
                <span className="truncate">Marcus Vance • CRO / Ops Principal (LD4)</span>
              </div>
              <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
                <button className="px-4 py-2.5 rounded-xl text-xs font-bold text-on-surface hover:bg-surface-container transition-all" type="button" onClick={() => setSo0(false)}>                  Keep Export Running</button>
                <button className="px-5 py-2.5 rounded-xl text-xs font-bold text-white bg-error hover:bg-[#a32a28] shadow-sm flex items-center gap-1.5 transition-all" type="button" onClick={() => setSo0(false)}>
<MsIcon name="stop_circle" className="text-[16px]" />
                  <span>Confirm &amp; Abort Export Job</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        </>
      )}
      {so1 && (        <aside className="fixed top-0 right-0 h-screen w-full sm:w-[680px] bg-surface-container-lowest z-50 flex flex-col shadow-2xl overflow-hidden transition-transform duration-300 ease-out">
          <div className="relative bg-surface-container-low px-7 pt-6 pb-5 flex-shrink-0">
            <div className="flex items-center justify-between gap-2 mb-3">
              <div className="flex flex-wrap items-center gap-2">
                <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold tracking-wide uppercase bg-primary-container/30 text-on-primary-fixed-variant">
<MsIcon name="gavel" className="text-[13px]" />
                  SEC 17a-4 Compliant Dataset
                </span>
                <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold tracking-wide uppercase bg-secondary-container text-on-secondary-container">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                  Ready &amp; Sealed
                </span>
                <span className="inline-flex items-center px-2 py-1 rounded-md text-[10px] font-mono font-semibold bg-surface-container-high text-on-surface-variant">                  JSONL + Parquet</span>
              </div>
              <button className="w-8 h-8 rounded-full bg-surface-container hover:bg-surface-container-high text-on-surface-variant hover:text-on-surface flex items-center justify-center transition-colors" title="Close sheet" onClick={() => setSo1(false)}><MsIcon name="close" className="text-[18px]" /></button>
            </div>
            <div className="pr-6">
              <h2 className="font-headline text-2xl font-bold text-on-surface tracking-tight leading-snug">
                Dataset Export Detail —
                <span className="font-mono text-primary font-semibold">#EXP-90412</span>
              </h2>
              <p className="text-xs text-on-surface-variant mt-1.5 leading-relaxed font-body">                Curated domain-specific reasoning samples from desk conversational audit logs with cryptographic PII redaction and WORM mirror.</p>
            </div>
            <div className="mt-4 flex flex-wrap items-center gap-2 pt-3">
              <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface hover:bg-surface-container-high text-xs font-semibold shadow-sm transition-all" onClick={() => setSo1(false)}>
<MsIcon name="download" className="text-[15px] text-primary" />
                Download Dataset (.tar.gz)
              </button>
              <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface hover:bg-surface-container-high text-xs font-semibold shadow-sm transition-all" onClick={() => setSo1(false)}>
<MsIcon name="description" className="text-[15px] text-tertiary" />
                Export Manifest (.json)
              </button>
              <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface hover:bg-surface-container-high text-xs font-mono font-medium shadow-sm transition-all" id="copyHashBtn" onClick={() => setSo1(false)}>
<MsIcon name="content_copy" className="text-[15px] text-tsc" />
                Copy SHA-256 Hash
              </button>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto px-7 py-6 space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="bg-surface-container rounded-xl p-3.5 flex flex-col justify-between shadow-sm">
                <div className="flex items-center justify-between text-on-surface-variant">
                  <span className="text-[11px] font-bold uppercase tracking-wider">Total Rows</span>
<MsIcon name="dataset" className="text-[16px] text-primary" />
                </div>
                <div className="mt-2">
                  <div className="text-xl font-headline font-bold text-on-surface leading-tight">385,000</div>
                  <div className="text-[10px] text-on-surface-variant font-medium mt-0.5">~1.12B Tokens · 100% Validated</div>
                </div>
              </div>
              <div className="bg-surface-container rounded-xl p-3.5 flex flex-col justify-between shadow-sm">
                <div className="flex items-center justify-between text-on-surface-variant">
                  <span className="text-[11px] font-bold uppercase tracking-wider">Uncompressed Size</span>
<MsIcon name="folder_zip" className="text-[16px] text-tertiary" />
                </div>
                <div className="mt-2">
                  <div className="text-xl font-headline font-bold text-on-surface leading-tight">460.4 MB</div>
                  <div className="text-[10px] text-on-surface-variant font-medium mt-0.5">148.2 MB Snappy Parquet</div>
                </div>
              </div>
              <div className="bg-surface-container rounded-xl p-3.5 flex flex-col justify-between shadow-sm">
                <div className="flex items-center justify-between text-on-surface-variant">
                  <span className="text-[11px] font-bold uppercase tracking-wider">Sampling Range</span>
<MsIcon name="date_range" className="text-[16px] text-tsc" />
                </div>
                <div className="mt-2">
                  <div className="text-xs font-mono font-bold text-on-surface leading-tight">2025-04-01 → 05-18</div>
                  <div className="text-[10px] text-on-surface-variant font-medium mt-0.5">47 calendar days elapsed</div>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-1.5 p-1 bg-surface-container-high rounded-xl overflow-x-auto text-xs font-semibold">
              <button className="tab-btn px-3 py-2 rounded-lg bg-surface text-on-surface shadow-sm transition-all whitespace-nowrap flex items-center gap-1.5" id="tabBtn1">
<MsIcon name="tune" className="text-[15px] text-primary" />
                1. Overview &amp; Pipeline Config
              </button>
              <button className="tab-btn px-3 py-2 rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface/50 transition-all whitespace-nowrap flex items-center gap-1.5" id="tabBtn2">
<MsIcon name="verified_user" className="text-[15px]" />
                2. PII &amp; Anonymization Audit
              </button>
              <button className="tab-btn px-3 py-2 rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface/50 transition-all whitespace-nowrap flex items-center gap-1.5" id="tabBtn3">
<MsIcon name="code_blocks" className="text-[15px]" />
                3. Tokenizer &amp; Format
              </button>
              <button className="tab-btn px-3 py-2 rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface/50 transition-all whitespace-nowrap flex items-center gap-1.5" id="tabBtn4">
<MsIcon name="enhanced_encryption" className="text-[15px]" />
                4. Cryptographic Proof
              </button>
            </div>
            <div className="tab-pane space-y-6" id="tabContent1">
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <div className="flex items-center justify-between pb-3 bg-gradient-to-r from-transparent via-surface-container-highest/20 to-transparent">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-bold text-xs">1</span>
                    <h3 className="font-headline font-semibold text-sm text-on-surface">Source Pipeline &amp; Sampling Criteria</h3>
                  </div>
                  <span className="text-[11px] font-mono text-primary font-semibold">FILTER_PASS_RATE: 98.4%</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="p-3 rounded-lg bg-surface flex flex-col gap-1 shadow-sm">
                    <span className="text-on-surface-variant font-medium text-[11px]">Primary Source Stream</span>
                    <span className="text-on-surface font-semibold flex items-center gap-1.5">
<MsIcon name="chat" className="text-[16px] text-tertiary" />
                      Chat &amp; Multi-turn Reasoning Logs
                    </span>
                    <span className="text-[10px] text-on-surface-variant">Synthesized from LD4 low-latency desk threads</span>
                  </div>
                  <div className="p-3 rounded-lg bg-surface flex flex-col gap-1 shadow-sm">
                    <span className="text-on-surface-variant font-medium text-[11px]">Trader Tier Scope</span>
                    <span className="text-on-surface font-semibold flex items-center gap-1.5">
<MsIcon name="workspace_premium" className="text-[16px] text-primary" />
                      Funded &amp; Master Desk (Level 3+)
                    </span>
                    <span className="text-[10px] text-on-surface-variant">Excluded trainee, sandbox, and retail test profiles</span>
                  </div>
                  <div className="p-3 rounded-lg bg-surface flex flex-col gap-1 shadow-sm">
                    <span className="text-on-surface-variant font-medium text-[11px]">Minimum Token Sequence</span>
                    <div className="flex items-baseline gap-2">
                      <span className="text-on-surface font-mono font-bold text-sm">120 tokens</span>
                      <span className="text-[11px] text-on-surface-variant">(Mean: 342 tokens/row)</span>
                    </div>
                    <span className="text-[10px] text-on-surface-variant">Cutoff eliminates uninformative monosyllabic pings</span>
                  </div>
                  <div className="p-3 rounded-lg bg-surface flex flex-col gap-1 shadow-sm">
                    <span className="text-on-surface-variant font-medium text-[11px]">Quality Supervision Score</span>
                    <div className="flex items-baseline gap-2">
                      <span className="text-on-surface font-mono font-bold text-sm">Score ≥ 4.0 / 5.0</span>
                      <span className="text-[11px] text-primary font-medium">98.4% Passed</span>
                    </div>
                    <span className="text-[10px] text-on-surface-variant">Evaluated by Llama-3-70B Critic Evaluator</span>
                  </div>
                </div>
                <div className="p-4 rounded-lg bg-surface space-y-2 shadow-sm">
                  <div className="flex items-center justify-between text-[11px]">
                    <span className="font-semibold text-on-surface">Toxicity, Risk &amp; Compliance Filtering Funnel</span>
                    <span className="font-mono text-error font-medium">1,420 non-compliant threads discarded</span>
                  </div>
                  <div className="w-full h-3 bg-surface-container-high rounded-full overflow-hidden flex">
                    <div className="h-full bg-primary" style={{ width: '96.3%' }} title="Clean Domain Reasoning (96.3%)"></div>
                    <div className="h-full bg-tertiary-container" style={{ width: '2.1%' }} title="Borderline Low Information (2.1%)"></div>
                    <div className="h-full bg-error" style={{ width: '1.6%' }} title="Redacted Toxic / Compliance Flags (1.6%)"></div>
                  </div>
                  <div className="flex items-center justify-between text-[10px] text-on-surface-variant pt-1 font-mono">
                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-primary"></span> 385,000 Certified Rows (96.3%)</span>
                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-tertiary-container"></span> Filtered Context</span>
                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-error"></span> 1,420 Quarantined (1.6%)</span>
                  </div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <div className="flex items-center justify-between pb-3 bg-gradient-to-r from-transparent via-surface-container-highest/20 to-transparent">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-bold text-xs">2</span>
                    <h3 className="font-headline font-semibold text-sm text-on-surface">PII Redaction &amp; Regulatory Compliance Audit</h3>
                  </div>
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-primary-container/40 text-on-primary-fixed-variant">10,000 / 10,000 PROBES PASSED</span>
                </div>
                <div className="p-4 rounded-xl bg-surface flex items-start gap-4 shadow-sm">
                  <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center flex-shrink-0"><MsIcon name="policy" className="text-on-primary text-[22px]" /></div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <h4 className="text-xs font-bold text-on-surface uppercase tracking-wide">Synthetic Adversarial Probe Verdict</h4>
                      <span className="font-mono text-xs font-bold text-primary">0 LEAKS DETECTED</span>
                    </div>
                    <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">                      Zero instances of unmasked credentials, phone numbers, individual trader names, or internal settlement IBANs survived the dual-pass NER &amp; regex masking engine.</p>
                  </div>
                </div>
                <div className="space-y-2 text-xs">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-tsc">Salting &amp; Obfuscation Registry</span>
                  <div className="space-y-1.5">
                    <div className="p-2.5 rounded-lg bg-surface flex items-center justify-between font-mono text-[11px]">
                      <div className="flex items-center gap-2 text-on-surface">
<MsIcon name="fingerprint" className="text-[15px] text-primary" />
                        <span>Trader Emails &amp; Handles</span>
                      </div>
                      <span className="text-on-surface-variant">SHA-256 HMAC (Key: #HSM-KMS-771)</span>
                      <span className="text-primary font-bold">100% Masked</span>
                    </div>
                    <div className="p-2.5 rounded-lg bg-surface flex items-center justify-between font-mono text-[11px]">
                      <div className="flex items-center gap-2 text-on-surface">
<MsIcon name="router" className="text-[15px] text-primary" />
                        <span>Broker Auth Tokens &amp; IP Addresses</span>
                      </div>
                      <span className="text-on-surface-variant">Class-C / CIDR Zero-fill + Nonce</span>
                      <span className="text-primary font-bold">100% Masked</span>
                    </div>
                    <div className="p-2.5 rounded-lg bg-surface flex items-center justify-between font-mono text-[11px]">
                      <div className="flex items-center gap-2 text-on-surface">
<MsIcon name="account_balance_wallet" className="text-[15px] text-primary" />
                        <span>MT5 Account IDs &amp; Bank Routing</span>
                      </div>
                      <span className="text-on-surface-variant">Cryptographic Synthetic Tokens</span>
                      <span className="text-primary font-bold">100% Masked</span>
                    </div>
                  </div>
                </div>
                <div className="pt-2 flex flex-wrap gap-2">
                  <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface text-[11px] font-semibold">
<MsIcon name="check_circle" className="text-[14px] text-primary" />
                    SEC Rule 17a-4(f) Immutable Format
                  </div>
                  <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface text-[11px] font-semibold">
<MsIcon name="check_circle" className="text-[14px] text-primary" />
                    FINRA Rule 4511 Books &amp; Records
                  </div>
                  <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface text-on-surface text-[11px] font-semibold">
<MsIcon name="check_circle" className="text-[14px] text-primary" />
                    GDPR Art. 17(3)(b) Pseudonymization
                  </div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <div className="flex items-center justify-between pb-3 bg-gradient-to-r from-transparent via-surface-container-highest/20 to-transparent">
                  <div className="flex items-center gap-2">
                    <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center font-bold text-xs">3</span>
                    <h3 className="font-headline font-semibold text-sm text-on-surface">Storage &amp; WORM Optical Provenance</h3>
                  </div>
                  <span className="text-[11px] font-mono text-tertiary font-bold flex items-center gap-1">
<MsIcon name="lock" className="text-[14px]" />
                    WORM LOCKED (7 YEARS)
                  </span>
                </div>
                <div className="space-y-2.5">
                  <div>
                    <span className="text-[11px] font-bold uppercase tracking-wider text-tsc">Target S3 Glacier Vault URI</span>
                    <div className="mt-1 p-2.5 rounded-lg bg-surface font-mono text-xs text-on-surface flex items-center justify-between">
                      <span className="truncate">{"s3://terradesk-worm-vault/exports/2025/exp-90412.tar.gz"}</span>
                      <span className="text-[10px] text-primary font-bold px-2 py-0.5 rounded bg-primary-container/30">LOCK EXP: 2032-05-18</span>
                    </div>
                  </div>
                  <div>
                    <span className="text-[11px] font-bold uppercase tracking-wider text-tsc">Cryptographic Merkle Root Hash</span>
                    <div className="mt-1 p-2.5 rounded-lg bg-surface font-mono text-xs text-on-surface flex items-center justify-between">
                      <span className="truncate text-tsc">0x8a91f4b72e01a89c91e04cfbb4669fec39d4b94182f6e917d2a714c029194182</span>
                      <button className="text-primary hover:text-primary-fixed-variant text-xs flex items-center gap-1 ml-2"><MsIcon name="content_copy" className="text-[15px]" /></button>
                    </div>
                  </div>
                  <div className="p-3 rounded-lg bg-surface-container flex items-center justify-between text-xs">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-primary-container/40 flex items-center justify-center text-primary"><MsIcon name="verified" className="text-[18px]" /></div>
                      <div>
                        <span className="font-bold text-on-surface block">Marcus Vance (CRO / Ops Principal)</span>
                        <span className="text-[10px] font-mono text-on-surface-variant">Timestamp: 2025-05-18 14:14:02 UTC · HSM Key ID: 0x98FF-VNC</span>
                      </div>
                    </div>
                    <span className="px-2.5 py-1 rounded bg-surface font-mono text-[10px] font-bold text-on-surface shadow-sm">RSA-4096 SIGNED</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="tab-pane hidden space-y-4" id="tabContent2">
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <h3 className="font-headline font-semibold text-sm text-on-surface">Adversarial PII Audit Log (10,000 Iteration Pass)</h3>
                <p className="text-xs text-on-surface-variant leading-relaxed">                  The output dataset was bombarded with automated extraction prompts across 12 known threat vectors, including prompt injection, prefix extraction, and reconstruction attacks.</p>
                <div className="space-y-2 font-mono text-xs">
                  <div className="p-3 rounded-lg bg-surface flex items-center justify-between">
                    <div>
                      <span className="text-on-surface font-bold">Probe #001–2500: Prompt Injection Leaks</span>
                      <span className="text-[10px] block text-on-surface-variant">Tested for system prompt leaking and raw audit header retrieval</span>
                    </div>
                    <span className="text-primary font-bold">0 Leaks (Pass)</span>
                  </div>
                  <div className="p-3 rounded-lg bg-surface flex items-center justify-between">
                    <div>
                      <span className="text-on-surface font-bold">Probe #2501–5000: Regex Credit/IBAN Scans</span>
                      <span className="text-[10px] block text-on-surface-variant">Audited for Luhn-compliant credit strings &amp; SWIFT BIC structures</span>
                    </div>
                    <span className="text-primary font-bold">0 Leaks (Pass)</span>
                  </div>
                  <div className="p-3 rounded-lg bg-surface flex items-center justify-between">
                    <div>
                      <span className="text-on-surface font-bold">Probe #5001–10000: Trader Name Correlation</span>
                      <span className="text-[10px] block text-on-surface-variant">Cross-referenced against institutional HR &amp; desk active rosters</span>
                    </div>
                    <span className="text-primary font-bold">0 Leaks (Pass)</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="tab-pane hidden space-y-4" id="tabContent3">
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-3 font-mono text-xs">
                <h3 className="font-headline font-semibold text-sm text-on-surface">Dataset Specification &amp; Packaging</h3>
                <div className="p-3 rounded-lg bg-surface text-on-surface space-y-2">
                  <div className="flex justify-between border-b border-surface-container-highest/40 pb-2">
                    <span className="text-tsc font-medium">Encoding:</span>
                    <span>UTF-8 JSONL (Gzip compression lvl 9)</span>
                  </div>
                  <div className="flex justify-between border-b border-surface-container-highest/40 pb-2">
                    <span className="text-tsc font-medium">Alternative Layout:</span>
                    <span>Apache Parquet 2.0 (Snappy compressed, columnar)</span>
                  </div>
                  <div className="flex justify-between border-b border-surface-container-highest/40 pb-2">
                    <span className="text-tsc font-medium">Tokenizer Compatibility:</span>
                    <span>tiktoken (cl100k_base) &amp; Llama-3 BPE (128k vocab)</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-tsc font-medium">Format Hierarchy:</span>
                    <span>System / User / Reasoning_Chain / Desk_Action</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="tab-pane hidden space-y-4" id="tabContent4">
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-3">
                <h3 className="font-headline font-semibold text-sm text-on-surface">WORM Optical &amp; Hash Chain Verification</h3>
                <div className="p-3 rounded-lg bg-surface font-mono text-[11px] text-on-surface space-y-2">
                  <div className="text-on-surface-variant font-medium">Vault Storage Block:</div>
                  <div className="p-2 rounded bg-surface-container break-all">BLK-90412-20250518-141402-SHA256:7e8d6411ca73f9104b901a88c42b918f519c</div>
                  <div className="text-on-surface-variant font-medium pt-2">Optical WORM Certificate State:</div>
                  <div className="flex items-center gap-2 text-primary font-bold">
<MsIcon name="verified" className="text-[16px]" />
                    IMMUTABLE HARDWARE LOCK ENGAGED (Read-Only)
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-surface-container border-t-0 p-5 flex flex-col gap-3 flex-shrink-0 shadow-lg">
            <div className="flex items-center gap-2 text-[11px] text-on-surface-variant">
              <span className="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
              <span className="font-medium">WORM Storage Active · Merkle Root Verified · Tamper-evident lock engaged.</span>
            </div>
            <div className="flex items-center justify-between gap-3">
              <button className="px-4 py-2.5 rounded-xl bg-surface hover:bg-surface-container-high text-on-surface text-xs font-semibold shadow-sm transition-all flex items-center gap-2">
<MsIcon name="terminal" className="text-[16px]" />
                Inspect Sample Payload (JSON)
              </button>
              <button className="px-5 py-2.5 rounded-xl bg-primary hover:bg-primary-fixed-variant text-on-primary text-xs font-semibold shadow-md hover:shadow-lg transition-all flex items-center gap-2" onClick={() => setSo1(false)}>
<MsIcon name="download_for_offline" className="text-[18px]" />
                Download Certified Archive (.tar.gz) ↓
              </button>
            </div>
          </div>
        </aside>
        </>
      )}
    </>
  );
}
