"use client";

/**
 * Ad Spend — Stitch conversion (view-id: `marketing-ad-spend`)
 *
 * Source: stitch_screens/ad_spend
 * Spec: [EXISTING] · overlay states: 2/2 wired
 * States: ad_spend_ad_campaign_detail_configuration_sheet_state✓, ad_spend_delete_campaign_confirmation_alertdialog_state✓
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import * as React from "react";
import { MsIcon } from "@/components/stitch/stitch";

export function MarketingAdSpendStitchPage() {
  const [so0, setSo0] = React.useState(false);
  const [so1, setSo1] = React.useState(false);
  return (
    <>
      <div className="flex flex-col w-full space-y-8">
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 transform translate-y-20 opacity-0 pointer-events-none transition-all duration-300 ease-out flex items-center gap-3 px-5 py-3.5 rounded-xl bg-inverse-surface text-inverse-on-surface shadow-xl shadow-on-surface/10 text-xs font-semibold" id="toast-notification">
<MsIcon name="check_circle" className="text-primary-fixed-dim text-lg" />
          <span id="toast-message">Integration gateway opened. Syncing attribution telemetry...</span>
        </div>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-surface-container-high/60">
          <div className="flex items-center gap-2 text-xs tracking-wider uppercase font-semibold text-tsc">
            <span>Marketing &amp; Growth</span>
            <span className="text-outline-variant">/</span>
            <span>Acquisition</span>
            <span className="text-outline-variant">/</span>
            <span className="text-primary font-bold">Ad Spend</span>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant text-[11px] font-semibold">
              <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
              Multi-Touch Attribution Active
            </span>
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant text-[11px] font-semibold">
<MsIcon name="sync" className="text-[14px] text-tertiary" />
              Real-Time ROAS Reconciled
            </span>
            <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-secondary-container text-on-secondary-container text-[11px] font-bold">
<MsIcon name="verified_user" className="text-[14px]" />
              SEC &amp; FTC Rule Compliant
            </span>
          </div>
        </div>
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          <div className="flex items-start sm:items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-primary-fixed flex items-center justify-center text-on-primary-fixed shrink-0 shadow-sm"><MsIcon name="campaign" className="text-2xl" fill /></div>
            <div className="space-y-1">
              <div className="flex items-center gap-3">
                <h1 className="font-headline text-2xl sm:text-3xl font-bold tracking-tight text-on-surface">Ad Spend</h1>
                <span className="px-2 py-0.5 rounded text-[11px] font-bold uppercase tracking-wider bg-surface-container-high text-tsc">Institutional Ops</span>
              </div>
              <p className="text-xs sm:text-sm text-tsc max-w-3xl leading-relaxed">                Cross-platform paid acquisition performance across Google, Meta, TikTok, LinkedIn, and X with real-time CPA/ROAS attribution and full conversion funnel tracking to funded challenge traders.</p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 shrink-0">
            <button className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-surface-container-lowest text-primary text-xs font-bold hover:bg-surface-container-high transition-all shadow-sm active:scale-95 group">
<MsIcon name="add_circle" className="text-[18px] group-hover:rotate-90 transition-transform" />
              <span>+ Connect Ad Account</span>
            </button>
            <div className="text-[10px] text-tsc text-center sm:text-right hidden sm:block">
              <span className="font-semibold text-on-surface">Sync Interval:</span>
              60s live poll
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-tsc">Total Ad Spend (30d)</span>
              <span className="w-8 h-8 rounded-lg bg-surface-container flex items-center justify-center text-on-surface-variant"><MsIcon name="payments" className="text-base" /></span>
            </div>
            <div className="space-y-1">
              <div className="font-headline text-3xl font-bold text-on-surface tracking-tight">$142,850.00</div>
              <div className="text-xs text-tsc flex items-center gap-1.5 pt-1">
                <span className="inline-flex items-center text-primary font-bold text-[11px]">
<MsIcon name="trending_up" className="text-sm" />
                  84%
                </span>
                <span>of $170k monthly cap</span>
              </div>
            </div>
            <div className="w-full bg-surface-container-high rounded-full h-1.5 overflow-hidden">              <div className="bg-primary h-full rounded-full" style={{ width: '84%' }}></div></div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-tsc">Total Conversions</span>
              <span className="w-8 h-8 rounded-lg bg-surface-container flex items-center justify-center text-on-surface-variant"><MsIcon name="how_to_reg" className="text-base" /></span>
            </div>
            <div className="space-y-1">
              <div className="font-headline text-3xl font-bold text-on-surface tracking-tight">1,842 <span className="text-base font-body font-normal text-tsc">Traders</span></div>
              <div className="text-xs text-tsc flex items-center gap-1.5 pt-1">
                <span className="inline-flex items-center text-primary font-bold text-[11px] bg-primary-fixed/40 px-1.5 py-0.5 rounded">                  +22.4%</span>
                <span>vs previous period</span>
              </div>
            </div>
            <div className="text-[11px] text-tsc font-medium">              Funded evaluation &amp; instant prop tiers</div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-tsc">Blended CPA</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">                ≤ $100 Target</span>
            </div>
            <div className="space-y-1">
              <div className="font-headline text-3xl font-bold text-primary tracking-tight">$77.55</div>
              <div className="text-xs text-tsc flex items-center gap-1.5 pt-1">
<MsIcon name="check_circle" className="text-primary text-sm" />
                <span className="font-medium text-on-surface-variant">Efficient scaling zone</span>
              </div>
            </div>
            <div className="text-[11px] text-tsc flex justify-between items-center">
              <span>Historical Low: $64.10</span>
              <span className="text-primary font-bold">-$22.45 to cap</span>
            </div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-tsc">Aggregate ROAS</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-tertiary-fixed text-on-tertiary-fixed">                Target ≥ 2.0x</span>
            </div>
            <div className="space-y-1">
              <div className="font-headline text-3xl font-bold text-on-surface tracking-tight">3.85x</div>
              <div className="text-xs text-tsc flex items-center gap-1.5 pt-1">
                <span className="font-bold text-tertiary">$549,420</span>
                <span>Gross Challenge Revenue</span>
              </div>
            </div>
            <div className="text-[11px] text-tsc flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-primary"></span>
              <span>Net Ad Profit: <strong>+$406,570</strong></span>
            </div>
          </div>
        </div>
        <div className="p-4 rounded-xl bg-surface-container-low shadow-sm flex flex-wrap items-center justify-between gap-4">
          <div className="flex flex-wrap items-center gap-3">
            <div className="relative">
              <select className="appearance-none pl-3 pr-8 py-2 rounded-lg bg-surface-container-lowest text-xs font-semibold text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-xs cursor-pointer" id="filter-platform">
                <option value="all">All Platforms (5 Connected)</option>
                <option value="google">Google Search &amp; Display</option>
                <option value="meta">Meta (Instagram / FB)</option>
                <option value="tiktok">TikTok Ads</option>
                <option value="twitter">Twitter / X</option>
                <option value="linkedin">LinkedIn Ads</option>
              </select>
<MsIcon name="expand_more" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[18px] text-tsc pointer-events-none" />
            </div>
            <div className="relative">
              <select className="appearance-none pl-3 pr-8 py-2 rounded-lg bg-surface-container-lowest text-xs font-semibold text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-xs cursor-pointer" id="filter-campaign" onClick={() => setSo0(true)}>
                <option value="all">All Campaigns (24 Active)</option>
                <option value="funded">100k Challenge Scalper Surge</option>
                <option value="institutional">Institutional Pro Tier Q2</option>
                <option value="retargeting">Retargeting / Abandoned Cart</option>
                <option value="emea">EMEA Tier 1 FX Expansion</option>
              </select>
<MsIcon name="expand_more" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[18px] text-tsc pointer-events-none" />
            </div>
            <div className="flex items-center p-1 rounded-lg bg-surface-container">
              <button className="px-3 py-1 rounded text-xs font-medium text-tsc hover:text-on-surface transition-colors">7d</button>
              <button className="px-3 py-1 rounded text-xs font-bold bg-surface-container-lowest text-primary shadow-xs">30d</button>
              <button className="px-3 py-1 rounded text-xs font-medium text-tsc hover:text-on-surface transition-colors">90d</button>
            </div>
            <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container transition-all">
<MsIcon name="restart_alt" className="text-[16px]" />
              <span>Reset Filters</span>
            </button>
          </div>
          <div className="flex items-center gap-2">
            <button className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg bg-surface-container-lowest text-on-surface text-xs font-semibold hover:bg-surface-container-high transition-colors shadow-xs">
<MsIcon name="download" className="text-[16px] text-tsc" />
              <span>Export CSV</span>
            </button>
          </div>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-7 p-6 rounded-xl bg-surface-container-lowest shadow-sm flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-4">
                <div>
                  <h2 className="font-headline text-lg font-bold text-on-surface">Spend by Platform</h2>
                  <p className="text-xs text-tsc">Reconciled ad expenditure across active partner channels</p>
                </div>
                <span className="text-xs font-bold text-primary bg-primary-fixed/30 px-2.5 py-1 rounded-full">Active Pacing</span>
              </div>
              <div className="space-y-4 pt-2">
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-primary"></span>
                      <span className="font-semibold text-on-surface">Google Ads</span>
                      <span className="text-[10px] text-tsc bg-surface-container px-1.5 py-0.5 rounded">Search &amp; Performance Max</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">CTR: 4.12%</span>
                      <span className="font-mono font-bold text-on-surface">$58,400.00</span>
                    </div>
                  </div>
                  <div className="w-full bg-surface-container rounded-full h-2.5 overflow-hidden">                    <div className="bg-primary h-full rounded-full transition-all duration-700" style={{ width: '78%' }}></div></div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-primary-container"></span>
                      <span className="font-semibold text-on-surface">Meta (Instagram / FB)</span>
                      <span className="text-[10px] text-tsc bg-surface-container px-1.5 py-0.5 rounded">Story Reels &amp; Feeds</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">CTR: 3.48%</span>
                      <span className="font-mono font-bold text-on-surface">$41,200.00</span>
                    </div>
                  </div>
                  <div className="w-full bg-surface-container rounded-full h-2.5 overflow-hidden">                    <div className="bg-primary-container h-full rounded-full transition-all duration-700" style={{ width: '55%' }}></div></div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-tertiary"></span>
                      <span className="font-semibold text-on-surface">Twitter / X</span>
                      <span className="text-[10px] text-tsc bg-surface-container px-1.5 py-0.5 rounded">Finance &amp; Scalp Fintwit</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">CTR: 2.85%</span>
                      <span className="font-mono font-bold text-on-surface">$19,500.00</span>
                    </div>
                  </div>
                  <div className="w-full bg-surface-container rounded-full h-2.5 overflow-hidden">                    <div className="bg-tertiary h-full rounded-full transition-all duration-700" style={{ width: '26%' }}></div></div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-tertiary-container"></span>
                      <span className="font-semibold text-on-surface">TikTok Ads</span>
                      <span className="text-[10px] text-tsc bg-surface-container px-1.5 py-0.5 rounded">Short-form Video Spark</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">CTR: 5.21%</span>
                      <span className="font-mono font-bold text-on-surface">$14,250.00</span>
                    </div>
                  </div>
                  <div className="w-full bg-surface-container rounded-full h-2.5 overflow-hidden">                    <div className="bg-tertiary-container h-full rounded-full transition-all duration-700" style={{ width: '19%' }}></div></div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-tsc"></span>
                      <span className="font-semibold text-on-surface">LinkedIn Ads</span>
                      <span className="text-[10px] text-tsc bg-surface-container px-1.5 py-0.5 rounded">High-Net-Worth &amp; Quants</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">CTR: 1.62%</span>
                      <span className="font-mono font-bold text-on-surface">$9,500.00</span>
                    </div>
                  </div>
                  <div className="w-full bg-surface-container rounded-full h-2.5 overflow-hidden">                    <div className="bg-tsc h-full rounded-full transition-all duration-700" style={{ width: '12%' }}></div></div>
                </div>
              </div>
            </div>
            <div className="pt-6 mt-6 border-t border-surface-container-high/60 flex items-center justify-between text-xs text-tsc">
              <span>Average CPC: <strong className="text-on-surface">$0.78</strong></span>
              <span>Network Delivery Success: <strong className="text-primary font-bold">99.8%</strong></span>
            </div>
          </div>
          <div className="lg:col-span-5 p-6 rounded-xl bg-surface-container-lowest shadow-sm flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-3">
                <h2 className="font-headline text-lg font-bold text-on-surface">Spend Distribution</h2>
                <span className="text-xs text-tsc">Normalized %</span>
              </div>
              <div className="relative flex items-center justify-center my-4">
                <svg className="w-48 h-48 -rotate-90 transform" viewBox="0 0 100 100">
                  <circle className="text-surface-container" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeWidth={12}></circle>
                  <circle className="text-primary" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeDasharray="97.6 238.8" strokeDashoffset="0" strokeWidth={12}></circle>
                  <circle className="text-primary-container" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeDasharray="68.7 238.8" strokeDashoffset="-97.6" strokeWidth={12}></circle>
                  <circle className="text-tertiary" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeDasharray="32.7 238.8" strokeDashoffset="-166.3" strokeWidth={12}></circle>
                  <circle className="text-tertiary-container" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeDasharray="23.8 238.8" strokeDashoffset="-199" strokeWidth={12}></circle>
                  <circle className="text-tsc" cx={50} cy={50} fill="none" r={38} stroke="currentColor" strokeDasharray="15.7 238.8" strokeDashoffset="-222.8" strokeWidth={12}></circle>
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                  <span className="font-headline text-xl font-bold text-on-surface">$142.8k</span>
                  <span className="text-[10px] uppercase tracking-wider font-semibold text-tsc">Total Spend</span>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-2.5 pt-2 text-xs">
                <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-low">
                  <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-primary"></span>Google</span>
                  <span className="font-bold text-on-surface">40.9%</span>
                </div>
                <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-low">
                  <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-primary-container"></span>Meta</span>
                  <span className="font-bold text-on-surface">28.8%</span>
                </div>
                <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-low">
                  <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-tertiary"></span>Twitter/X</span>
                  <span className="font-bold text-on-surface">13.7%</span>
                </div>
                <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-low">
                  <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-tertiary-container"></span>TikTok</span>
                  <span className="font-bold text-on-surface">10.0%</span>
                </div>
                <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-low col-span-2">
                  <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-tsc"></span>LinkedIn</span>
                  <span className="font-bold text-on-surface">6.6%</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="p-6 rounded-xl bg-surface-container-lowest shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-headline text-lg font-bold text-on-surface">Return on Ad Spend (ROAS) by Network</h2>
                <div className="group relative inline-block">
<MsIcon name="help_outline" className="text-[16px] text-tsc cursor-help" />
                  <div className="absolute left-1/2 -translate-x-1/2 bottom-full mb-2 hidden group-hover:block w-72 p-2.5 bg-inverse-surface text-inverse-on-surface text-[11px] rounded-lg shadow-lg z-30 leading-relaxed font-normal">                    ROAS = Gross Challenge Evaluation Revenue / Platform Ad Spend. Target benchmark is ≥ 2.0x for profitable funded trader acquisition.</div>
                </div>
              </div>
              <p className="text-xs text-tsc">Capital return efficiency measured against audited prop challenge purchases</p>
            </div>
            <div className="flex items-center gap-4 text-xs font-semibold">
              <span className="flex items-center gap-1.5 text-tsc">
                <span className="w-3 h-0.5 bg-outline-variant inline-block"></span>
                Benchmark (2.0x)
              </span>
              <span className="flex items-center gap-1.5 text-primary">
                <span className="w-2 h-2 rounded-full bg-primary"></span>
                Top Performer
              </span>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            <div className="p-4 rounded-xl bg-surface-container-low flex flex-col justify-between space-y-3 relative overflow-hidden">
              <div className="absolute top-0 right-0 bg-primary px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-on-primary rounded-bl">                Viral Spike</div>
              <div className="text-xs font-semibold text-tsc">TikTok Ads</div>
              <div>
                <div className="font-headline text-3xl font-bold text-primary">4.82x</div>
                <div className="text-[11px] text-tsc">Revenue: $68.7k</div>
              </div>
              <div className="w-full bg-surface-container rounded-full h-2">                <div className="bg-primary h-full rounded-full" style={{ width: '96%' }}></div></div>
              <div className="text-[10px] text-primary font-bold">+141% over target</div>
            </div>
            <div className="p-4 rounded-xl bg-surface-container-low flex flex-col justify-between space-y-3">
              <div className="text-xs font-semibold text-tsc">Google Ads</div>
              <div>
                <div className="font-headline text-3xl font-bold text-on-surface">4.24x</div>
                <div className="text-[11px] text-tsc">Revenue: $247.6k</div>
              </div>
              <div className="w-full bg-surface-container rounded-full h-2">                <div className="bg-primary-container h-full rounded-full" style={{ width: '85%' }}></div></div>
              <div className="text-[10px] text-primary font-bold">+112% over target</div>
            </div>
            <div className="p-4 rounded-xl bg-surface-container-low flex flex-col justify-between space-y-3">
              <div className="text-xs font-semibold text-tsc">Meta (IG / FB)</div>
              <div>
                <div className="font-headline text-3xl font-bold text-on-surface">3.62x</div>
                <div className="text-[11px] text-tsc">Revenue: $149.1k</div>
              </div>
              <div className="w-full bg-surface-container rounded-full h-2">                <div className="bg-primary-container h-full rounded-full" style={{ width: '72%' }}></div></div>
              <div className="text-[10px] text-primary font-bold">+81% over target</div>
            </div>
            <div className="p-4 rounded-xl bg-surface-container-low flex flex-col justify-between space-y-3">
              <div className="text-xs font-semibold text-tsc">Twitter / X</div>
              <div>
                <div className="font-headline text-3xl font-bold text-on-surface">3.12x</div>
                <div className="text-[11px] text-tsc">Revenue: $60.8k</div>
              </div>
              <div className="w-full bg-surface-container rounded-full h-2">                <div className="bg-tertiary h-full rounded-full" style={{ width: '62%' }}></div></div>
              <div className="text-[10px] text-primary font-bold">+56% over target</div>
            </div>
            <div className="p-4 rounded-xl bg-surface-container-low flex flex-col justify-between space-y-3">
              <div className="text-xs font-semibold text-tsc">LinkedIn Ads</div>
              <div>
                <div className="font-headline text-3xl font-bold text-on-surface">2.14x</div>
                <div className="text-[11px] text-tsc">Revenue: $20.3k</div>
              </div>
              <div className="w-full bg-surface-container rounded-full h-2">                <div className="bg-tsc h-full rounded-full" style={{ width: '43%' }}></div></div>
              <div className="text-[10px] text-tsc font-semibold">At target (≥2.0x)</div>
            </div>
          </div>
        </div>
        <div className="p-6 rounded-xl bg-surface-container-lowest shadow-sm space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h2 className="font-headline text-lg font-bold text-on-surface">Daily Spend &amp; Conversion Pacing (30 Days)</h2>
              <p className="text-xs text-tsc">Visualizing daily expenditure fluctuations alongside 7-day rolling performance</p>
            </div>
            <div className="flex items-center gap-4 text-xs">
              <span className="flex items-center gap-1.5 text-tsc">
                <span className="w-3 h-3 rounded-sm bg-primary/40"></span>
                Daily Spend
              </span>
              <span className="flex items-center gap-1.5 text-tsc">
                <span className="w-4 h-0.5 bg-primary"></span>
                7d Rolling Baseline
              </span>
            </div>
          </div>
          <div className="w-full h-52 pt-4">
            <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 1000 200">
              <defs>
                <linearGradient id="spendGradient" x1={0} x2={0} y1={0} y2={1}>
                  <stop offset="0%" stopColor="#4a7c59" stopOpacity={0.3}></stop>
                  <stop offset="100%" stopColor="#4a7c59" stopOpacity={0.0}></stop>
                </linearGradient>
              </defs>
              <line stroke="#f0ece4" strokeWidth={1} x1={0} x2={1000} y1={40} y2={40}></line>
              <line stroke="#f0ece4" strokeWidth={1} x1={0} x2={1000} y1={90} y2={90}></line>
              <line stroke="#f0ece4" strokeWidth={1} x1={0} x2={1000} y1={140} y2={140}></line>
              <line stroke="#eae6de" strokeWidth={1} x1={0} x2={1000} y1={190} y2={190}></line>
              <polygon fill="url(#spendGradient)" points="           0,160 35,150 70,155 105,140 140,110 175,95 210,120 245,160 280,150 315,100 350,85 385,80 420,110 455,150 490,140 525,90 560,75 595,70 630,95 665,140 700,130 735,80 770,60 805,50 840,75 875,110 910,100 945,70 980,55 1000,50 1000,190 0,190         "></polygon>
              <polyline fill="none" points="           0,160 35,150 70,155 105,140 140,110 175,95 210,120 245,160 280,150 315,100 350,85 385,80 420,110 455,150 490,140 525,90 560,75 595,70 630,95 665,140 700,130 735,80 770,60 805,50 840,75 875,110 910,100 945,70 980,55 1000,50         " stroke="#78a886" strokeWidth={2}></polyline>
              <path d="M 0,155 Q 250,130 500,100 T 1000,65" fill="none" stroke="#4a7c59" strokeWidth={3}></path>
              <circle cx={805} cy={50} fill="#4a7c59" r={4.5} stroke="#ffffff" strokeWidth={2}></circle>
            </svg>
          </div>
          <div className="flex justify-between items-center text-[10px] font-mono text-tsc pt-1">
            <span>May 01 (Day 1)</span>
            <span>May 08</span>
            <span>May 15</span>
            <span>May 22</span>
            <span>May 30 (Today)</span>
          </div>
        </div>
        <div className="p-6 rounded-xl bg-surface-container-lowest shadow-sm space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <h2 className="font-headline text-lg font-bold text-on-surface">Ad Campaigns (24 Active)</h2>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-surface-container text-tsc">Live Audit</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="relative">
<input className="pl-8 pr-3 py-1.5 rounded-lg bg-surface-container-low text-xs text-on-surface placeholder:text-tsc focus:outline-none focus:ring-1 focus:ring-primary w-56" id="campaign-search" placeholder="Filter campaign names..." type="text" />
<MsIcon name="search" className="absolute left-2.5 top-1/2 -translate-y-1/2 text-[16px] text-tsc" />
              </div>
            </div>
          </div>
          <div className="overflow-x-auto -mx-6 px-6">
            <table className="w-full text-left text-xs whitespace-nowrap">
              <thead>
                <tr className="text-[10px] font-bold uppercase tracking-wider text-tsc border-b border-surface-container-high/60">
                  <th className="py-3 px-3">Campaign</th>
                  <th className="py-3 px-3">Platform</th>
                  <th className="py-3 px-3 text-right">Spend</th>
                  <th className="py-3 px-3 text-right">Impr.</th>
                  <th className="py-3 px-3 text-right">Clicks</th>
                  <th className="py-3 px-3 text-right">CTR</th>
                  <th className="py-3 px-3 text-right">CPC</th>
                  <th className="py-3 px-3 text-right">Conv.</th>
                  <th className="py-3 px-3 text-right">CPA</th>
                  <th className="py-3 px-3 text-right">ROAS</th>
                  <th className="py-3 px-3 text-center">Status</th>
                  <th className="py-3 px-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-container-high/40" id="campaigns-table-body">
                <tr className="hover:bg-surface-container-low/50 transition-colors">
                  <td className="py-3.5 px-3">
                    <div className="flex flex-col">
                      <span className="font-bold text-on-surface">100k Challenge Scalper Surge</span>
                      <span className="text-[10px] text-tsc font-mono">#CMP-2025-01 · Performance Max</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-3">
                    <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-on-surface">
                      <span className="w-2 h-2 rounded-full bg-primary"></span>
                      Google Ads
                    </span>
                  </td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">$42,180.00</td>
                  <td className="py-3.5 px-3 text-right text-tsc">1.84M</td>
                  <td className="py-3.5 px-3 text-right text-tsc">62.4K</td>
                  <td className="py-3.5 px-3 text-right">                    <span className="px-1.5 py-0.5 rounded text-[11px] font-bold bg-primary-fixed/40 text-on-primary-fixed-variant">3.39%</span></td>
                  <td className="py-3.5 px-3 font-mono text-right text-tsc">$0.68</td>
                  <td className="py-3.5 px-3 text-right font-semibold text-on-surface">544 Traders</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-primary">$77.54</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">4.37x</td>
                  <td className="py-3.5 px-3 text-center">                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">Active</span></td>
                  <td className="py-3.5 px-3 text-right">                    <button className="px-2 py-1 rounded text-xs font-semibold text-primary hover:bg-surface-container-high transition-colors">View</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/50 transition-colors">
                  <td className="py-3.5 px-3">
                    <div className="flex flex-col">
                      <span className="font-bold text-on-surface">Meta Instagram Reels Viral Blitz</span>
                      <span className="text-[10px] text-tsc font-mono">#CMP-2025-02 · Story Placements</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-3">
                    <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-on-surface">
                      <span className="w-2 h-2 rounded-full bg-primary-container"></span>
                      Meta Ads
                    </span>
                  </td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">$28,500.00</td>
                  <td className="py-3.5 px-3 text-right text-tsc">980K</td>
                  <td className="py-3.5 px-3 text-right text-tsc">41.8K</td>
                  <td className="py-3.5 px-3 text-right">                    <span className="px-1.5 py-0.5 rounded text-[11px] font-bold bg-primary-fixed/40 text-on-primary-fixed-variant">4.27%</span></td>
                  <td className="py-3.5 px-3 font-mono text-right text-tsc">$0.68</td>
                  <td className="py-3.5 px-3 text-right font-semibold text-on-surface">366 Traders</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-primary">$77.86</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">3.82x</td>
                  <td className="py-3.5 px-3 text-center">                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">Active</span></td>
                  <td className="py-3.5 px-3 text-right">                    <button className="px-2 py-1 rounded text-xs font-semibold text-primary hover:bg-surface-container-high transition-colors">View</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/50 transition-colors">
                  <td className="py-3.5 px-3">
                    <div className="flex flex-col">
                      <span className="font-bold text-on-surface">TikTok Quant Algo Influencer Push</span>
                      <span className="text-[10px] text-tsc font-mono">#CMP-2025-03 · Spark Ads</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-3">
                    <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-on-surface">
                      <span className="w-2 h-2 rounded-full bg-tertiary-container"></span>
                      TikTok Ads
                    </span>
                  </td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">$14,250.00</td>
                  <td className="py-3.5 px-3 text-right text-tsc">520K</td>
                  <td className="py-3.5 px-3 text-right text-tsc">27.1K</td>
                  <td className="py-3.5 px-3 text-right">                    <span className="px-1.5 py-0.5 rounded text-[11px] font-bold bg-primary-fixed/40 text-on-primary-fixed-variant">5.21%</span></td>
                  <td className="py-3.5 px-3 font-mono text-right text-tsc">$0.53</td>
                  <td className="py-3.5 px-3 text-right font-semibold text-on-surface">228 Traders</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-primary">$62.50</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">4.82x</td>
                  <td className="py-3.5 px-3 text-center">                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">Active</span></td>
                  <td className="py-3.5 px-3 text-right">                    <button className="px-2 py-1 rounded text-xs font-semibold text-primary hover:bg-surface-container-high transition-colors">View</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/50 transition-colors">
                  <td className="py-3.5 px-3">
                    <div className="flex flex-col">
                      <span className="font-bold text-on-surface">Fintwit Breakout Retargeting</span>
                      <span className="text-[10px] text-tsc font-mono">#CMP-2025-04 · Tailored Audiences</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-3">
                    <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-on-surface">
                      <span className="w-2 h-2 rounded-full bg-tertiary"></span>
                      Twitter / X
                    </span>
                  </td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">$19,500.00</td>
                  <td className="py-3.5 px-3 text-right text-tsc">310K</td>
                  <td className="py-3.5 px-3 text-right text-tsc">8.8K</td>
                  <td className="py-3.5 px-3 text-right">                    <span className="px-1.5 py-0.5 rounded text-[11px] font-bold bg-primary-fixed/40 text-on-primary-fixed-variant">2.85%</span></td>
                  <td className="py-3.5 px-3 font-mono text-right text-tsc">$2.21</td>
                  <td className="py-3.5 px-3 text-right font-semibold text-on-surface">215 Traders</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-primary">$90.69</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">3.12x</td>
                  <td className="py-3.5 px-3 text-center">                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">Active</span></td>
                  <td className="py-3.5 px-3 text-right">                    <button className="px-2 py-1 rounded text-xs font-semibold text-primary hover:bg-surface-container-high transition-colors">View</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/50 transition-colors">
                  <td className="py-3.5 px-3">
                    <div className="flex flex-col">
                      <span className="font-bold text-on-surface">Quant Proprietary Elite (C-Suite)</span>
                      <span className="text-[10px] text-tsc font-mono">#CMP-2025-05 · Sponsored InMail</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-3">
                    <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-on-surface">
                      <span className="w-2 h-2 rounded-full bg-tsc"></span>
                      LinkedIn
                    </span>
                  </td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">$9,500.00</td>
                  <td className="py-3.5 px-3 text-right text-tsc">85K</td>
                  <td className="py-3.5 px-3 text-right text-tsc">1.4K</td>
                  <td className="py-3.5 px-3 text-right text-tsc">1.62%</td>
                  <td className="py-3.5 px-3 font-mono text-right text-tsc">$6.78</td>
                  <td className="py-3.5 px-3 text-right font-semibold text-on-surface">42 Traders</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-error">$226.19</td>
                  <td className="py-3.5 px-3 font-mono text-right font-bold text-on-surface">2.14x</td>
                  <td className="py-3.5 px-3 text-center">                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary-container text-on-secondary-container">Paused</span></td>
                  <td className="py-3.5 px-3 text-right">                    <button className="px-2 py-1 rounded text-xs font-semibold text-primary hover:bg-surface-container-high transition-colors">View</button></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="pt-3 border-t border-surface-container-high/60 flex items-center justify-between text-xs text-tsc">
            <span>Showing 5 of 24 verified attribution cohorts</span>
            <div className="flex items-center gap-1">
              <button className="px-2 py-1 rounded bg-surface-container text-on-surface font-semibold text-xs">1</button>
              <button className="px-2 py-1 rounded hover:bg-surface-container text-tsc text-xs">2</button>
              <button className="px-2 py-1 rounded hover:bg-surface-container text-tsc text-xs">3</button>
            </div>
          </div>
        </div>
        <div className="p-6 rounded-xl bg-surface-container-lowest shadow-sm space-y-6">
          <div className="flex items-center gap-2">
            <h2 className="font-headline text-lg font-bold text-on-surface">Cross-Channel Trader Conversion Funnel</h2>
            <div className="group relative inline-block">
<MsIcon name="help_outline" className="text-[16px] text-tsc cursor-help" />
              <div className="absolute left-1/2 -translate-x-1/2 bottom-full mb-2 hidden group-hover:block w-72 p-2.5 bg-inverse-surface text-inverse-on-surface text-[11px] rounded-lg shadow-lg z-30 leading-relaxed font-normal">                Tracks progression from paid ad impressions to verified KYC funded challenge traders.</div>
            </div>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-4">
              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-on-surface flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-surface-container flex items-center justify-center text-[10px] text-tsc">1</span>
                    Ad Impressions
                  </span>
                  <span className="font-mono font-bold text-on-surface">3,840,000</span>
                </div>
                <div className="w-full bg-surface-container rounded-lg h-8 relative overflow-hidden flex items-center px-3">
                  <div className="absolute inset-y-0 left-0 bg-primary/20 rounded-lg w-full"></div>
                  <span className="relative z-10 text-[11px] font-bold text-on-surface">100% Top of Funnel Pool</span>
                </div>
              </div>
              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-on-surface flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-surface-container flex items-center justify-center text-[10px] text-tsc">2</span>
                    Paid Clicks
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold text-primary bg-primary-fixed/40 px-1.5 py-0.5 rounded">3.71% CTR</span>
                    <span className="font-mono font-bold text-on-surface">142,500</span>
                  </div>
                </div>
                <div className="w-full bg-surface-container rounded-lg h-8 relative overflow-hidden flex items-center px-3">
                  <div className="absolute inset-y-0 left-0 bg-primary/40 rounded-lg" style={{ width: '58%' }}></div>
                  <span className="relative z-10 text-[11px] font-bold text-on-surface">3.71% Qualified Click-Through</span>
                </div>
              </div>
              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-on-surface flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-surface-container flex items-center justify-center text-[10px] text-tsc">3</span>
                    Challenge Signups / Orders
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold text-tertiary bg-tertiary-fixed/50 px-1.5 py-0.5 rounded">5.91% Cart Conv.</span>
                    <span className="font-mono font-bold text-on-surface">8,420</span>
                  </div>
                </div>
                <div className="w-full bg-surface-container rounded-lg h-8 relative overflow-hidden flex items-center px-3">
                  <div className="absolute inset-y-0 left-0 bg-tertiary/40 rounded-lg" style={{ width: '32%' }}></div>
                  <span className="relative z-10 text-[11px] font-bold text-on-surface">5.91% Checkout Completion</span>
                </div>
              </div>
              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-xs">
                  <span className="font-bold text-on-surface flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-primary flex items-center justify-center text-[10px] text-on-primary">4</span>
                    Funded Challenge Traders
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold text-primary bg-primary-fixed px-1.5 py-0.5 rounded">21.88% Pass Rate</span>
                    <span className="font-mono font-bold text-primary">1,842</span>
                  </div>
                </div>
                <div className="w-full bg-surface-container rounded-lg h-8 relative overflow-hidden flex items-center px-3">
                  <div className="absolute inset-y-0 left-0 bg-primary rounded-lg" style={{ width: '22%' }}></div>
                  <span className="relative z-10 text-[11px] font-bold text-on-primary">21.88% Evaluated &amp; Active</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col justify-between space-y-3">
              <div className="p-3.5 rounded-xl bg-surface-container-low">
                <div className="text-[10px] uppercase font-bold text-tsc">Stage Velocity</div>
                <div className="font-headline text-lg font-bold text-on-surface">4.2 Days</div>
                <div className="text-[11px] text-tsc">From ad click to challenge test initiate</div>
              </div>
              <div className="p-3.5 rounded-xl bg-surface-container-low">
                <div className="text-[10px] uppercase font-bold text-tsc">Organic Ripple Coefficient</div>
                <div className="font-headline text-lg font-bold text-primary">1.28x</div>
                <div className="text-[11px] text-tsc">Unattributed trader referrals spurred by paid ads</div>
              </div>
              <div className="p-3.5 rounded-xl bg-surface-container-low">
                <div className="text-[10px] uppercase font-bold text-tsc">Pass-Through Churn</div>
                <div className="font-headline text-lg font-bold text-on-surface">78.1%</div>
                <div className="text-[11px] text-tsc">Challenge fail rate (standard risk model)</div>
              </div>
              <div className="p-3.5 rounded-xl bg-surface-container-low">
                <div className="text-[10px] uppercase font-bold text-tsc">LTV / CPA Efficiency</div>
                <div className="font-headline text-lg font-bold text-tertiary">5.4x Multiple</div>
                <div className="text-[11px] text-tsc">Blended 180-day lifetime customer value</div>
              </div>
            </div>
          </div>
        </div>
        <div className="fixed bottom-6 right-8 z-40">
          <button className="inline-flex items-center gap-2.5 px-5 py-3.5 rounded-xl bg-primary text-on-primary text-xs font-bold shadow-lg shadow-on-surface/20 hover:scale-105 active:scale-95 transition-all" onClick={() => setSo1(true)}>
<MsIcon name="add" className="text-[20px]" />
            <span>+ New Ad Campaign</span>
          </button>
        </div>
      </div>
      {so0 && (
        <>
        <div className="fixed inset-0 z-50 bg-inverse-surface/60 backdrop-blur-sm transition-opacity duration-300">
          <div className="fixed top-0 right-0 h-screen w-full max-w-[560px] bg-surface-container-low shadow-[0_4px_30px_rgba(46,50,48,0.18)] z-50 flex flex-col justify-between overflow-hidden">
            <div className="px-7 pt-6 pb-5 bg-surface-container-low shrink-0 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <span className="text-[10px] font-bold tracking-widest uppercase text-tsc">{"Campaign Management // Attribution Engine"}</span>
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed text-[10px] font-bold">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                    ACTIVE PACING
                  </span>
                </div>
                <button className="w-8 h-8 rounded-lg flex items-center justify-center text-tsc hover:bg-surface-container-high hover:text-on-surface transition-colors" title="Close Panel" type="button" onClick={() => setSo0(false)}><MsIcon name="close" className="text-[20px]" /></button>
              </div>
              <div>
                <h2 className="font-headline text-xl font-bold text-on-surface tracking-tight leading-snug">                  Ad Campaign: 100k Challenge Scalper Surge</h2>
                <div className="flex items-center gap-2 mt-1.5">
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-surface-container text-xs font-semibold text-on-surface">
<MsIcon name="verified" className="text-[14px] text-primary" />
                    #CMP-2025-01 · Google Ads
                  </span>
                  <span className="text-xs text-tsc">•</span>
                  <span className="text-xs text-tsc">Inspect pacing, real-time CPA/ROAS, and budget controls.</span>
                </div>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto px-7 py-2 space-y-6">
              <div className="p-3.5 rounded-xl bg-surface-container shadow-sm">
                <div className="flex items-center justify-between pb-2 mb-2.5">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-tsc">Live Performance Signals (30D)</span>
                  <span className="text-[10px] font-bold text-primary flex items-center gap-1">
<MsIcon name="sync" className="text-[12px]" />
                    Synced 2m ago
                  </span>
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                  <div className="p-2.5 rounded-lg bg-surface-container-lowest shadow-sm flex flex-col justify-between">
                    <span className="text-[10px] font-semibold text-tsc">Spend</span>
                    <span className="font-headline text-base font-bold text-on-surface mt-1">$42,180.00</span>
                    <span className="text-[10px] font-medium text-primary mt-0.5">72% of budget</span>
                  </div>
                  <div className="p-2.5 rounded-lg bg-surface-container-lowest shadow-sm flex flex-col justify-between">
                    <span className="text-[10px] font-semibold text-tsc">CPA</span>
                    <span className="font-headline text-base font-bold text-on-surface mt-1">$77.54</span>
                    <span className="text-[10px] font-medium text-primary mt-0.5">Target: ≤$100 (Optimal)</span>
                  </div>
                  <div className="p-2.5 rounded-lg bg-surface-container-lowest shadow-sm flex flex-col justify-between">
                    <span className="text-[10px] font-semibold text-tsc">ROAS</span>
                    <span className="font-headline text-base font-bold text-on-surface mt-1">4.37x</span>
                    <span className="text-[10px] font-medium text-tertiary mt-0.5">Target: ≥2.0x (High)</span>
                  </div>
                  <div className="p-2.5 rounded-lg bg-surface-container-lowest shadow-sm flex flex-col justify-between">
                    <span className="text-[10px] font-semibold text-tsc">CTR</span>
                    <span className="font-headline text-base font-bold text-on-surface mt-1">3.39%</span>
                    <span className="text-[10px] font-medium text-on-surface-variant mt-0.5">Ind. Avg: 2.10%</span>
                  </div>
                </div>
              </div>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-tsc">1. Basic Identification</span>
                  <span className="text-[11px] text-tsc">Required fields</span>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="text-xs font-semibold text-on-surface">Campaign Name</label>
                    <div className="flex items-center gap-1 text-[11px] text-tsc">
<MsIcon name="info" className="text-[13px]" />
                      <span>Visible across global blotters</span>
                    </div>
                  </div>
<input className="w-full px-3.5 py-2.5 rounded-lg bg-surface-container text-xs font-medium text-on-surface placeholder:text-tsc focus:outline-none focus:ring-1 focus:ring-primary shadow-sm" type="text" defaultValue="100k Challenge Scalper Surge" />
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="text-xs font-semibold text-on-surface">Ad Network &amp; Platform</label>
                    <span className="text-[11px] text-tsc">Exchange feed route</span>
                  </div>
                  <div className="relative">
                    <select className="w-full appearance-none pl-10 pr-9 py-2.5 rounded-lg bg-surface-container text-xs font-semibold text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm cursor-pointer" defaultValue="Google Ads (Search & Performance Max)">
                      <option>Google Ads (Search &amp; Performance Max)</option>
                      <option>Meta Ads (Instagram &amp; Facebook Feed)</option>
                      <option>TikTok Ads (In-Feed Spark Ads)</option>
                      <option>LinkedIn Marketing Solutions</option>
                      <option>Twitter / X Ads</option>
                    </select>
<MsIcon name="public" className="absolute left-3 top-1/2 -translate-y-1/2 text-primary text-[18px]" />
<MsIcon name="expand_more" className="absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[18px] pointer-events-none" />
                  </div>
                </div>
              </div>
              <div className="space-y-4 pt-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-tsc">2. Budget &amp; Scheduling</span>
                  <span className="text-[11px] text-primary font-semibold">Treasury Escrow Active</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-on-surface">Budget Cap Amount</label>
                    <div className="relative">
                      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-tsc text-xs font-bold">$</span>
<input className="w-full pl-7 pr-3.5 py-2 rounded-lg bg-surface-container text-xs font-bold text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm" type="text" defaultValue="58,400.00" />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-on-surface">Allocation Model</label>
                    <div className="relative">
                      <select className="w-full appearance-none px-3.5 py-2 rounded-lg bg-surface-container text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm cursor-pointer" defaultValue="Total Budget (Lifetime)">
                        <option>Total Budget (Lifetime)</option>
                        <option>Daily Pacing Cap (Dynamic)</option>
                        <option>Accelerated Frontload</option>
                      </select>
<MsIcon name="unfold_more" className="absolute right-3 top-1/2 -translate-y-1/2 text-tsc text-[16px] pointer-events-none" />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-on-surface">Deployment Start</label>
                    <div className="relative">
<input className="w-full pl-3.5 pr-8 py-2 rounded-lg bg-surface-container text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm cursor-pointer" type="date" defaultValue="2025-05-01" />
<MsIcon name="calendar_month" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-tsc text-[16px] pointer-events-none" />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-on-surface">Maturity / End Date</label>
                    <div className="relative">
<input className="w-full pl-3.5 pr-8 py-2 rounded-lg bg-surface-container text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm cursor-pointer" type="date" defaultValue="2025-05-31" />
<MsIcon name="calendar_month" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-tsc text-[16px] pointer-events-none" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="space-y-4 pt-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase tracking-wider text-tsc">3. Targeting &amp; Creative Assets</span>
                  <span className="text-[11px] text-tsc">Pixel Attribution v2</span>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="text-xs font-semibold text-on-surface">Target Audience &amp; Keyword Scope</label>
                    <span className="text-[10px] text-tsc">Search &amp; In-Market Intent</span>
                  </div>
<textarea className="w-full p-3 rounded-lg bg-surface-container text-xs text-on-surface placeholder:text-tsc focus:outline-none focus:ring-1 focus:ring-primary shadow-sm leading-relaxed" rows={3} defaultValue="Search & Performance Max: High-intent forex/crypto scalpers, prop trading search keywords (funded account, MT5 scalping, zero spread challenge), geo US, UK, DE, AU, SG." />
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="text-xs font-semibold text-on-surface">Creative Landing URL &amp; UTM Params</label>
                    <button className="text-[10px] font-bold text-primary hover:underline flex items-center gap-0.5" type="button" onClick={() => setSo0(false)}>
<MsIcon name="open_in_new" className="text-[12px]" />
                      Test Link
                    </button>
                  </div>
                  <div className="relative">
<MsIcon name="link" className="absolute left-3 top-1/2 -translate-y-1/2 text-tsc text-[16px]" />
<input className="w-full pl-9 pr-3.5 py-2.5 rounded-lg bg-surface-container text-[11px] font-mono text-on-surface focus:outline-none focus:ring-1 focus:ring-primary shadow-sm truncate" type="text" defaultValue="https://terradesk.com/challenges/100k-scalper?utm_source=google&utm_medium=cpc&utm_campaign=scalper_surge" />
                  </div>
                </div>
              </div>
              <div className="pt-2">
                <div className="p-4 rounded-xl bg-surface-container shadow-sm flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-lg bg-primary-container/30 flex items-center justify-center text-primary shrink-0 mt-0.5"><MsIcon name="bolt" className="text-lg" /></div>
                    <div className="flex flex-col">
                      <span className="text-xs font-bold text-on-surface leading-tight">Campaign Active &amp; Pacing</span>
                      <p className="text-[11px] text-on-surface-variant mt-1 leading-relaxed">                        Live bids and impression ingress active across Google Search &amp; PMax ad exchanges. When paused, tracking pixels continue recording delayed conversions without incurring additional costs.</p>
                    </div>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer shrink-0 mt-1">
<input defaultChecked className="sr-only peer" type="checkbox" />
                    <div className="w-11 h-6 bg-surface-container-highest peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface-container-lowest after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                  </label>
                </div>
              </div>
            </div>
            <div className="px-7 py-4 bg-surface-container shrink-0 flex items-center justify-between shadow-[0_-2px_10px_rgba(46,50,48,0.03)]">
              <button className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-error-container/30 text-error hover:bg-error-container hover:text-on-error-container transition-colors text-xs font-bold" type="button" onClick={() => setSo0(false)}>
<MsIcon name="delete_outline" className="text-base" />
                <span>Delete Campaign</span>
              </button>
              <div className="flex items-center gap-2.5">
                <button className="flex items-center gap-1 px-3.5 py-2 rounded-lg bg-surface-container-low text-on-surface hover:bg-surface-container-high transition-colors text-xs font-semibold shadow-sm" type="button">
<MsIcon name="pause_circle" className="text-[16px] text-tsc" />
                  <span>Pause Campaign</span>
                </button>
                <button className="flex items-center gap-1.5 px-5 py-2 rounded-lg bg-primary text-on-primary hover:bg-primary/90 transition-all text-xs font-bold shadow-md active:scale-95" type="button" onClick={() => setSo0(false)}>
<MsIcon name="check_circle" className="text-[16px]" />
                  <span>Save Changes</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        </>
      )}
      {so1 && (
        <>
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-inverse-surface/65 backdrop-blur-md transition-opacity duration-200" id="delete-modal-overlay">
          <div className="relative w-full max-w-[520px] bg-surface-container-lowest rounded-xl shadow-xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="h-1.5 w-full bg-error"></div>
            <div className="p-7 space-y-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-error-container text-error flex items-center justify-center shrink-0 shadow-sm"><MsIcon name="delete_forever" className="text-[26px]" /></div>
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-error">Destructive Action</span>
                    <span className="w-1 h-1 rounded-full bg-error"></span>
                    <span className="text-[11px] font-semibold text-tsc">Blotter Ops Protocol 14B</span>
                  </div>
                  <h2 className="font-headline text-2xl font-bold text-on-surface tracking-tight">Delete this campaign?</h2>
                  <p className="text-xs text-on-surface-variant leading-relaxed">                    You are about to sever attribution tracking and purge this campaign from active liquidity ledger routes.</p>
                </div>
              </div>
              <div className="rounded-xl bg-surface-container p-4 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-tsc">Target Entity</span>
                  <span className="px-2 py-0.5 rounded-full bg-surface-container-highest text-[10px] font-bold text-on-surface-variant">Active Ingress</span>
                </div>
                <div className="space-y-1">
                  <div className="text-sm font-bold text-on-surface tracking-tight font-headline">                    100k Challenge Scalper Surge</div>
                  <div className="flex flex-wrap items-center gap-2 text-xs text-on-surface-variant font-medium">
                    <span className="px-1.5 py-0.5 rounded bg-surface-container-high font-mono text-[11px] font-semibold text-on-surface">#CMP-2025-01</span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
<MsIcon name="campaign" className="text-[14px] text-tsc" />
                      <span>Google Ads</span>
                    </span>
                  </div>
                </div>
                <div className="pt-2 border-t-0 flex items-center justify-between text-xs bg-surface-container-high/60 -mx-4 -mb-4 px-4 py-2.5 rounded-b-xl">
                  <div className="flex items-center gap-1.5 text-on-surface font-semibold">
<MsIcon name="monetization_on" className="text-[15px] text-tertiary" />
                    <span>$42,180.00 spent</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-tsc font-medium">
<MsIcon name="group" className="text-[15px] text-primary" />
                    <span>544 Funded Traders attributed</span>
                  </div>
                </div>
              </div>
              <div className="space-y-3">
                <div className="text-xs font-bold uppercase tracking-wider text-on-surface flex items-center gap-1.5">
<MsIcon name="warning" className="text-[16px] text-error" />
                  <span>Immediate Operational Consequences</span>
                </div>
                <div className="rounded-xl bg-surface-container-low p-3.5 space-y-3">
                  <div className="flex items-start gap-2.5 text-xs text-on-surface-variant">
<MsIcon name="power_off" className="text-[18px] text-error shrink-0 mt-0.5" />
                    <div className="leading-relaxed">
                      <span className="font-bold text-on-surface">Immediate Ingress Termination:</span>
                      Active Google Ads bids and ad group tracking will be detached immediately.
                    </div>
                  </div>
                  <div className="flex items-start gap-2.5 text-xs text-on-surface-variant">
<MsIcon name="cleaning_services" className="text-[18px] text-tertiary shrink-0 mt-0.5" />
                    <div className="leading-relaxed">
                      <span className="font-bold text-on-surface">Platform-side Cleanup Required:</span>
                      External ad exchange tracking pixels must be manually deprecated in Google Ads Manager to prevent orphaned webhooks.
                    </div>
                  </div>
                  <div className="flex items-start gap-2.5 text-xs text-on-surface-variant">
<MsIcon name="archive" className="text-[18px] text-primary shrink-0 mt-0.5" />
                    <div className="leading-relaxed">
                      <span className="font-bold text-on-surface">Attribution Integrity:</span>
                      Trailing 90-day multi-touch attribution ledger records and funded trader audit history will be archived into cold WORM storage.
                    </div>
                  </div>
                  <div className="flex items-start gap-2.5 text-xs text-error font-semibold">
<MsIcon name="lock_reset" className="text-[18px] text-error shrink-0 mt-0.5" />
                    <div className="leading-relaxed">
                      <span>Irreversible Action:</span>
                      This action is permanent and cannot be undone.
                    </div>
                  </div>
                </div>
              </div>
              <div className="space-y-3">
                <label className="flex items-start gap-3 p-3 rounded-lg bg-surface-container cursor-pointer select-none">
<input defaultChecked className="mt-0.5 w-4 h-4 rounded text-error accent-error cursor-pointer" id="acknowledgment-check" type="checkbox" />
                  <span className="text-xs text-on-surface font-medium leading-relaxed">                    I understand that external ad exchange synchronization will be severed and this action is logged in the permanent audit trail.</span>
                </label>
                <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-surface-container-high text-[11px] text-tsc">
<MsIcon name="security" className="text-[15px] text-primary" />
                  <span className="font-medium text-on-surface-variant">Audit Stamp:</span>
                  <span className="truncate">Logged under Marcus Vance (CRO / Ops Principal) · IP: 198.51.100.42</span>
                </div>
              </div>
            </div>
            <div className="px-7 py-4 bg-surface-container flex items-center justify-between gap-3">
              <div className="text-[11px] text-tsc flex items-center gap-1 font-mono">
<MsIcon name="shield" className="text-[14px]" />
                <span>AUTH_KEY_VERIFIED</span>
              </div>
              <div className="flex items-center gap-3">
                <button className="px-5 py-2.5 rounded-xl bg-surface-container-highest text-xs font-semibold text-on-surface hover:bg-surface-dim active:scale-[0.98] transition-all" id="cancel-delete-btn" type="button" onClick={() => setSo1(false)}>                  Cancel</button>
                <button className="px-5 py-2.5 rounded-xl bg-error text-xs font-bold text-on-error hover:opacity-95 shadow-md flex items-center gap-2 active:scale-[0.98] transition-all" id="confirm-delete-btn" type="button" onClick={() => setSo1(false)}>
<MsIcon name="delete" className="text-[18px]" />
                  <span>Delete Campaign</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        </>
      )}
    </>
  );
}
