"use client";

/**
 * Platform Health — Stitch conversion (view-id: `platform-health`)
 *
 * Source: stitch_screens/system_health
 * Spec: [EXISTING] · overlay states: 2/2 wired
 * States: system_health_incident_inspection_automated_failover_drawer_state✓, system_health_simulate_disaster_recovery_drill_modal_state✓
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import * as React from "react";
import { MsIcon } from "@/components/stitch/stitch";

export function PlatformHealthStitchPage() {
  const [so0, setSo0] = React.useState(false);
  const [so1, setSo1] = React.useState(false);
  return (
    <>
      <div className="flex flex-col w-full space-y-8 pb-16">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-2 border-b border-outline-variant/30">
          <div className="flex items-center gap-2 text-xs text-on-surface-variant font-medium">
            <span>Platform Governance</span>
<MsIcon name="chevron_right" className="text-[14px] text-outline" />
            <span>Infrastructure &amp; Mesh</span>
<MsIcon name="chevron_right" className="text-[14px] text-outline" />
            <span className="text-on-surface font-semibold bg-surface-container px-2 py-0.5 rounded">System Health</span>
          </div>
          <div className="flex flex-wrap items-center gap-2.5">
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant text-[11px] font-medium shadow-sm">
<MsIcon name="verified" className="text-[14px] text-primary" />
              <span>SOC 2 Type II Certified</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant text-[11px] font-medium shadow-sm">
<MsIcon name="lock_clock" className="text-[14px] text-tertiary" />
              <span>SEC Rule 17a-4 WORM</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-primary-fixed text-on-primary-fixed-variant text-[11px] font-bold shadow-sm">
              <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
              <span>99.982% Fleet SLA Target</span>
            </div>
          </div>
        </div>
        <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-6">
          <div className="max-w-3xl space-y-2">
            <div className="flex items-center gap-3">
              <h1 className="text-3xl font-headline font-bold text-on-surface tracking-tight">System Health</h1>
              <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-surface-container-high text-xs font-semibold text-on-surface">
                <span className="relative flex h-2.5 w-2.5">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-primary"></span>
                </span>
                <span>Core Ingress Operational</span>
                <span className="text-outline">·</span>
                <span className="text-error font-medium flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-error"></span>
                  1 Degraded
                </span>
              </div>
            </div>
            <p className="text-sm text-on-surface-variant leading-relaxed">

        Real-time telemetry, sub-millisecond edge latency, and microservice mesh health across <strong className="text-on-surface font-semibold">LD4 (London)</strong>, <strong className="text-on-surface font-semibold">NY4 (New York)</strong>, and <strong className="text-on-surface font-semibold">TY3 (Tokyo)</strong> sovereign high-frequency enclaves.
      
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <div className="relative">
<MsIcon name="filter_alt" className="absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-on-surface-variant" />
<input className="pl-9 pr-4 py-2 text-xs rounded-xl bg-surface-container-low text-on-surface placeholder:text-on-surface-variant/60 focus:outline-none focus:bg-surface-container-lowest focus:ring-2 focus:ring-primary shadow-sm w-64 transition-all" id="service-search-input" placeholder="Filter services, clusters... [⌘K]" type="text" />
            </div>
            <button className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-semibold shadow-sm transition-colors" id="subscribe-updates-btn">
<MsIcon name="notifications_active" className="text-[17px] text-primary" />
              <span>Subscribe</span>
            </button>
            <button className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-error-container/60 hover:bg-error-container text-on-error-container text-xs font-semibold transition-colors shadow-sm" id="simulate-drill-btn" onClick={() => setSo1(true)}>
<MsIcon name="warning" className="text-[17px] text-error" />
              <span>Simulate Drill</span>
            </button>
            <button className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary hover:bg-primary/90 text-on-primary text-xs font-bold shadow-md transition-transform active:scale-95" id="run-diagnostics-btn">
<MsIcon name="sync" className="text-[17px]" />
              <span>Run Diagnostics</span>
            </button>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Uptime (Last 30 Days)</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">+0.014% vs SLA</span>
            </div>
            <div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-headline font-bold text-on-surface tracking-tight">99.982%</span>
                <span className="text-xs font-semibold text-primary">Target met</span>
              </div>
              <div className="mt-3 flex items-center gap-1 h-3">
                <div className="flex-1 h-2 rounded-full bg-primary" title="Day 1-7: 100%"></div>
                <div className="flex-1 h-2 rounded-full bg-primary" title="Day 8-14: 100%"></div>
                <div className="flex-1 h-2 rounded-full bg-primary" title="Day 15-21: 100%"></div>
                <div className="w-2.5 h-2 rounded-full bg-error" title="Day 22: Minor failover (4m 12s)"></div>
                <div className="flex-1 h-2 rounded-full bg-primary" title="Day 23-30: 100%"></div>
              </div>
            </div>
            <div className="pt-2 text-[11px] text-on-surface-variant flex items-center gap-1">
<MsIcon name="history" className="text-[14px] text-outline" />
              <span>Unscheduled downtime: <strong className="font-mono text-on-surface">4m 12s</strong> across 8 clusters</span>
            </div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Avg Mesh Latency</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">Optimal</span>
            </div>
            <div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-headline font-bold text-on-surface tracking-tight font-mono">1.12<span className="text-lg font-normal text-on-surface-variant ml-1">ms</span></span>
                <span className="text-xs font-semibold text-primary">-0.08ms</span>
              </div>
              <div className="mt-3 grid grid-cols-3 gap-1 text-[10px] font-mono text-on-surface-variant bg-surface-container-low px-2 py-1.5 rounded-lg">
                <div>p50: <span className="text-on-surface font-semibold">0.42ms</span></div>
                <div>p95: <span className="text-on-surface font-semibold">1.84ms</span></div>
                <div>p99: <span className="text-on-surface font-semibold">4.10ms</span></div>
              </div>
            </div>
            <div className="pt-2 text-[11px] text-on-surface-variant flex items-center gap-1 truncate">
<MsIcon name="cable" className="text-[14px] text-primary" />
              <span>Equinix LD4 direct fiber interconnect</span>
            </div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Global Error Rate</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary-container text-on-secondary-container">Green Zone</span>
            </div>
            <div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-headline font-bold text-on-surface tracking-tight font-mono">0.0031%</span>
                <span className="text-xs text-on-surface-variant">5xx errors</span>
              </div>
              <div className="mt-3 flex items-center justify-between text-[11px] text-on-surface-variant">
                <span>Dropped packets</span>
                <span className="font-mono font-bold text-primary">0.000%</span>
              </div>
            </div>
            <div className="pt-2 text-[11px] text-on-surface-variant flex items-center gap-1 truncate">
<MsIcon name="data_check" className="text-[14px] text-outline" />
              <span>12 HTTP 5xx / 4.2M total fleet queries</span>
            </div>
          </div>
          <div className="p-5 rounded-xl bg-surface-container-lowest shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Active Live Sessions</span>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">+14.2% MoM</span>
            </div>
            <div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-headline font-bold text-on-surface tracking-tight font-mono">34,892</span>
                <span className="text-xs text-primary font-semibold">Concurrent</span>
              </div>
              <div className="mt-3 flex items-center justify-between text-[11px] text-on-surface-variant">
                <span>Live WebSocket pipes</span>
                <span className="font-mono font-bold text-on-surface">1,284 duplex</span>
              </div>
            </div>
            <div className="pt-2 text-[11px] text-on-surface-variant flex items-center gap-1 truncate">
<MsIcon name="memory" className="text-[14px] text-primary" />
              <span>18 sovereign AWS Nitro enclaves</span>
            </div>
          </div>
        </div>
        <div className="p-4 rounded-xl bg-surface-container-low shadow-[0_4px_16px_rgba(184,50,48,0.08)] flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-start gap-3.5">
            <div className="w-9 h-9 rounded-lg bg-error-container text-on-error-container flex items-center justify-center shrink-0"><MsIcon name="crisis_alert" className="text-[20px] text-error animate-pulse" /></div>
            <div className="space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-xs font-bold uppercase tracking-wider text-error">Active Degraded Notice</span>
                <span className="text-on-surface font-semibold text-xs">Node US-EAST-02 · cTrader Gateway Bridge</span>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-error-container/80 text-on-error-container font-semibold">Elevated Jitter: +8.4ms</span>
              </div>
              <p className="text-xs text-on-surface-variant leading-relaxed">
                Automated BGP failover to London Equinix LD4 fiber interconnect active. All client order execution routing intact with
                <strong className="text-on-surface">0 order drops</strong>
                . Engineering war-room opened.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 self-end lg:self-center shrink-0">
            <a className="px-3 py-1.5 rounded-lg bg-surface-container hover:bg-surface-container-high text-xs font-semibold text-on-surface transition-colors flex items-center gap-1" href="#incidents-section" onClick={() => setSo0(true)}>
              <span>Inspect Incident #INC-8942</span>
<MsIcon name="arrow_outward" className="text-[14px]" />
            </a>
            <button className="px-3 py-1.5 rounded-lg bg-error text-on-error hover:bg-error/90 text-xs font-bold transition-transform active:scale-95 shadow-sm">              Bypass Node</button>
          </div>
        </div>
        <div className="rounded-xl bg-surface-container-lowest shadow-[0_4px_24px_rgba(46,50,48,0.04)] overflow-hidden">
          <div className="p-6 border-b border-surface-container flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div>
                <h2 className="text-lg font-headline font-bold text-on-surface">Platform Microservices &amp; Infrastructure Mesh</h2>
                <p className="text-xs text-on-surface-variant mt-0.5">Continuous deterministic heartbeat probes across 16 critical nodes</p>
              </div>
              <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-surface-container text-on-surface font-mono">16 Tracked</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-1.5 text-xs text-on-surface-variant font-mono bg-surface-container-low px-2.5 py-1 rounded-lg">
                <span className="w-2 h-2 rounded-full bg-primary animate-ping"></span>
                <span>Auto-refresh: <strong>5s</strong></span>
              </div>
            </div>
          </div>
          <div className="px-6 py-3 bg-surface-container-low/50 flex flex-wrap items-center gap-2 text-xs font-semibold text-on-surface-variant">
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg bg-surface-container-lowest text-primary shadow-sm font-bold transition-all" data-category="all">              All Services (16)</button>
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg hover:bg-surface-container-lowest transition-all" data-category="core">              Core Execution (4)</button>
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg hover:bg-surface-container-lowest transition-all" data-category="financial">              Financial &amp; PSP (3)</button>
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg hover:bg-surface-container-lowest transition-all" data-category="data">              Data &amp; Ledger (4)</button>
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg hover:bg-surface-container-lowest transition-all" data-category="ai">              Intelligence &amp; AI (3)</button>
            <button className="filter-tab-btn px-3 py-1.5 rounded-lg hover:bg-surface-container-lowest transition-all" data-category="enclave">              Per-Region Enclaves (2)</button>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-surface-container/60 text-on-surface-variant font-semibold text-[11px] uppercase tracking-wider">
                <tr>
                  <th className="py-3 px-6">Service &amp; Module ID</th>
                  <th className="py-3 px-4">Cluster / Topology</th>
                  <th className="py-3 px-4">Latency (p95)</th>
                  <th className="py-3 px-4">Throughput</th>
                  <th className="py-3 px-4">30d SLA</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-6 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-container/50 font-normal">
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="core">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0 font-bold"><MsIcon name="bolt" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Trading &amp; Order Routing Engine</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_trading_core · v4.12.8</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>LD4-Direct-Fiber</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-on-surface">0.42ms</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] bg-primary-fixed text-on-primary-fixed-variant font-mono">0.38-0.45</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">14,250 ops/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.999%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="core">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="verified_user" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Risk &amp; Surveillance Engine</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_risk_engine · v3.9.1</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>LD4-Enclave-01</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-on-surface">0.84ms</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] bg-primary-fixed text-on-primary-fixed-variant font-mono">p95</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">8,420 ev/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.995%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="bg-error-container/10 hover:bg-error-container/20 transition-colors" data-service="core">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-error-container text-on-error-container flex items-center justify-center shrink-0"><MsIcon name="public" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm flex items-center gap-2">
                          cTrader Gateway &amp; FIX Bridge
                          <span className="px-1.5 py-0.2 rounded text-[10px] bg-error-container text-error font-bold font-mono">INC-8942</span>
                        </div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_fix_ctrader · v2.1.0</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-error animate-pulse"></span>
                      <span className="font-semibold text-error">US-EAST-02 (Secaucus NY4)</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-error">9.54ms</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] bg-error-container text-error font-mono font-bold">+8.4ms jitter</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">1,820 msg/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-error">98.740%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-error-container text-on-error-container">
                      <span className="w-1.5 h-1.5 rounded-full bg-error animate-ping"></span>
                      Degraded
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-error text-on-error hover:bg-error/90 font-bold transition-all shadow-sm">                      Drilldown →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="core">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="developer_board" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">MetaTrader 5 Cluster Bridge</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_mt5_bridge · v5.0.3</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>LD4-MT5-Cluster</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-on-surface">0.76ms</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] bg-primary-fixed text-on-primary-fixed-variant font-mono">optimal</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">12,900 msg/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.998%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="financial">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-tertiary-container/30 text-tertiary flex items-center justify-center shrink-0"><MsIcon name="payments" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Multi-PSP Checkout &amp; Settlement</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_psp_gateway · v3.2.0</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>AWS-Nitro-KMS</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">                    <div className="flex items-center gap-2">                      <span className="font-mono font-bold text-on-surface">1.15ms</span></div></td>
                  <td className="py-4 px-4 font-mono text-on-surface">420 tx/min</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">100.00%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="data">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="lock" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm flex items-center gap-2">
                          WORM Cryptographic Audit Sink
                          <span className="px-1.5 py-0.2 rounded text-[10px] bg-secondary-container text-on-secondary-container font-semibold">SEC 17a-4</span>
                        </div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_worm_ledger · v1.8.0</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>AWS CloudHSM / LD4</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">                    <div className="flex items-center gap-2">                      <span className="font-mono font-bold text-on-surface">1.28ms</span></div></td>
                  <td className="py-4 px-4 font-mono text-on-surface">18.5k log/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">100.00%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="ai">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-tertiary-container/30 text-tertiary flex items-center justify-center shrink-0"><MsIcon name="neurology" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">AI Inference &amp; Anomaly Mesh</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_ai_sentinel · v2.4.6</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>LDN-AI-GPU (4x H100)</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">                    <div className="flex items-center gap-2">                      <span className="font-mono font-bold text-on-surface">14.2ms</span></div></td>
                  <td className="py-4 px-4 font-mono text-on-surface">280 tokens/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.950%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="data">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="hub" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Affiliate &amp; Attribution Ledger</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_affiliate_clickhouse · v2.0</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>ClickHouse LD4</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">                    <div className="flex items-center gap-2">                      <span className="font-mono font-bold text-on-surface">1.45ms</span></div></td>
                  <td className="py-4 px-4 font-mono text-on-surface">2,100 ev/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.991%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="financial">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="fingerprint" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Trader Identity &amp; KYC Webhook Bus</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_auth_kyc · v3.0.4</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>EU-Central-1 / LD4</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">                    <div className="flex items-center gap-2">                      <span className="font-mono font-bold text-on-surface">2.10ms</span></div></td>
                  <td className="py-4 px-4 font-mono text-on-surface">340 req/min</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">99.980%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
                <tr className="hover:bg-surface-container-low/40 transition-colors" data-service="enclave">
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0"><MsIcon name="dns" className="text-[18px]" /></div>
                      <div>
                        <div className="font-bold text-on-surface text-sm">Global Edge DNS &amp; Anycast Routing</div>
                        <div className="font-mono text-[11px] text-on-surface-variant">mod_edge_anycast · v1.1.2</div>
                      </div>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface-variant">
                    <div className="flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      <span>Cloudflare Enterprise Mesh</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-on-surface">0.28ms</span>
                      <span className="px-1.5 py-0.5 rounded text-[10px] bg-primary-fixed text-on-primary-fixed-variant font-mono">Ultra-low</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 font-mono text-on-surface">45,000 req/sec</td>
                  <td className="py-4 px-4 font-mono font-semibold text-primary">100.00%</td>
                  <td className="py-4 px-4">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Operational
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">                    <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface font-semibold transition-colors">                      Inspect →</button></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div className="rounded-xl bg-surface-container-lowest shadow-[0_4px_24px_rgba(46,50,48,0.04)] overflow-hidden" id="incidents-section">
          <div className="p-6 border-b border-surface-container flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h2 className="text-lg font-headline font-bold text-on-surface">Recent Incidents &amp; Maintenance Timeline</h2>
              <p className="text-xs text-on-surface-variant mt-0.5">Immutable audit record synced with WORM storage vault</p>
            </div>
            <div className="flex items-center gap-2 text-xs font-semibold">
              <button className="incident-filter-btn px-3 py-1.5 rounded-lg bg-surface-container font-bold text-on-surface">All Records</button>
              <button className="incident-filter-btn px-3 py-1.5 rounded-lg hover:bg-surface-container text-on-surface-variant">Active (1)</button>
              <button className="incident-filter-btn px-3 py-1.5 rounded-lg hover:bg-surface-container text-on-surface-variant">Resolved</button>
              <button className="incident-filter-btn px-3 py-1.5 rounded-lg hover:bg-surface-container text-on-surface-variant">Maintenance</button>
            </div>
          </div>
          <div className="p-6 space-y-6">
            <div className="flex items-start gap-4">
              <div className="w-9 h-9 rounded-full bg-error-container text-error flex items-center justify-center shrink-0 mt-0.5 shadow-sm"><MsIcon name="crisis_alert" className="text-[20px]" /></div>
              <div className="flex-1 space-y-1">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-error bg-error-container px-2 py-0.5 rounded">INC-8942</span>
                    <h3 className="font-bold text-sm text-on-surface">cTrader Bridge Jitter on Node US-EAST-02</h3>
                  </div>
                  <span className="font-mono text-xs text-on-surface-variant">Today, 13:58 UTC (42m ago)</span>
                </div>
                <p className="text-xs text-on-surface-variant leading-relaxed">                  Automated BGP rerouting triggered after node jitter exceeded 6.0ms threshold. Ingress traffic safely switched to London Equinix LD4 direct interconnect. Latency stabilized with zero tenant slippage. Root cause analysis underway with tier-1 transit carrier.</p>
                <div className="pt-1 flex items-center gap-3 text-[11px] font-mono">
                  <span className="text-error font-bold flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-error animate-ping"></span>
                    Status: Investigating / Mitigated
                  </span>
                  <span className="text-outline">·</span>
                  <span className="text-on-surface-variant">Assigned: SecOps On-Call (Marcus Vance)</span>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-9 h-9 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center shrink-0 mt-0.5 shadow-sm"><MsIcon name="build_circle" className="text-[20px]" /></div>
              <div className="flex-1 space-y-1">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-on-secondary-container bg-secondary-container px-2 py-0.5 rounded">MAINT-1049</span>
                    <h3 className="font-bold text-sm text-on-surface">AWS CloudHSM Sovereign Enclave Security Patch</h3>
                  </div>
                  <span className="font-mono text-xs text-on-surface-variant">May 16, 2025 · 02:00 - 02:14 UTC</span>
                </div>
                <p className="text-xs text-on-surface-variant leading-relaxed">                  Firmware upgrade executed across redundant FIPS 140-3 Level 3 hardware security modules. Hot standby failover took 12ms. Zero impact to live cryptographic signing or ledger audit sink.</p>
                <div className="pt-1 flex items-center gap-3 text-[11px] font-mono">
                  <span className="text-primary font-bold flex items-center gap-1">
<MsIcon name="check_circle" className="text-[14px]" />
                    Status: Completed (0 Downtime)
                  </span>
                  <span className="text-outline">·</span>
                  <span className="text-on-surface-variant">Operator: Automated Terraform Mesh Pipeline</span>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-9 h-9 rounded-full bg-primary-fixed text-on-primary-fixed-variant flex items-center justify-center shrink-0 mt-0.5 shadow-sm"><MsIcon name="task_alt" className="text-[20px]" /></div>
              <div className="flex-1 space-y-1">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-on-surface-variant bg-surface-container px-2 py-0.5 rounded">INC-8931</span>
                    <h3 className="font-bold text-sm text-on-surface">PSP Webhook Ingestion Retries Spike</h3>
                  </div>
                  <span className="font-mono text-xs text-on-surface-variant">May 11, 2025 · 18:22 UTC</span>
                </div>
                <p className="text-xs text-on-surface-variant leading-relaxed">                  Third-party gateway rate-limited 4,200 checkout confirmations. SQS backpressure queues buffered incoming events with zero loss. Throttling ceiling adjusted with Stripe and 100% reconciliation completed within 6 minutes.</p>
                <div className="pt-1 flex items-center gap-3 text-[11px] font-mono">
                  <span className="text-primary font-bold">Status: Resolved</span>
                  <span className="text-outline">·</span>
                  <span className="text-on-surface-variant">Duration: 6m 14s</span>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-9 h-9 rounded-full bg-primary-fixed text-on-primary-fixed-variant flex items-center justify-center shrink-0 mt-0.5 shadow-sm"><MsIcon name="task_alt" className="text-[20px]" /></div>
              <div className="flex-1 space-y-1">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-on-surface-variant bg-surface-container px-2 py-0.5 rounded">INC-8910</span>
                    <h3 className="font-bold text-sm text-on-surface">FIX Protocol Session Refresh Tag 35=2</h3>
                  </div>
                  <span className="font-mono text-xs text-on-surface-variant">May 04, 2025 · 07:11 UTC</span>
                </div>
                <p className="text-xs text-on-surface-variant leading-relaxed">                  Broker Liquidity Provider LP-03 triggered an unexpected sequence gap. QuickFIX session re-synced state in 180ms without interrupting active order routing execution.</p>
                <div className="pt-1 flex items-center gap-3 text-[11px] font-mono">
                  <span className="text-primary font-bold">Status: Resolved</span>
                  <span className="text-outline">·</span>
                  <span className="text-on-surface-variant">Duration: 180ms</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="pt-4 border-t border-outline-variant/30 flex flex-col md:flex-row md:items-center justify-between gap-4 text-xs text-on-surface-variant">
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-semibold text-on-surface">TerraDesk PFaaS Global Service Mesh</span>
            <span className="text-outline">·</span>
            <span className="font-mono">Cluster Hash: <strong className="text-on-surface">0x9f4a...881c</strong></span>
            <span className="text-outline">·</span>
            <span className="font-mono">PTP IEEE 1588v2 Precision Clocks Synced</span>
          </div>
          <div className="flex items-center gap-3 font-mono text-[11px]">
            <span className="flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              <span>24/7/365 Sovereign SOC Active</span>
            </span>
            <span className="text-outline">·</span>
            <span>3 Regions: LD4 / NY4 / TY3</span>
          </div>
        </div>
      </div>
      {so0 && (
        <>
        <div className="fixed inset-0 top-16 left-72 bg-inverse-surface/40 backdrop-blur-sm z-50 flex justify-end transition-opacity duration-300" id="drawerBackdrop">
          <div className="w-full max-w-[660px] h-full bg-surface-container-lowest shadow-2xl flex flex-col justify-between overflow-hidden relative" id="incidentDrawer">
            <div className="px-7 py-5 bg-surface-container-low flex items-start justify-between shadow-sm shrink-0">
              <div className="flex flex-col gap-1.5">
                <div className="flex items-center gap-2.5">
                  <span className="font-mono text-base font-bold text-on-surface">INC-8942</span>
                  <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-error text-on-error uppercase tracking-wide flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse"></span>
                    High Jitter / BGP Reroute
                  </span>
                </div>
                <div className="flex items-center gap-3 text-xs text-tsc">
                  <span className="flex items-center gap-1"><MsIcon name="schedule" className="text-[14px]" /> Today, 13:58 UTC <strong className="text-on-surface font-semibold font-body">(42m ago)</strong></span>
                  <span>•</span>
                  <span className="flex items-center gap-1"><MsIcon name="badge" className="text-[14px]" /> Marcus Vance (L5 Arch)</span>
                </div>
              </div>
              <button className="w-8 h-8 rounded-full bg-surface-container hover:bg-surface-container-high text-on-surface-variant hover:text-on-surface flex items-center justify-center transition-colors" id="closeDrawerBtn" onClick={() => setSo0(false)}><MsIcon name="close" className="text-[20px]" /></button>
            </div>
            <div className="flex-1 overflow-y-auto px-7 py-6 space-y-6">
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="font-headline font-semibold text-sm text-on-surface flex items-center gap-2">
<MsIcon name="troubleshoot" className="text-primary text-[18px]" />
                    Impact Assessment &amp; Scope
                  </h4>
                  <span className="px-2 py-0.5 rounded bg-tertiary-container/30 text-on-tertiary-container font-mono text-[11px] font-bold">Severity: L2 Warning</span>
                </div>
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="bg-surface-container p-3 rounded-lg">
                    <span className="text-[10px] uppercase font-bold text-tsc tracking-wider block">Target Node</span>
                    <span className="font-mono font-bold text-error text-sm mt-0.5 block">US-EAST-02</span>
                    <span className="text-tsc text-[11px]">Secaucus NY4 Enclave</span>
                  </div>
                  <div className="bg-surface-container p-3 rounded-lg">
                    <span className="text-[10px] uppercase font-bold text-tsc tracking-wider block">Active Service</span>
                    <span className="font-mono font-semibold text-on-surface text-sm mt-0.5 block">mod_fix_ctrader</span>
                    <span className="text-tsc text-[11px]">Subsystem v2.1.0-p4</span>
                  </div>
                  <div className="bg-surface-container p-3 rounded-lg">
                    <span className="text-[10px] uppercase font-bold text-tsc tracking-wider block">Latency Anomaly</span>
                    <span className="font-mono font-bold text-error text-sm mt-0.5 block">+8.42ms Jitter</span>
                    <span className="text-tsc text-[11px]">9.54ms (Baseline: 1.12ms)</span>
                  </div>
                  <div className="bg-surface-container p-3 rounded-lg">
                    <span className="text-[10px] uppercase font-bold text-tsc tracking-wider block">Order Integrity</span>
                    <span className="font-mono font-bold text-primary text-sm mt-0.5 block">0 Dropped Orders</span>
                    <span className="text-tsc text-[11px]">Buffer: 1,820 msg/sec</span>
                  </div>
                </div>
                <div className="p-3 rounded-lg bg-surface-container flex items-start gap-2.5">
<MsIcon name="alt_route" className="text-primary text-[18px] shrink-0 mt-0.5" />
                  <div className="text-xs">
                    <span className="font-bold text-on-surface">Failover Route Warm &amp; Ready:</span>
                    <p className="text-on-surface-variant mt-0.5 leading-relaxed">London Equinix LD4 direct fiber interconnect calibrated at 41.2ms transatlantic RTT. Automatic mirror sync healthy.</p>
                  </div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="font-headline font-semibold text-sm text-on-surface flex items-center gap-2">
<MsIcon name="timeline" className="text-tertiary text-[18px]" />
                    Live Telemetry: Latency Step Metric
                  </h4>
                  <span className="text-[11px] font-mono text-tsc">Sampling: 1s intervals</span>
                </div>
                <div className="w-full bg-surface-container p-4 rounded-xl flex flex-col gap-3">
                  <div className="w-full h-32 flex items-end">
                    <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 540 120">
                      <defs>
                        <linearGradient id="latencyGradient" x1="0%" x2="0%" y1="0%" y2="100%">
                          <stop offset="0%" stopColor="#b83230" stopOpacity={0.25}></stop>
                          <stop offset="100%" stopColor="#b83230" stopOpacity={0.0}></stop>
                        </linearGradient>
                      </defs>
                      <line stroke="#c4c8bc" strokeDasharray="3 3" strokeWidth={1} x1={0} x2={540} y1={105} y2={105}></line>
                      <text fill="#6b6358" fontFamily="monospace" fontSize={9} x={5} y={100}>1.12ms SLA baseline</text>
                      <line opacity={0.6} stroke="#b83230" strokeDasharray="2 2" strokeWidth={1} x1={280} x2={280} y1={0} y2={120}></line>
                      <text fill="#b83230" fontFamily="monospace" fontSize={9} fontWeight="bold" x={285} y={15}>13:42 UTC BGP Flap</text>
                      <path d="M 0 105 L 80 105 L 140 106 L 200 105 L 260 104 L 280 105 L 280 24 L 330 20 L 370 26 L 420 18 L 470 22 L 540 20 L 540 120 L 0 120 Z" fill="url(#latencyGradient)"></path>
                      <path d="M 0 105 L 80 105 L 140 106 L 200 105 L 260 104 L 280 105 L 280 24 L 330 20 L 370 26 L 420 18 L 470 22 L 540 20" fill="none" stroke="#b83230" strokeLinecap="round" strokeWidth={2.5}></path>
                      <circle cx={280} cy={24} fill="#b83230" r={4}></circle>
                      <circle className="animate-ping" cx={540} cy={20} fill="#b83230" r={4}></circle>
                      <circle cx={540} cy={20} fill="#b83230" r={3}></circle>
                    </svg>
                  </div>
                  <div className="flex items-center justify-between text-[11px] font-mono text-tsc pt-1 border-t border-surface-container-high/60">
                    <span>13:30 UTC</span>
                    <span>13:42 UTC (Anomaly)</span>
                    <span>14:00 UTC</span>
                    <span className="text-error font-bold">Current: 9.54ms</span>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3 text-xs pt-1">
                  <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container">
                    <span className="text-tsc font-medium">Packet Loss:</span>
                    <span className="font-mono font-bold text-on-surface">0.002% (Nominal)</span>
                  </div>
                  <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container">
                    <span className="text-tsc font-medium">Queue Buffer:</span>
                    <span className="font-mono font-bold text-primary">Holding (No backlog)</span>
                  </div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-3">
                <h4 className="font-headline font-semibold text-sm text-on-surface flex items-center gap-2">
<MsIcon name="verified" className="text-tsc text-[18px]" />
                  Root Cause &amp; Diagnostic Runbook
                </h4>
                <p className="text-xs text-on-surface-variant leading-relaxed">
                  Telemetry confirms an upstream transatlantic BGP flapping event between CenturyLink transit and NY4 cross-connect. 
            Automated internal TCP window scale dampened immediate disconnects, but order transit jitter breaches institutional HFT guarantee (&lt;2.5ms).
                </p>
                <div className="bg-surface-container p-3 rounded-lg text-xs space-y-1.5 font-mono text-tsc">
                  <div className="text-on-surface font-semibold">Automated Runbook Actions:</div>
                  <div>[13:42:04] • BGP route flap detected on AS3356 transit</div>
                  <div>[13:42:19] • Equinix LD4 backup fiber bridge armed in hot standby</div>
                  <div>[13:43:01] • Super-admin intervention required for physical node isolation</div>
                </div>
              </div>
              <div className="bg-surface-container-low rounded-xl p-5 shadow-sm space-y-4">
                <h4 className="font-headline font-semibold text-sm text-on-surface flex items-center gap-2">
<MsIcon name="tune" className="text-primary text-[18px]" />
                  Actions &amp; Failover Controls
                </h4>
                <div className="space-y-2.5">
                  <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container hover:bg-surface-container-high/80 cursor-pointer transition-colors">
<input defaultChecked className="mt-0.5 text-primary focus:ring-primary focus:ring-offset-0" name="failover_action" type="radio" defaultValue="isolate" />
                    <div className="text-xs">
                      <span className="font-bold text-on-surface block">Bypass Node &amp; Isolate US-EAST-02 (Recommended)</span>
                      <span className="text-tsc">Drains NY4 inbound sessions, routes all cTrader order flow through London LD4 bridge.</span>
                    </div>
                  </label>
                  <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container hover:bg-surface-container-high/80 cursor-pointer transition-colors">
<input className="mt-0.5 text-primary focus:ring-primary focus:ring-offset-0" name="failover_action" type="radio" defaultValue="resync" />
                    <div className="text-xs">
                      <span className="font-bold text-on-surface block">Force Re-sync BGP Session</span>
                      <span className="text-tsc">Sends soft reset to upstream peer router. May cause 200ms brief micro-drop.</span>
                    </div>
                  </label>
                  <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container hover:bg-surface-container-high/80 cursor-pointer transition-colors">
<input className="mt-0.5 text-primary focus:ring-primary focus:ring-offset-0" name="failover_action" type="radio" defaultValue="rebalance" />
                    <div className="text-xs">
                      <span className="font-bold text-on-surface block">Rebalance Traffic to Tokyo TY3 Enclave</span>
                      <span className="text-tsc">Shifts load across transpacific route (+12ms expected baseline latency).</span>
                    </div>
                  </label>
                </div>
                <div className="pt-1">
                  <label className="flex items-center gap-2.5 cursor-pointer text-xs text-on-surface">
<input defaultChecked className="rounded text-primary focus:ring-primary focus:ring-offset-0" type="checkbox" />
                    <span>Broadcast maintenance notice to affected cTrader prop firms <strong className="font-semibold text-primary">(3 institutional tenants)</strong></span>
                  </label>
                </div>
                <div className="space-y-1.5 pt-1">
                  <label className="text-[11px] uppercase tracking-wider font-bold text-tsc">Institutional Audit Note</label>
<textarea className="w-full bg-surface-container rounded-xl p-3 text-xs text-on-surface focus:outline-none focus:ring-1 focus:ring-primary resize-none" rows={2} defaultValue="Automated failover stable. Engineering war-room reviewing upstream carrier peering logs prior to full drain." />
                </div>
              </div>
            </div>
            <div className="px-7 py-4 bg-surface-container-low shadow-[0_-2px_12px_rgba(46,50,48,0.05)] flex flex-col gap-3 shrink-0">
              <div className="flex items-center justify-between text-[11px] text-tsc font-mono">
                <span className="flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-primary"></span>
                  SEC Rule 17a-4 Cryptographic Proof:
                </span>
                <span className="font-bold text-on-surface">#0x8f2d...91c4</span>
              </div>
              <div className="flex items-center justify-end gap-3 pt-1">
                <button className="px-4 py-2.5 rounded-xl bg-surface-container hover:bg-surface-container-high text-xs font-semibold text-on-surface transition-colors" id="cancelDrawerBtn" onClick={() => setSo0(false)}>                  Close Drawer</button>
                <button className="px-5 py-2.5 rounded-xl bg-error hover:bg-error/90 text-on-error text-xs font-bold shadow-md hover:shadow-lg transition-all flex items-center gap-1.5" id="executeBtn">
                  <span>Authorize Failover &amp; Isolate Node</span>
<MsIcon name="bolt" className="text-[16px]" />
                </button>
              </div>
            </div>
          </div>
        </div>
        </>
      )}
      {so1 && (
        <>
        <div className="fixed inset-0 top-16 left-72 bg-inverse-surface/45 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto">
          <div className="relative w-full max-w-[730px] my-auto bg-surface-container-lowest text-on-surface rounded-2xl shadow-[0_12px_48px_rgba(46,50,48,0.18)] overflow-hidden transition-all duration-200">
            <div className="h-1.5 w-full bg-gradient-to-r from-primary via-primary-container to-tertiary-container"></div>
            <div className="px-7 pt-6 pb-4 bg-surface-container-low/70 flex items-start justify-between gap-4">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-2xl bg-primary text-on-primary flex items-center justify-center shadow-md shrink-0"><MsIcon name="shield_with_heart" className="text-[26px]" /></div>
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold font-mono tracking-widest text-primary uppercase bg-primary-fixed/60 px-2 py-0.5 rounded-full">Automated Chaos Protocol</span>
                    <span className="text-[11px] font-mono text-tsc">ISO-22301 / FINRA Compliant</span>
                  </div>
                  <h2 className="font-headline text-xl lg:text-2xl font-bold text-on-surface tracking-tight">Simulate Automated Disaster Recovery &amp; Chaos Drill</h2>
                  <p className="text-xs text-on-surface-variant leading-relaxed">                    Inject controlled latency, isolate microservice enclaves, or simulate cross-region cloud failover to validate SLA continuity.</p>
                </div>
              </div>
              <button aria-label="Close modal" className="w-8 h-8 rounded-xl bg-surface-container text-on-surface-variant hover:text-on-surface hover:bg-surface-container-high transition-colors flex items-center justify-center shrink-0" id="closeModalBtn" onClick={() => setSo1(false)}><MsIcon name="close" className="text-[20px]" /></button>
            </div>
            <div className="px-7 py-5 space-y-6 max-h-[calc(88vh-180px)] overflow-y-auto">
              <div className="space-y-2.5">
                <div className="flex items-center justify-between">
                  <label className="font-headline text-sm font-bold text-on-surface flex items-center gap-1.5">
                    <span>1. Drill Scenario Architecture</span>
                    <span className="text-primary text-xs">*</span>
                  </label>
                  <span className="text-[11px] text-tsc font-mono">Select simulated fault</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <label className="cursor-pointer group relative rounded-xl p-3.5 bg-secondary-fixed/50 hover:bg-secondary-fixed text-on-surface transition-all flex flex-col justify-between">
<input defaultChecked className="sr-only peer" name="drill_scenario" type="radio" defaultValue="peering_sever" />
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="w-8 h-8 rounded-lg bg-primary text-on-primary flex items-center justify-center shadow-xs"><MsIcon name="cable" className="text-[18px]" /></div>
                        <span className="w-5 h-5 rounded-full bg-primary text-on-primary flex items-center justify-center peer-checked:opacity-100 opacity-0 group-[.peer:checked]:opacity-100"><MsIcon name="check" className="text-[13px]" /></span>
                      </div>
                      <h4 className="font-headline font-bold text-xs text-on-surface leading-tight">Transatlantic Peering Sever</h4>
                      <p className="text-[11px] text-on-surface-variant leading-snug">Simulates LD4 ↔ NY4 fiber cut, forces automated BGP failover to backup dark fiber.</p>
                    </div>
                    <div className="mt-3 pt-2 bg-surface-container-high/40 rounded px-2 py-1 flex items-center justify-between text-[10px] font-mono text-tsc">
                      <span>Target Impact</span>
                      <span className="text-primary font-semibold">Optical Latency</span>
                    </div>
                    <div className="absolute inset-0 rounded-xl bg-primary/10 pointer-events-none opacity-100"></div>
                  </label>
                  <label className="cursor-pointer group relative rounded-xl p-3.5 bg-surface-container-low hover:bg-surface-container text-on-surface transition-all flex flex-col justify-between">
<input className="sr-only peer" name="drill_scenario" type="radio" defaultValue="key_rotation" />
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="w-8 h-8 rounded-lg bg-surface-container-high text-tsc flex items-center justify-center"><MsIcon name="key" className="text-[18px]" /></div>
                        <span className="w-5 h-5 rounded-full bg-surface-container-high text-tsc flex items-center justify-center opacity-40"><MsIcon name="check" className="text-[13px]" /></span>
                      </div>
                      <h4 className="font-headline font-bold text-xs text-on-surface leading-tight">Nitro Key Rotation Outage</h4>
                      <p className="text-[11px] text-on-surface-variant leading-snug">Tests HSM hardware signature fallback to secondary CloudHSM multi-tier vault.</p>
                    </div>
                    <div className="mt-3 pt-2 bg-surface-container-high/40 rounded px-2 py-1 flex items-center justify-between text-[10px] font-mono text-tsc">
                      <span>Target Impact</span>
                      <span className="text-tertiary font-semibold">HSM Fallback</span>
                    </div>
                  </label>
                  <label className="cursor-pointer group relative rounded-xl p-3.5 bg-surface-container-low hover:bg-surface-container text-on-surface transition-all flex flex-col justify-between">
<input className="sr-only peer" name="drill_scenario" type="radio" defaultValue="hft_spike" />
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="w-8 h-8 rounded-lg bg-surface-container-high text-tsc flex items-center justify-center"><MsIcon name="show_chart" className="text-[18px]" /></div>
                        <span className="w-5 h-5 rounded-full bg-surface-container-high text-tsc flex items-center justify-center opacity-40"><MsIcon name="check" className="text-[13px]" /></span>
                      </div>
                      <h4 className="font-headline font-bold text-xs text-on-surface leading-tight">HFT Execution Surge</h4>
                      <p className="text-[11px] text-on-surface-variant leading-snug">Stress tests zero-copy ring buffers under artificial 50k ops/sec synthetic load.</p>
                    </div>
                    <div className="mt-3 pt-2 bg-surface-container-high/40 rounded px-2 py-1 flex items-center justify-between text-[10px] font-mono text-tsc">
                      <span>Target Impact</span>
                      <span className="text-on-surface font-semibold">50,000 req/s</span>
                    </div>
                  </label>
                </div>
              </div>
              <div className="space-y-3.5 pt-1">
                <div className="flex items-center justify-between">
                  <label className="font-headline text-sm font-bold text-on-surface">2. Target Enclave Scope &amp; Microservices</label>
                  <span className="text-[11px] text-tsc font-mono">Isolated blast radius</span>
                </div>
                <div className="space-y-1.5">
                  <span className="text-xs font-semibold text-tsc">Target Data Center Region:</span>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                    <button className="px-3 py-2 rounded-xl text-xs font-medium text-on-surface-variant bg-surface-container-low hover:bg-surface-container transition-colors flex items-center justify-center gap-1.5" type="button" onClick={() => setSo1(false)}>                      <span>All Regions</span></button>
                    <button className="px-3 py-2 rounded-xl text-xs font-medium text-on-surface-variant bg-surface-container-low hover:bg-surface-container transition-colors flex items-center justify-center gap-1.5" type="button">
                      <span className="w-1.5 h-1.5 rounded-full bg-tsc"></span>
                      <span>London LD4</span>
                    </button>
                    <button className="px-3 py-2 rounded-xl text-xs font-bold text-on-surface bg-primary-container/70 shadow-sm flex items-center justify-center gap-1.5" type="button">
                      <span className="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
                      <span>New York NY4</span>
<MsIcon name="check_circle" className="text-[14px] text-primary" />
                    </button>
                    <button className="px-3 py-2 rounded-xl text-xs font-medium text-on-surface-variant bg-surface-container-low hover:bg-surface-container transition-colors flex items-center justify-center gap-1.5" type="button">
                      <span className="w-1.5 h-1.5 rounded-full bg-tsc"></span>
                      <span>Tokyo TY3</span>
                    </button>
                  </div>
                </div>
                <div className="space-y-1.5 pt-1">
                  <span className="text-xs font-semibold text-tsc">Target Microservices for Isolation:</span>
                  <div className="flex flex-wrap gap-2">
                    <label className="cursor-pointer inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-surface-container-low text-xs font-mono font-medium text-on-surface hover:bg-surface-container">
<input className="rounded text-primary focus:ring-primary accent-primary" type="checkbox" />
                      <span>mod_trading_core</span>
                    </label>
                    <label className="cursor-pointer inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-primary-container text-xs font-mono font-bold text-on-surface shadow-xs">
<input defaultChecked className="rounded text-primary focus:ring-primary accent-primary" type="checkbox" />
                      <span>mod_fix_ctrader</span>
                      <span className="text-[10px] bg-primary text-on-primary px-1.5 py-0.2 rounded font-sans font-semibold">Active Target</span>
                    </label>
                    <label className="cursor-pointer inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-surface-container-low text-xs font-mono font-medium text-on-surface hover:bg-surface-container">
<input className="rounded text-primary focus:ring-primary accent-primary" type="checkbox" />
                      <span>mod_psp_gateway</span>
                    </label>
                    <label className="cursor-pointer inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-surface-container-low text-xs font-mono font-medium text-on-surface hover:bg-surface-container">
<input className="rounded text-primary focus:ring-primary accent-primary" type="checkbox" />
                      <span>mod_order_book_l2</span>
                    </label>
                  </div>
                </div>
              </div>
              <div className="space-y-3.5 pt-1">
                <div className="flex items-center justify-between">
                  <label className="font-headline text-sm font-bold text-on-surface">3. Blast Radius &amp; Automated Circuit Breakers</label>
                  <span className="text-[11px] text-primary font-bold">Safeguards Armed</span>
                </div>
                <div className="bg-surface-container-low p-3.5 rounded-xl space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-semibold text-tsc">Synthetic Fault Injection Duration:</span>
                    <span className="font-mono font-bold text-primary">60 Seconds Window</span>
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    <button className="py-2 px-3 rounded-lg text-xs font-bold bg-primary text-on-primary shadow-xs flex items-center justify-center gap-1" type="button">
<MsIcon name="timer" className="text-[15px]" />
                      <span>60 Seconds [Armed]</span>
                    </button>
                    <button className="py-2 px-3 rounded-lg text-xs font-medium bg-surface-container text-on-surface-variant hover:text-on-surface flex items-center justify-center gap-1" type="button">
<MsIcon name="timer" className="text-[15px]" />
                      <span>5 Minutes</span>
                    </button>
                    <button className="py-2 px-3 rounded-lg text-xs font-medium bg-surface-container text-on-surface-variant hover:text-on-surface flex items-center justify-center gap-1" type="button">
<MsIcon name="timer" className="text-[15px]" />
                      <span>15 Minutes</span>
                    </button>
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container-low hover:bg-surface-container transition-colors cursor-pointer">
                    <div className="pt-0.5"><input defaultChecked className="w-4 h-4 rounded text-primary accent-primary cursor-pointer" type="checkbox" /></div>
                    <div className="flex-1">
                      <p className="text-xs font-bold text-on-surface flex items-center gap-1.5">
<MsIcon name="shield" className="text-primary text-[16px]" />
                        <span>Safety Cutoff: Instant Abort if Live Client Slippage exceeds 0.5 pips</span>
                      </p>
                      <p className="text-[11px] text-on-surface-variant leading-snug mt-0.5">                        Immediately resets BGP routes and rolls back socket enclaves if simulated stress bleeds into live execution pipelines.</p>
                    </div>
                  </label>
                  <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container-low hover:bg-surface-container transition-colors cursor-pointer">
                    <div className="pt-0.5"><input defaultChecked className="w-4 h-4 rounded text-primary accent-primary cursor-pointer" type="checkbox" /></div>
                    <div className="flex-1">
                      <p className="text-xs font-bold text-on-surface flex items-center gap-1.5">
<MsIcon name="lock" className="text-primary text-[16px]" />
                        <span>Sandbox Isolation: Route mock synthetic trades only; live tenant orders completely ring-fenced</span>
                      </p>
                      <p className="text-[11px] text-on-surface-variant leading-snug mt-0.5">                        Production data channels remain physically walled off via zero-trust eBPF micro-segmentation.</p>
                    </div>
                  </label>
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-secondary-container/70 flex items-start gap-3">
<MsIcon name="gavel" className="text-tertiary text-[20px] shrink-0 mt-0.5" />
                <div className="space-y-0.5">
                  <span className="text-xs font-bold text-on-secondary-container">Level-4 Quorum &amp; Regulatory Logging Notice</span>
                  <p className="text-[11px] text-on-surface-variant leading-relaxed">                    Simulated drills in production fabrics require Level-4 Quorum attestation. The drill results, socket latency telemetry, and failover timestamps will be automatically logged to WORM immutable storage (SEC 17a-4 compliant).</p>
                </div>
              </div>
            </div>
            <div className="px-7 py-4 bg-surface-container-low flex flex-col sm:flex-row items-center justify-between gap-3 shadow-inner">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-primary animate-ping"></span>
                <span className="text-xs font-mono text-tsc">Estimated Failover Time:</span>
                <span className="px-2 py-0.5 rounded-md text-xs font-mono font-bold bg-surface-container-high text-primary">&lt; 120ms MTTR</span>
              </div>
              <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
                <button className="px-4 py-2.5 rounded-xl text-xs font-bold text-on-surface bg-surface-container hover:bg-surface-container-high transition-colors" id="cancelModalBtn" type="button" onClick={() => setSo1(false)}>                  Cancel / Abort</button>
                <button className="px-5 py-2.5 rounded-xl text-xs font-bold text-on-primary bg-primary hover:bg-primary/90 shadow-md flex items-center gap-1.5 transition-transform active:scale-95" type="button" onClick={() => setSo1(false)}>
                  <span>Arm &amp; Execute Simulated Drill</span>
                  <span className="text-sm">⚡</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        </>
      )}
    </>
  );
}
