/**
 * Stitch Module — manifest, navigation, routes.
 *
 * PFaaS prop-admin module for screens converted from stitch_screens
 * reference renders. Optional module; depends on trading.
 */

import {  Monitor, BookOpen, Settings, BarChart3, Wallet, Shield, Users, Tag, Bell, MessageSquare, FileText, Link, Bot, Brain, CreditCard, ArrowLeftRight, MapPin, Clock, Target, Trophy, AlertTriangle, Command, LayoutList, Image, Building2, LogIn, FileCheck, RefreshCw, Download, Share2, MoreHorizontal, Plus, Edit2, Trash2, Check, X, Search, Filter, ChevronRight, Menu, DollarSign, History, ShoppingBag, Sun, GitBranch, Flag, Activity, Calendar, Globe, TrendingDown , Contact, Key, Lightbulb, Mail, Megaphone, Ticket, TrendingUp, Upload } from "lucide-react";
import type { FrontendModule, NavigationItem, RouteDefinition } from "@/lib/platform/types";

const navigation: NavigationItem[] = [
  {
    id: "stitch",
    label: "Stitch",
    icon: Monitor,
    order: 90,
    children: [
      { id: "stitch.overview", label: "Overview", href: "overview", icon: BookOpen },
      { id: "stitch.profile", label: "Profile", href: "profile", icon: Users },
      { id: "stitch.audit", label: "Audit Log", href: "audit", icon: Shield },
      { id: "stitch.notifications", label: "Notifications", href: "notifications", icon: Bell },
      { id: "stitch.help", label: "Help", href: "help", icon: BookOpen },
      { id: "stitch.settings", label: "Settings", href: "settings", icon: Settings },
      { id: "stitch.pending-tasks", label: "Pending Tasks", href: "pending-tasks", icon: Clock },
      { id: "stitch.accounting", label: "Accounting", href: "accounting", icon: BookOpen },
      { id: "stitch.accounting-transactions", label: "Transactions", href: "accounting-transactions", icon: ArrowLeftRight },
      { id: "stitch.accounting-reconciliation", label: "Reconciliation", href: "accounting-reconciliation", icon: ArrowLeftRight },
      { id: "stitch.accounting-invoices", label: "Invoices", href: "accounting-invoices", icon: FileText },
      { id: "stitch.accounting-pl", label: "P&L Statement", href: "accounting-pl", icon: BarChart3 },
      { id: "stitch.challenges", label: "Challenges", href: "challenges", icon: Target },
      { id: "stitch.challenges-active", label: "Active", href: "challenges-active", icon: Trophy },
      { id: "stitch.challenges-passed", label: "Passed", href: "challenges-passed", icon: Check },
      { id: "stitch.challenges-failed", label: "Failed", href: "challenges-failed", icon: X },
      { id: "stitch.challenge-wizard", label: "Challenge Wizard", href: "challenge-wizard", icon: Flag },
      { id: "stitch.challenge-config", label: "Challenge Config", href: "challenge-config", icon: Settings },
      { id: "stitch.challenge-types", label: "Challenge Types", href: "challenge-types", icon: Tag },
      { id: "stitch.challenge-marketplace-preview", label: "Marketplace Preview", href: "challenge-marketplace-preview", icon: Share2 },
      { id: "stitch.challenge-comparison", label: "Challenge Comparison", href: "challenge-comparison", icon: BarChart3 },
      { id: "stitch.challenge-analytics", label: "Challenge Analytics", href: "challenge-analytics", icon: BarChart3 },
      { id: "stitch.phase-migration-tool", label: "Phase Migration", href: "phase-migration-tool", icon: GitBranch },
      { id: "stitch.bulk-phase-editor", label: "Bulk Phase Editor", href: "bulk-phase-editor", icon: Edit2 },
      { id: "stitch.competitions", label: "Competitions", href: "competitions", icon: Trophy },
      { id: "stitch.challenge-marketplace", label: "Marketplace", href: "challenge-marketplace", icon: Share2 },
      { id: "stitch.checkout", label: "Checkout", href: "checkout", icon: CreditCard },
      { id: "stitch.purchase-completed", label: "Purchase Completed", href: "purchase-completed", icon: Check },
      { id: "stitch.phase-management", label: "Phase Management", href: "phase-management", icon: GitBranch },
      { id: "stitch.challenge-edit", label: "Challenge Edit", href: "challenge-edit", icon: Edit2 },
      { id: "stitch.phase-detail", label: "Phase Detail", href: "phase-detail", icon: FileText },
      { id: "stitch.risk", label: "Risk", href: "risk", icon: Shield },
      { id: "stitch.breaches", label: "Breaches", href: "breaches", icon: AlertTriangle },
      { id: "stitch.risk-cases", label: "Risk Cases", href: "risk-cases", icon: FileText },
      { id: "stitch.risk-statistics", label: "Risk Statistics", href: "risk-statistics", icon: BarChart3 },
      { id: "stitch.trading-events", label: "Trading Events", href: "trading-events", icon: Activity },
      { id: "stitch.copy-trading-events", label: "Copy Trading Events", href: "copy-trading-events", icon: RefreshCw },
      { id: "stitch.copy-trading-analysis", label: "Copy Trading Analysis", href: "copy-trading-analysis", icon: BarChart3 },
      { id: "stitch.inverse-trading-events", label: "Inverse Events", href: "inverse-trading-events", icon: RefreshCw },
      { id: "stitch.account-ip-addresses", label: "IP Addresses", href: "account-ip-addresses", icon: MapPin },
      { id: "stitch.weekend-trades", label: "Weekend Trades", href: "weekend-trades", icon: Calendar },
      { id: "stitch.risk-unprofitable-countries", label: "Unprofitable Countries", href: "risk-unprofitable-countries", icon: Globe },
      { id: "stitch.risk-revenue-loss", label: "Revenue Loss", href: "risk-revenue-loss", icon: TrendingDown },
      { id: "stitch.risk-label-vs-payouts", label: "Label vs Payouts", href: "risk-label-vs-payouts", icon: BarChart3 },
      { id: "stitch.risk-highest-earners", label: "Highest Earners", href: "risk-highest-earners", icon: BarChart3 },
      { id: "stitch.risk-group-vs-payouts", label: "Group vs Payouts", href: "risk-group-vs-payouts", icon: BarChart3 },
      { id: "stitch.risk-coupon-vs-payouts", label: "Coupon vs Payouts", href: "risk-coupon-vs-payouts", icon: Tag },
      { id: "stitch.risk-account-label-analysis", label: "Label Analysis", href: "risk-account-label-analysis", icon: Tag },
      { id: "stitch.risk-addon-revenue", label: "Addon Revenue", href: "risk-addon-revenue", icon: DollarSign },
      { id: "stitch.payouts", label: "Payouts", href: "payouts", icon: Wallet },
      { id: "stitch.payouts-pending", label: "Pending", href: "payouts-pending", icon: Clock },
      { id: "stitch.payouts-history", label: "History", href: "payouts-history", icon: History },
      { id: "stitch.payouts-enhanced-withdrawals", label: "Enhanced Withdrawals", href: "payouts-enhanced-withdrawals", icon: RefreshCw },
      { id: "stitch.payout-provider-status", label: "Provider Status", href: "payout-provider-status", icon: Check },
      { id: "stitch.payout-eligibility", label: "Eligibility", href: "payout-eligibility", icon: Check },
      { id: "stitch.payout-request", label: "Request", href: "payout-request", icon: Plus },
      { id: "stitch.analytics", label: "Analytics", href: "analytics", icon: BarChart3 },
      { id: "stitch.analytics-traders", label: "Trader Analytics", href: "analytics-traders", icon: Users },
      { id: "stitch.analytics-performance", label: "Performance", href: "analytics-performance", icon: TrendingUp },
      { id: "stitch.analytics-risk", label: "Risk Analytics", href: "analytics-risk", icon: Shield },
      { id: "stitch.analytics-advanced", label: "Advanced Analytics", href: "analytics-advanced", icon: Brain },
      { id: "stitch.reports", label: "Reports", href: "reports", icon: FileText },
      { id: "stitch.trader-performance", label: "Trader Performance", href: "trader-performance", icon: TrendingUp },
      { id: "stitch.analytics-firm-statistics", label: "Firm Statistics", href: "analytics-firm-statistics", icon: Building2 },
      { id: "stitch.analytics-daily-highlights", label: "Daily Highlights", href: "analytics-daily-highlights", icon: Sun },
      { id: "stitch.analytics-retention", label: "Retention", href: "analytics-retention", icon: RefreshCw },
      { id: "stitch.dashboard-accounts", label: "Dashboard Accounts", href: "dashboard-accounts", icon: Users },
      { id: "stitch.dashboard-payouts", label: "Dashboard Payouts", href: "dashboard-payouts", icon: Wallet },
      { id: "stitch.dashboard-orders", label: "Dashboard Orders", href: "dashboard-orders", icon: ShoppingBag },
      { id: "stitch.dashboard-positions", label: "Dashboard Positions", href: "dashboard-positions", icon: TrendingUp },
      { id: "stitch.affiliates", label: "Affiliates", href: "affiliates", icon: Tag },
      { id: "stitch.affiliates-list", label: "Affiliates List", href: "affiliates-list", icon: Users },
      { id: "stitch.affiliates-campaigns", label: "Campaigns", href: "affiliates-campaigns", icon: Tag },
      { id: "stitch.affiliates-commissions", label: "Commissions", href: "affiliates-commissions", icon: DollarSign },
      { id: "stitch.offer-management", label: "Offer Management", href: "offer-management", icon: Tag },
      { id: "stitch.offer-edit", label: "Offer Edit", href: "offer-edit", icon: Edit2 },
      { id: "stitch.offer-matching-users", label: "Matching Users", href: "offer-matching-users", icon: Users },
      { id: "stitch.offer-change-history", label: "Change History", href: "offer-change-history", icon: History },
      { id: "stitch.affiliate-coupons", label: "Coupons", href: "affiliate-coupons", icon: Tag },
      { id: "stitch.affiliate-link-tracking", label: "Link Tracking", href: "affiliate-link-tracking", icon: Link },
      { id: "stitch.accounting", label: "Accounting", href: "accounting", icon: BookOpen },
      { id: "stitch.accounting-transactions", label: "Transactions", href: "accounting-transactions", icon: ArrowLeftRight },
      { id: "stitch.accounting-reconciliation", label: "Reconciliation", href: "accounting-reconciliation", icon: ArrowLeftRight },
      { id: "stitch.accounting-invoices", label: "Invoices", href: "accounting-invoices", icon: FileText },
      { id: "stitch.accounting-pl", label: "P&L", href: "accounting-pl", icon: TrendingUp },
      { id: "stitch.marketing", label: "Marketing", href: "marketing", icon: Megaphone },
      { id: "stitch.marketing-campaigns", label: "Campaigns", href: "marketing-campaigns", icon: Tag },
      { id: "stitch.marketing-performance", label: "Performance", href: "marketing-performance", icon: TrendingUp },
      { id: "stitch.marketing-dashboard", label: "Dashboard", href: "marketing-dashboard", icon: BarChart3 },
      { id: "stitch.marketing-email-campaigns", label: "Email Campaigns", href: "marketing-email-campaigns", icon: Mail },
      { id: "stitch.marketing-ad-spend", label: "Ad Spend", href: "marketing-ad-spend", icon: CreditCard },
      { id: "stitch.crm", label: "CRM", href: "crm", icon: Contact },
      { id: "stitch.crm-contacts", label: "Contacts", href: "crm-contacts", icon: Users },
      { id: "stitch.crm-pipeline", label: "Pipeline", href: "crm-pipeline", icon: GitBranch },
      { id: "stitch.kyc", label: "KYC", href: "kyc", icon: Shield },
      { id: "stitch.kyc-reviews", label: "Reviews", href: "kyc-reviews", icon: FileCheck },
      { id: "stitch.kyc-risk", label: "KYC Risk", href: "kyc-risk", icon: AlertTriangle },
      { id: "stitch.kyc-document-requests", label: "Doc Requests", href: "kyc-document-requests", icon: FileText },
      { id: "stitch.kyc-onboarding", label: "Onboarding", href: "kyc-onboarding", icon: LogIn },
      { id: "stitch.kyc-status", label: "KYC Status", href: "kyc-status", icon: Check },
      { id: "stitch.support", label: "Support", href: "support", icon: MessageSquare },
      { id: "stitch.support-tickets", label: "Tickets", href: "support-tickets", icon: Ticket },
      { id: "stitch.support-knowledge", label: "Knowledge", href: "support-knowledge", icon: BookOpen },
      { id: "stitch.support-sla", label: "SLA", href: "support-sla", icon: Clock },
      { id: "stitch.ai", label: "AI", href: "ai", icon: Brain },
      { id: "stitch.ai-insights", label: "Insights", href: "ai-insights", icon: Lightbulb },
      { id: "stitch.ai-assistant", label: "Assistant", href: "ai-assistant", icon: Bot },
      { id: "stitch.ai-configure", label: "Configure", href: "ai-configure", icon: Settings },
      { id: "stitch.ai-predictive", label: "Predictive", href: "ai-predictive", icon: TrendingUp },
      { id: "stitch.ai-anomaly", label: "Anomaly", href: "ai-anomaly", icon: AlertTriangle },
      { id: "stitch.ai-cost", label: "Cost Tracking", href: "ai-cost", icon: DollarSign },
      { id: "stitch.audit-user-events", label: "User Events", href: "audit-user-events", icon: Activity },
      { id: "stitch.audit-change-history", label: "Change History", href: "audit-change-history", icon: History },
      { id: "stitch.audit-user-event-detail", label: "Event Detail", href: "audit-user-event-detail", icon: FileText },
      { id: "stitch.email-templates", label: "Email Templates", href: "email-templates", icon: Mail },
      { id: "stitch.certificate-management", label: "Certificate Mgmt", href: "certificate-management", icon: Shield },
      { id: "stitch.banner-management", label: "Banners", href: "banner-management", icon: Image },
      { id: "stitch.user-management", label: "User Mgmt", href: "user-management", icon: Users },
      { id: "stitch.group-management", label: "Groups", href: "group-management", icon: Users },
      { id: "stitch.token-management", label: "Tokens", href: "token-management", icon: Key },
      { id: "stitch.certificatesissued", label: "Issued Certs", href: "certificatesissued", icon: FileCheck },
      { id: "stitch.certificate-detail", label: "Cert Detail", href: "certificate-detail", icon: FileText },
      { id: "stitch.notifications-management", label: "Notif Mgmt", href: "notifications-management", icon: Bell },
      { id: "stitch.notification-edit", label: "Notif Edit", href: "notification-edit", icon: Edit2 },
      { id: "stitch.utilities", label: "Utilities", href: "utilities", icon: Settings },
      { id: "stitch.email-template-edit", label: "Email Template Edit", href: "email-template-edit", icon: Mail },
      { id: "stitch.certificate-template-designer", label: "Cert Template Designer", href: "certificate-template-designer", icon: FileText },
      { id: "stitch.certificate-font-upload", label: "Font Upload", href: "certificate-font-upload", icon: Upload },
      { id: "stitch.marketing-integrations", label: "Marketing Integrations", href: "marketing-integrations", icon: Link },
      { id: "stitch.marketing-banner-edit", label: "Banner Edit", href: "marketing-banner-edit", icon: Image },
      { id: "stitch.social-media-links", label: "Social Links", href: "social-media-links", icon: Share2 },
      { id: "stitch.device-activities", label: "Device Activities", href: "device-activities", icon: Monitor },
      { id: "stitch.token-detail", label: "Token Detail", href: "token-detail", icon: Key },
      { id: "stitch.audit-user-events-enhanced", label: "Enhanced Events", href: "audit-user-events-enhanced", icon: Activity },
      { id: "stitch.kyc-providers", label: "KYC Providers", href: "kyc-providers", icon: Shield },
      { id: "stitch.2fa-setup-dialog", label: "2FA Setup", href: "2fa-setup-dialog", icon: Shield },
    ],
  },
];

const routes: RouteDefinition[] = [
  { path: "overview", viewId: "overview", label: "Overview" },
  { path: "profile", viewId: "profile", label: "Profile" },
  { path: "audit", viewId: "audit", label: "Audit Log" },
  { path: "notifications", viewId: "notifications", label: "Notifications" },
  { path: "help", viewId: "help", label: "Help" },
  { path: "settings", viewId: "settings", label: "Settings" },
  { path: "pending-tasks", viewId: "pending-tasks", label: "Pending Tasks" },
  { path: "accounting", viewId: "accounting", label: "Accounting" },
  { path: "accounting-transactions", viewId: "accounting-transactions", label: "Transactions" },
  { path: "accounting-reconciliation", viewId: "accounting-reconciliation", label: "Reconciliation" },
  { path: "accounting-invoices", viewId: "accounting-invoices", label: "Invoices" },
  { path: "accounting-pl", viewId: "accounting-pl", label: "P&L" },
  { path: "challenges", viewId: "challenges", label: "Challenges" },
  { path: "challenges-active", viewId: "challenges-active", label: "Active" },
  { path: "challenges-passed", viewId: "challenges-passed", label: "Passed" },
  { path: "challenges-failed", viewId: "challenges-failed", label: "Failed" },
  { path: "challenge-wizard", viewId: "challenge-wizard", label: "Wizard" },
  { path: "challenge-config", viewId: "challenge-config", label: "Config" },
  { path: "challenge-types", viewId: "challenge-types", label: "Types" },
  { path: "challenge-marketplace-preview", viewId: "challenge-marketplace-preview", label: "Marketplace Preview" },
  { path: "challenge-comparison", viewId: "challenge-comparison", label: "Comparison" },
  { path: "challenge-analytics", viewId: "challenge-analytics", label: "Analytics" },
  { path: "phase-migration-tool", viewId: "phase-migration-tool", label: "Phase Migration" },
  { path: "bulk-phase-editor", viewId: "bulk-phase-editor", label: "Bulk Phase Editor" },
  { path: "competitions", viewId: "competitions", label: "Competitions" },
  { path: "challenge-marketplace", viewId: "challenge-marketplace", label: "Marketplace" },
  { path: "checkout", viewId: "checkout", label: "Checkout" },
  { path: "purchase-completed", viewId: "purchase-completed", label: "Purchase Completed" },
  { path: "phase-management", viewId: "phase-management", label: "Phase Management" },
  { path: "challenge-edit", viewId: "challenge-edit", label: "Challenge Edit" },
  { path: "phase-detail", viewId: "phase-detail", label: "Phase Detail" },
  { path: "risk", viewId: "risk", label: "Risk" },
  { path: "breaches", viewId: "breaches", label: "Breaches" },
  { path: "risk-cases", viewId: "risk-cases", label: "Risk Cases" },
  { path: "risk-statistics", viewId: "risk-statistics", label: "Risk Statistics" },
  { path: "trading-events", viewId: "trading-events", label: "Trading Events" },
  { path: "copy-trading-events", viewId: "copy-trading-events", label: "Copy Trading Events" },
  { path: "copy-trading-analysis", viewId: "copy-trading-analysis", label: "Copy Trading Analysis" },
  { path: "inverse-trading-events", viewId: "inverse-trading-events", label: "Inverse Events" },
  { path: "account-ip-addresses", viewId: "account-ip-addresses", label: "IP Addresses" },
  { path: "weekend-trades", viewId: "weekend-trades", label: "Weekend Trades" },
  { path: "risk-unprofitable-countries", viewId: "risk-unprofitable-countries", label: "Unprofitable Countries" },
  { path: "risk-revenue-loss", viewId: "risk-revenue-loss", label: "Revenue Loss" },
  { path: "risk-label-vs-payouts", viewId: "risk-label-vs-payouts", label: "Label vs Payouts" },
  { path: "risk-highest-earners", viewId: "risk-highest-earners", label: "Highest Earners" },
  { path: "risk-group-vs-payouts", viewId: "risk-group-vs-payouts", label: "Group vs Payouts" },
  { path: "risk-coupon-vs-payouts", viewId: "risk-coupon-vs-payouts", label: "Coupon vs Payouts" },
  { path: "risk-account-label-analysis", viewId: "risk-account-label-analysis", label: "Label Analysis" },
  { path: "risk-addon-revenue", viewId: "risk-addon-revenue", label: "Addon Revenue" },
  { path: "payouts", viewId: "payouts", label: "Payouts" },
  { path: "payouts-pending", viewId: "payouts-pending", label: "Pending" },
  { path: "payouts-history", viewId: "payouts-history", label: "History" },
  { path: "payouts-enhanced-withdrawals", viewId: "payouts-enhanced-withdrawals", label: "Enhanced Withdrawals" },
  { path: "payout-provider-status", viewId: "payout-provider-status", label: "Provider Status" },
  { path: "payout-eligibility", viewId: "payout-eligibility", label: "Eligibility" },
  { path: "payout-request", viewId: "payout-request", label: "Request" },
  { path: "analytics", viewId: "analytics", label: "Analytics" },
  { path: "analytics-traders", viewId: "analytics-traders", label: "Trader Analytics" },
  { path: "analytics-performance", viewId: "analytics-performance", label: "Performance" },
  { path: "analytics-risk", viewId: "analytics-risk", label: "Risk Analytics" },
  { path: "analytics-advanced", viewId: "analytics-advanced", label: "Advanced Analytics" },
  { path: "reports", viewId: "reports", label: "Reports" },
  { path: "certificatesissued", viewId: "certificatesissued", label: "Issued Certs" },
  { path: "challenges", viewId: "challenges", label: "Challenges" },
  { path: "competitions", viewId: "competitions", label: "Competitions" },
  { path: "help", viewId: "help", label: "Help" },
  { path: "trader-performance", viewId: "trader-performance", label: "Trader Performance" },
  { path: "analytics-firm-statistics", viewId: "analytics-firm-statistics", label: "Firm Statistics" },
  { path: "analytics-daily-highlights", viewId: "analytics-daily-highlights", label: "Daily Highlights" },
  { path: "analytics-retention", viewId: "analytics-retention", label: "Retention" },
  { path: "dashboard-accounts", viewId: "dashboard-accounts", label: "Dashboard Accounts" },
  { path: "dashboard-payouts", viewId: "dashboard-payouts", label: "Dashboard Payouts" },
  { path: "dashboard-orders", viewId: "dashboard-orders", label: "Dashboard Orders" },
  { path: "dashboard-positions", viewId: "dashboard-positions", label: "Dashboard Positions" },
  { path: "affiliates", viewId: "affiliates", label: "Affiliates" },
  { path: "affiliates-list", viewId: "affiliates-list", label: "Affiliates List" },
  { path: "affiliates-campaigns", viewId: "affiliates-campaigns", label: "Campaigns" },
  { path: "affiliates-commissions", viewId: "affiliates-commissions", label: "Commissions" },
  { path: "offer-management", viewId: "offer-management", label: "Offer Management" },
  { path: "offer-edit", viewId: "offer-edit", label: "Offer Edit" },
  { path: "offer-matching-users", viewId: "offer-matching-users", label: "Matching Users" },
  { path: "offer-change-history", viewId: "offer-change-history", label: "Change History" },
  { path: "affiliate-coupons", viewId: "affiliate-coupons", label: "Coupons" },
  { path: "affiliate-link-tracking", viewId: "affiliate-link-tracking", label: "Link Tracking" },
  { path: "accounting", viewId: "accounting", label: "Accounting" },
  { path: "accounting-transactions", viewId: "accounting-transactions", label: "Transactions" },
  { path: "accounting-reconciliation", viewId: "accounting-reconciliation", label: "Reconciliation" },
  { path: "accounting-invoices", viewId: "accounting-invoices", label: "Invoices" },
  { path: "accounting-pl", viewId: "accounting-pl", label: "P&L" },
  { path: "marketing", viewId: "marketing", label: "Marketing" },
  { path: "marketing-campaigns", viewId: "marketing-campaigns", label: "Campaigns" },
  { path: "marketing-performance", viewId: "marketing-performance", label: "Performance" },
  { path: "marketing-dashboard", viewId: "marketing-dashboard", label: "Dashboard" },
  { path: "marketing-email-campaigns", viewId: "marketing-email-campaigns", label: "Email Campaigns" },
  { path: "marketing-ad-spend", viewId: "marketing-ad-spend", label: "Ad Spend" },
  { path: "crm", viewId: "crm", label: "CRM" },
  { path: "crm-contacts", viewId: "crm-contacts", label: "Contacts" },
  { path: "crm-pipeline", viewId: "crm-pipeline", label: "Pipeline" },
  { path: "kyc", viewId: "kyc", label: "KYC" },
  { path: "kyc-reviews", viewId: "kyc-reviews", label: "Reviews" },
  { path: "kyc-risk", viewId: "kyc-risk", label: "KYC Risk" },
  { path: "kyc-document-requests", viewId: "kyc-document-requests", label: "Doc Requests" },
  { path: "kyc-onboarding", viewId: "kyc-onboarding", label: "Onboarding" },
  { path: "kyc-status", viewId: "kyc-status", label: "KYC Status" },
  { path: "support", viewId: "support", label: "Support" },
  { path: "support-tickets", viewId: "support-tickets", label: "Tickets" },
  { path: "support-knowledge", viewId: "support-knowledge", label: "Knowledge" },
  { path: "support-sla", viewId: "support-sla", label: "SLA" },
  { path: "ai", viewId: "ai", label: "AI" },
  { path: "ai-insights", viewId: "ai-insights", label: "Insights" },
  { path: "ai-assistant", viewId: "ai-assistant", label: "Assistant" },
  { path: "ai-configure", viewId: "ai-configure", label: "Configure" },
  { path: "ai-predictive", viewId: "ai-predictive", label: "Predictive" },
  { path: "ai-anomaly", viewId: "ai-anomaly", label: "Anomaly" },
  { path: "ai-cost", viewId: "ai-cost", label: "Cost Tracking" },
  { path: "audit-user-events", viewId: "audit-user-events", label: "User Events" },
  { path: "audit-change-history", viewId: "audit-change-history", label: "Change History" },
  { path: "audit-user-event-detail", viewId: "audit-user-event-detail", label: "Event Detail" },
  { path: "email-templates", viewId: "email-templates", label: "Email Templates" },
  { path: "certificate-management", viewId: "certificate-management", label: "Certificate Mgmt" },
  { path: "banner-management", viewId: "banner-management", label: "Banners" },
  { path: "user-management", viewId: "user-management", label: "User Mgmt" },
  { path: "group-management", viewId: "group-management", label: "Groups" },
  { path: "token-management", viewId: "token-management", label: "Tokens" },
  { path: "certificatesissued", viewId: "certificatesissued", label: "Issued Certs" },
  { path: "certificate-detail", viewId: "certificate-detail", label: "Cert Detail" },
  { path: "notifications-management", viewId: "notifications-management", label: "Notif Mgmt" },
  { path: "notification-edit", viewId: "notification-edit", label: "Notif Edit" },
  { path: "utilities", viewId: "utilities", label: "Utilities" },
  { path: "email-template-edit", viewId: "email-template-edit", label: "Email Template Edit" },
  { path: "certificate-template-designer", viewId: "certificate-template-designer", label: "Cert Template Designer" },
  { path: "certificate-font-upload", viewId: "certificate-font-upload", label: "Font Upload" },
  { path: "marketing-integrations", viewId: "marketing-integrations", label: "Marketing Integrations" },
  { path: "marketing-banner-edit", viewId: "marketing-banner-edit", label: "Banner Edit" },
  { path: "social-media-links", viewId: "social-media-links", label: "Social Links" },
  { path: "device-activities", viewId: "device-activities", label: "Device Activities" },
  { path: "token-detail", viewId: "token-detail", label: "Token Detail" },
  { path: "audit-user-events-enhanced", viewId: "audit-user-events-enhanced", label: "Enhanced Events" },
  { path: "kyc-providers", viewId: "kyc-providers", label: "KYC Providers" },
  { path: "2fa-setup-dialog", viewId: "2fa-setup-dialog", label: "2FA Setup" },
  { path: "notification-center", viewId: "notification-center", label: "Notification Center" },
  { path: "audit-log", viewId: "audit-log", label: "Audit Log" },
  { path: "enhanced-user-events", viewId: "enhanced-user-events", label: "Enhanced Events" },
  { path: "transactions", viewId: "transactions", label: "Transactions" },
  { path: "reviewer-audit-trail", viewId: "reviewer-audit-trail", label: "Reviewer Trail" },
  { path: "account-broker-details", viewId: "account-broker-details", label: "Broker Details" },
  { path: "account-configuration", viewId: "account-configuration", label: "Account Config" },
  { path: "account-events", viewId: "account-events", label: "Account Events" },
  { path: "account-ip-addresses", viewId: "account-ip-addresses", label: "IP Addresses" },
  { path: "account-kyc-statuses", viewId: "account-kyc-statuses", label: "KYC Statuses" },
  { path: "account-linkage-graph", viewId: "account-linkage-graph", label: "Linkage Graph" },
  { path: "account-related-accounts", viewId: "account-related-accounts", label: "Related Accounts" },
  { path: "account-version-history", viewId: "account-version-history", label: "Version History" },
  { path: "add-group-sheet", viewId: "add-group-sheet", label: "Add Group" },
  { path: "affiliate-commission-payout", viewId: "affiliate-commission-payout", label: "Commission Payout" },
  { path: "affiliate-comparison", viewId: "affiliate-comparison", label: "Comparison" },
  { path: "affiliate-detail", viewId: "affiliate-detail", label: "Affiliate Detail" },
  { path: "affiliate-link-tracking", viewId: "affiliate-link-tracking", label: "Link Tracking" },
  { path: "affiliate-onboarding", viewId: "affiliate-onboarding", label: "Onboarding" },
  { path: "affiliates-campaigns", viewId: "affiliates-campaigns", label: "Campaigns" },
  { path: "affiliates-commissions", viewId: "affiliates-commissions", label: "Commissions" },
  { path: "affiliates-list", viewId: "affiliates-list", label: "List" },
  { path: "affiliates", viewId: "affiliates", label: "Affiliates" },
  { path: "ai-finetuning", viewId: "ai-finetuning", label: "Fine-tuning" },
  { path: "ai-model-audit", viewId: "ai-model-audit", label: "Model Audit" },
  { path: "ai-prompt-library", viewId: "ai-prompt-library", label: "Prompt Library" },
  { path: "ai-quota", viewId: "ai-quota", label: "Usage Quota" },
  { path: "ai-training-export", viewId: "ai-training-export", label: "Training Export" },
  { path: "ai", viewId: "ai", label: "AI" },
  { path: "analytics-advanced", viewId: "analytics-advanced", label: "Advanced Analytics" },
  { path: "analytics-daily-highlights", viewId: "analytics-daily-highlights", label: "Daily Highlights" },
  { path: "analytics-firm-statistics", viewId: "analytics-firm-statistics", label: "Firm Statistics" },
  { path: "analytics-performance", viewId: "analytics-performance", label: "Performance" },
  { path: "analytics-retention", viewId: "analytics-retention", label: "Retention" },
  { path: "analytics-risk", viewId: "analytics-risk", label: "Risk Analytics" },
  { path: "analytics-traders", viewId: "analytics-traders", label: "Trader Analytics" },
  { path: "analytics", viewId: "analytics", label: "Analytics" },
  { path: "audit-compliance-report", viewId: "audit-compliance-report", label: "Compliance Report" },
  { path: "audit-retention", viewId: "audit-retention", label: "Retention" },
  { path: "audit-severity-policy", viewId: "audit-severity-policy", label: "Severity Policy" },
  { path: "audit-siem", viewId: "audit-siem", label: "SIEM" },
  { path: "audit", viewId: "audit", label: "Audit" },
  { path: "audit-user-event-detail", viewId: "audit-user-event-detail", label: "Event Detail" },
  { path: "audit-user-events-enhanced", viewId: "audit-user-events-enhanced", label: "Enhanced Events" },
  { path: "audit-user-events", viewId: "audit-user-events", label: "User Events" },
  { path: "bank-statement-import", viewId: "bank-statement-import", label: "Bank Statement Import" },
  { path: "banner-management", viewId: "banner-management", label: "Banner Management" },
  { path: "breach-detail", viewId: "breach-detail", label: "Breach Detail" },
  { path: "breaches", viewId: "breaches", label: "Breaches" },
  { path: "certificate-detail", viewId: "certificate-detail", label: "Certificate Detail" },
  { path: "certificate-font-upload", viewId: "certificate-font-upload", label: "Font Upload" },
  { path: "certificate-management", viewId: "certificate-management", label: "Certificate Management" },
  { path: "certificates-issued", viewId: "certificates-issued", label: "Certificates Issued" },
  { path: "certificate-template-designer", viewId: "certificate-template-designer", label: "Template Designer" },
  { path: "change-password-dialog", viewId: "change-password-dialog", label: "Change Password" },
  { path: "chart-of-accounts", viewId: "chart-of-accounts", label: "Chart of Accounts" },
  { path: "checkout-external", viewId: "checkout-external", label: "External Integration" },
  { path: "checkout-providers", viewId: "checkout-providers", label: "Payment Providers" },
  { path: "checkout-psp-onboarding", viewId: "checkout-psp-onboarding", label: "PSP Onboarding" },
  { path: "checkout-refund-dispute", viewId: "checkout-refund-dispute", label: "Refund/Dispute" },
  { path: "checkout-settlement", viewId: "checkout-settlement", label: "Settlement" },
  { path: "checkout-transactions", viewId: "checkout-transactions", label: "Transactions" },
  { path: "checkout-webhook-log", viewId: "checkout-webhook-log", label: "Webhook Log" },
  { path: "checkout", viewId: "checkout", label: "Checkout" },
  { path: "checkout-webhook-log", viewId: "checkout-webhook-log", label: "Webhook Log" },
  { path: "cohort-builder", viewId: "cohort-builder", label: "Cohort Builder" },
  { path: "connected-sessions-detail", viewId: "connected-sessions-detail", label: "Session Detail" },
  { path: "cookie-attribution", viewId: "cookie-attribution", label: "Cookie Attribution" },
  { path: "copy-trading-analysis", viewId: "copy-trading-analysis", label: "Copy Trading Analysis" },
  { path: "copy-trading-events", viewId: "copy-trading-events", label: "Copy Trading Events" },
  { path: "crm-activity-log", viewId: "crm-activity-log", label: "Activity Log" },
  { path: "crm-contact-create", viewId: "crm-contact-create", label: "Add Contact" },
  { path: "crm-contacts", viewId: "crm-contacts", label: "Contacts" },
  { path: "crm-lead-scoring", viewId: "crm-lead-scoring", label: "Lead Scoring" },
  { path: "crm-pipeline", viewId: "crm-pipeline", label: "Pipeline" },
  { path: "crm", viewId: "crm", label: "CRM" },
  { path: "csv-import-dialog", viewId: "csv-import-dialog", label: "CSV Import" },
  { path: "custom-segmentation", viewId: "custom-segmentation", label: "Segmentation" },
  { path: "dashboard-template-library", viewId: "dashboard-template-library", label: "Template Library" },
  { path: "device-activities", viewId: "device-activities", label: "Device Activities" },
  { path: "device-detail", viewId: "device-detail", label: "Device Detail" },
  { path: "email-template-edit", viewId: "email-template-edit", label: "Email Template Edit" },
  { path: "email-templates", viewId: "email-templates", label: "Email Templates" },
  { path: "financial-reports-library", viewId: "financial-reports-library", label: "Financial Reports" },
  { path: "group-management", viewId: "group-management", label: "Group Management" },
  { path: "help-changelog", viewId: "help-changelog", label: "Changelog" },
  { path: "help-module-detail", viewId: "help-module-detail", label: "Module Detail" },
  { path: "inverse-trading-events", viewId: "inverse-trading-events", label: "Inverse Events" },
  { path: "journal-entries", viewId: "journal-entries", label: "Journal Entries" },
  { path: "kyc-aml-cases", viewId: "kyc-aml-cases", label: "AML Cases" },
  { path: "kyc-provider-marketplace", viewId: "kyc-provider-marketplace", label: "Provider Marketplace" },
  { path: "kyc-providers", viewId: "kyc-providers", label: "KYC Providers" },
  { path: "kyc-record-detail", viewId: "kyc-record-detail", label: "KYC Record Detail" },
  { path: "kyc-reviewer-trail", viewId: "kyc-reviewer-trail", label: "Reviewer Trail" },
  { path: "kyc-reviews", viewId: "kyc-reviews", label: "KYC Reviews" },
  { path: "kyc-risk", viewId: "kyc-risk", label: "KYC Risk" },
  { path: "kyc", viewId: "kyc", label: "KYC" },
  { path: "marketing-ad-accounts", viewId: "marketing-ad-accounts", label: "Ad Accounts" },
  { path: "marketing-ad-spend", viewId: "marketing-ad-spend", label: "Ad Spend" },
  { path: "marketing-audience-builder", viewId: "marketing-audience-builder", label: "Audience Builder" },
  { path: "marketing-banner-edit", viewId: "marketing-banner-edit", label: "Banner Edit" },
  { path: "marketing-campaign-detail", viewId: "marketing-campaign-detail", label: "Campaign Detail" },
  { path: "marketing-dashboard", viewId: "marketing-dashboard", label: "Marketing Dashboard" },
  { path: "marketing-email-campaigns", viewId: "marketing-email-campaigns", label: "Email Campaigns" },
  { path: "marketing-integrations", viewId: "marketing-integrations", label: "Integrations" },
  { path: "marketing-performance", viewId: "marketing-performance", label: "Performance" },
  { path: "marketing-template-editor", viewId: "marketing-template-editor", label: "Template Editor" },
  { path: "marketing", viewId: "marketing", label: "Marketing" },
  { path: "my-tasks", viewId: "my-tasks", label: "My Tasks" },
  { path: "notification-detail-dialog", viewId: "notification-detail-dialog", label: "Notification Detail" },
  { path: "notification-edit", viewId: "notification-edit", label: "Notification Edit" },
  { path: "notification-preferences-matrix", viewId: "notification-preferences-matrix", label: "Notif Preferences" },
  { path: "notifications-archived", viewId: "notifications-archived", label: "Archived Notifs" },
  { path: "notifications-management", viewId: "notifications-management", label: "Notif Management" },
  { path: "notifications", viewId: "notifications", label: "Notifications" },
  { path: "offer-change-history", viewId: "offer-change-history", label: "Change History" },
  { path: "offer-edit", viewId: "offer-edit", label: "Offer Edit" },
  { path: "offer-management", viewId: "offer-management", label: "Offer Management" },
  { path: "offer-matching-users", viewId: "offer-matching-users", label: "Matching Users" },
  { path: "orders", viewId: "orders", label: "Orders" },
  { path: "overview-onboarding-tour", viewId: "overview-onboarding-tour", label: "Onboarding Tour" },
  { path: "overview-saved-views", viewId: "overview-saved-views", label: "Saved Views" },
  { path: "overview", viewId: "overview", label: "Overview" },
  { path: "payout-compliance", viewId: "payout-compliance", label: "Payout Compliance" },
  { path: "payout-detail", viewId: "payout-detail", label: "Payout Detail" },
  { path: "payout-methods-config", viewId: "payout-methods-config", label: "Methods Config" },
  { path: "payout-reversal", viewId: "payout-reversal", label: "Payout Reversal" },
  { path: "payouts-bulk-approval", viewId: "payouts-bulk-approval", label: "Bulk Approval" },
  { path: "payout-schedule", viewId: "payout-schedule", label: "Payout Schedule" },
  { path: "payouts-enhanced-withdrawals", viewId: "payouts-enhanced-withdrawals", label: "Enhanced Withdrawals" },
  { path: "payouts-history", viewId: "payouts-history", label: "Payout History" },
  { path: "payouts-pending", viewId: "payouts-pending", label: "Pending Payouts" },
  { path: "payouts", viewId: "payouts", label: "Payouts" },
  { path: "pending-snoozed-resolved", viewId: "pending-snoozed-resolved", label: "Snoozed/Resolved" },
  { path: "pending-task-detail", viewId: "pending-task-detail", label: "Task Detail" },
  { path: "pending-tasks", viewId: "pending-tasks", label: "Pending Tasks" },
  { path: "position-detail-live", viewId: "position-detail-live", label: "Position Detail" },
  { path: "profile-api-tokens", viewId: "profile-api-tokens", label: "API Tokens" },
  { path: "profile", viewId: "profile", label: "Profile" },
  { path: "reconciled-transactions", viewId: "reconciled-transactions", label: "Reconciled Transactions" },
  { path: "recurring-invoices", viewId: "recurring-invoices", label: "Recurring Invoices" },
  { path: "refunds-credit-notes", viewId: "refunds-credit-notes", label: "Refunds/Credits" },
  { path: "risk-account-label-analysis", viewId: "risk-account-label-analysis", label: "Label Analysis" },
  { path: "risk-addon-revenue", viewId: "risk-addon-revenue", label: "Addon Revenue" },
  { path: "risk-alert-subscription", viewId: "risk-alert-subscription", label: "Alert Subscription" },
  { path: "risk-coupon-vs-payouts", viewId: "risk-coupon-vs-payouts", label: "Coupon vs Payouts" },
  { path: "risk-group-vs-payouts", viewId: "risk-group-vs-payouts", label: "Group vs Payouts" },
  { path: "risk-highest-earners", viewId: "risk-highest-earners", label: "Highest Earners" },
  { path: "risk-label-vs-payouts", viewId: "risk-label-vs-payouts", label: "Label vs Payouts" },
  { path: "risk-revenue-loss", viewId: "risk-revenue-loss", label: "Revenue Loss" },
  { path: "risk-rules-editor", viewId: "risk-rules-editor", label: "Rules Editor" },
  { path: "risk-statistics", viewId: "risk-statistics", label: "Risk Statistics" },
  { path: "risk", viewId: "risk", label: "Risk" },
  { path: "risk-unprofitable-countries", viewId: "risk-unprofitable-countries", label: "Unprofitable Countries" },
  { path: "roles-management", viewId: "roles-management", label: "Roles Management" },
  { path: "saved-reports", viewId: "saved-reports", label: "Saved Reports" },
  { path: "scheduled-exports", viewId: "scheduled-exports", label: "Scheduled Exports" },
  { path: "settings-module-detail", viewId: "settings-module-detail", label: "Module Detail" },
  { path: "settings", viewId: "settings", label: "Settings" },
  { path: "social-media-links", viewId: "social-media-links", label: "Social Links" },
  { path: "support-agent-detail", viewId: "support-agent-detail", label: "Agent Detail" },
  { path: "support-canned-responses", viewId: "support-canned-responses", label: "Canned Responses" },
  { path: "support-contact", viewId: "support-contact", label: "Support Contact" },
  { path: "support-csat", viewId: "support-csat", label: "CSAT" },
  { path: "support-knowledge-editor", viewId: "support-knowledge-editor", label: "Knowledge Editor" },
  { path: "support-knowledge", viewId: "support-knowledge", label: "Knowledge" },
  { path: "support-sla", viewId: "support-sla", label: "SLA" },
  { path: "support-tickets", viewId: "support-tickets", label: "Tickets" },
  { path: "support", viewId: "support", label: "Support" },
  { path: "tax-vat-config", viewId: "tax-vat-config", label: "Tax/VAT Config" },
  { path: "team-members", viewId: "team-members", label: "Team Members" },
  { path: "token-detail", viewId: "token-detail", label: "Token Detail" },
  { path: "token-management", viewId: "token-management", label: "Token Management" },
  { path: "trader-risk-score-detail", viewId: "trader-risk-score-detail", label: "Risk Score Detail" },
  { path: "trading-events", viewId: "trading-events", label: "Trading Events" },
  { path: "transaction-detail", viewId: "transaction-detail", label: "Transaction Detail" },
  { path: "user-audit-timeline", viewId: "user-audit-timeline", label: "Audit Timeline" },
  { path: "vpn-proxy-detection-dashboard", viewId: "vpn-proxy-detection-dashboard", label: "VPN/Proxy Detection" },
  { path: "weekend-trades", viewId: "weekend-trades", label: "Weekend Trades" },
];

export const stitchModule: FrontendModule = {
  manifest: {
    id: "stitch",
    name: "Stitch",
    version: "1.0.0",
    description: "Screens converted from stitch_screens reference renders.",
    category: "core",
    optional: true,
    supportedApplications: ["prop-admin"],
    dependencies: ["trading"],
    permissions: [
      { id: "stitch.view", label: "View stitch screens" },
    ],
    icon: Monitor,
    accentColor: "#0a0a0a",
  },
  navigation,
  routes,
};
