"use client";

/**
 * Reconciliation — Stitch conversion (view-id: `accounting-reconciliation`)
 *
 * Source: stitch_screens/reconciliation
 * Spec: [EXISTING] · overlay states: 2/2 wired
 * States: reconciliation_discrepancy_investigation_sheet_state✓, reconciliation_import_bank_statement_sheet_state✓
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import * as React from "react";
import { MsIcon } from "@/components/stitch/stitch";

export function AccountingReconciliationStitchPage() {
  const [so0, setSo0] = React.useState(false);
  const [so1, setSo1] = React.useState(false);
  return (
    <>
      <div className="flex flex-col w-full space-y-6">
        <div className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4">
          <div className="flex flex-col space-y-1">
            <div className="flex items-center gap-2 text-[11px] font-semibold tracking-wider text-tsc uppercase">
              <span>Financial Ledger</span>
              <span className="text-outline-variant font-mono">/</span>
              <span>Accounting &amp; Reconciliation</span>
              <span className="text-outline-variant font-mono">/</span>
              <span className="text-primary font-bold">Reconciliation</span>
            </div>
            <h1 className="text-2xl lg:text-3xl font-headline font-bold text-on-surface tracking-tight">Reconciliation</h1>
            <p className="text-xs sm:text-sm text-tsc font-normal max-w-3xl leading-relaxed">              Audit ledger transactions against multi-currency bank feeds, payment settlement rails, and custodial statements with automated dual-entry clearing.</p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-[11px] font-medium text-on-surface-variant shadow-sm">
<MsIcon name="lock" className="text-[14px] text-tertiary" />
              <span>SEC Rule 17a-4 / FINRA WORM</span>
              <span className="font-mono text-tertiary font-bold">#8a9fc2</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-[11px] font-medium text-on-surface-variant shadow-sm">
              <span className="relative flex h-1.5 w-1.5">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-primary"></span>
              </span>
              <span className="text-tsc">ClickHouse:</span>
              <span className="font-mono text-primary font-bold">0.8ms</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-[11px] font-medium text-on-surface-variant shadow-sm">
<MsIcon name="verified" className="text-[14px] text-primary" />
              <span>Auto-Match:</span>
              <span className="font-mono font-bold text-primary">99.48%</span>
            </div>
            <div className="hidden 2xl:flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-[11px] font-medium text-tsc shadow-sm">
<MsIcon name="account_balance" className="text-[14px]" />
              <span>JPM Chase · Wise · Fireblocks</span>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-between gap-4 pt-1">
          <div className="flex items-center gap-2">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-surface-container-high text-xs font-semibold text-on-surface">
<MsIcon name="sync_alt" className="text-[16px] text-primary" />
              <span>Dual-Entry Ledger Core v4.8</span>
            </div>
            <span className="text-xs text-tsc hidden sm:inline">Daily clearing window: 23:59:59 UTC</span>
          </div>
          <div className="flex items-center gap-3">
            <button className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-surface-container hover:bg-surface-container-high text-xs font-semibold text-on-surface transition-all shadow-sm">
<MsIcon name="file_download" className="text-[16px] text-tsc" />
              <span>Export Reconciliation Report</span>
            </button>
            <button className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-primary hover:opacity-95 text-xs font-semibold text-on-primary shadow-sm transition-all" id="btn-import-sheet" onClick={() => setSo1(true)}>
<MsIcon name="upload_file" className="text-[16px]" />
              <span>+ Import Bank Statement</span>
            </button>
          </div>
        </div>
        <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-primary-fixed flex items-center justify-center shrink-0"><MsIcon name="published_with_changes" className="text-on-primary-fixed-variant text-[22px]" /></div>
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase bg-primary-fixed text-on-primary-fixed-variant">{"ACTIVE INGESTION FEED // AUTO-RECONCILER v4.8"}</span>
                  <span className="text-[11px] text-tsc font-mono">HASH: 4b29-e81a-9f44</span>
                </div>
                <p className="text-xs sm:text-sm font-medium text-on-surface">
                  <span className="font-bold">JPMorgan Chase Institutional Primary Operating (USD • ...4091)</span>
                  — Imported today at 14:15 UTC
                </p>
                <div className="flex items-center gap-3 text-xs text-tsc font-mono">
                  <span className="text-on-surface font-semibold">2,180 lines parsed</span>
                  <span>•</span>
                  <span className="text-primary font-semibold">2,168 auto-matched</span>
                  <span>•</span>
                  <span className="text-tertiary font-bold">12 pending review</span>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3 sm:gap-4 lg:self-center">
              <div className="flex flex-col items-start lg:items-end">
                <span className="text-[10px] uppercase font-bold tracking-wider text-tsc">Match Confidence</span>
                <span className="text-sm font-bold font-mono text-primary">99.4% · ±$0.01 Max Variance</span>
              </div>
              <div className="h-8 w-px bg-surface-container-highest hidden sm:block"></div>
              <div className="flex items-center gap-2">
                <button className="px-3 py-1.5 rounded-lg bg-surface-container-low hover:bg-surface-container text-xs font-semibold text-on-surface transition-colors">                  View Import History</button>
                <button className="px-3 py-1.5 rounded-lg bg-surface-container-high hover:bg-surface-variant text-xs font-semibold text-on-surface transition-colors flex items-center gap-1.5">
<MsIcon name="add" className="text-[14px]" />
                  <span>.OFX / .CSV Ingest</span>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-tsc uppercase tracking-wider">Total Ledger Volume</span>
<MsIcon name="account_balance_wallet" className="p-1.5 rounded-lg bg-surface-container-low text-tsc text-[18px]" />
            </div>
            <div className="space-y-1">
              <div className="text-2xl font-headline font-bold text-on-surface tracking-tight">$3,482,920.00</div>
              <div className="flex items-center gap-2 text-xs">
                <span className="font-semibold text-primary inline-flex items-center gap-0.5">
<MsIcon name="trending_up" className="text-[14px]" />
                  +14.2%
                </span>
                <span className="text-tsc font-mono">4,812 total entries</span>
              </div>
            </div>
          </div>
          <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-tsc uppercase tracking-wider">Reconciled Volume</span>
<MsIcon name="verified_user" className="p-1.5 rounded-lg bg-primary-fixed text-on-primary-fixed-variant text-[18px]" />
            </div>
            <div className="space-y-1">
              <div className="text-2xl font-headline font-bold text-primary tracking-tight">$3,464,700.00</div>
              <div className="flex items-center gap-2 text-xs">
                <span className="px-2 py-0.5 rounded-full bg-primary-fixed text-on-primary-fixed-variant font-bold text-[10px]">WORM SEALED</span>
                <span className="text-tsc font-mono">4,798 entries cleared</span>
              </div>
            </div>
          </div>
          <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-tsc uppercase tracking-wider">Pending Delta</span>
<MsIcon name="pending_actions" className="p-1.5 rounded-lg bg-tertiary-fixed text-on-tertiary-fixed text-[18px]" />
            </div>
            <div className="space-y-1">
              <div className="text-2xl font-headline font-bold text-tertiary tracking-tight">$18,220.00</div>
              <div className="flex items-center gap-2 text-xs">
                <span className="px-2 py-0.5 rounded-full bg-tertiary-fixed text-on-tertiary-fixed font-bold text-[10px]">14 QUEUE ITEMS</span>
                <span className="text-tsc font-mono">Awaiting pair/sign-off</span>
              </div>
            </div>
          </div>
          <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm relative overflow-hidden flex flex-col justify-between">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-tsc uppercase tracking-wider">Reconciliation Rate</span>
<MsIcon name="donut_large" className="p-1.5 rounded-lg bg-surface-container-low text-primary text-[18px]" />
            </div>
            <div className="space-y-1">
              <div className="flex items-baseline justify-between">
                <span className="text-2xl font-headline font-bold text-on-surface tracking-tight">99.48%</span>
                <span className="text-[10px] font-bold text-primary bg-primary-fixed px-2 py-0.5 rounded">{"NOMINAL // SEC PASS"}</span>
              </div>
              <div className="flex items-center gap-2 text-xs">
                <span className="text-tsc">Floor: ≥80.0%</span>
                <span className="text-outline-variant font-mono">•</span>
                <span className="text-primary font-semibold font-mono">+0.32% vs M-1</span>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-surface-container-lowest rounded-xl p-5 shadow-sm space-y-4">
          <div className="flex flex-col lg:flex-row items-stretch lg:items-center justify-between gap-4">
            <div className="relative flex-1 max-w-xl">
<MsIcon name="search" className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[18px] text-tsc" />
<input className="w-full bg-surface-container-low pl-10 pr-16 py-2 rounded-xl text-xs text-on-surface placeholder-tsc focus:outline-none focus:bg-surface-container-lowest focus:ring-1 focus:ring-primary shadow-sm" placeholder="Search reference, bank trace ID, counterparty, trader login..." type="text" />
              <span className="absolute right-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 rounded bg-surface-container text-[10px] font-mono font-semibold text-tsc shadow-xs">⌘K</span>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <label className="flex items-center gap-2 cursor-pointer bg-surface-container-low px-3 py-2 rounded-xl hover:bg-surface-container transition-colors">
<input className="sr-only peer" id="toggle-reconciled" type="checkbox" />
                <div className="w-8 h-4 bg-surface-container-highest peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface-container-lowest after:rounded-full after:h-3 after:w-3 after:transition-all peer-checked:bg-primary relative"></div>
                <span className="text-xs font-semibold text-on-surface select-none">Show Cleared Records</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-secondary-container text-on-secondary-container font-mono font-bold">14 Unmatched Shown</span>
              </label>
              <button className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-surface-container text-xs font-semibold text-on-surface hover:bg-surface-container-high transition-colors">
<MsIcon name="tune" className="text-[16px] text-tsc" />
                <span>Reset Filters</span>
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 pt-2">
            <div className="relative">
              <label className="block text-[10px] font-bold text-tsc uppercase tracking-wider mb-1">Settlement Rail / Bank</label>
              <div className="relative">
                <select className="w-full appearance-none bg-surface-container-low py-2 pl-3 pr-8 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary">
                  <option>All Feeds (JPM, Wise, Stripe, Fireblocks)</option>
                  <option>JPMorgan Chase USD (...4091)</option>
                  <option>Wise Business Multi-Currency (...8821)</option>
                  <option>Stripe Settlement Core (Gateway)</option>
                  <option>Fireblocks USDT Vault (EVM)</option>
                </select>
<MsIcon name="expand_more" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[16px] text-tsc pointer-events-none" />
              </div>
            </div>
            <div className="relative">
              <label className="block text-[10px] font-bold text-tsc uppercase tracking-wider mb-1">Transaction Category</label>
              <div className="relative">
                <select className="w-full appearance-none bg-surface-container-low py-2 pl-3 pr-8 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary">
                  <option>Transaction Type: All Types</option>
                  <option>Challenge Evaluation Fees</option>
                  <option>Trader Profit Splits (Payouts)</option>
                  <option>Affiliate &amp; Media Commissions</option>
                  <option>Chargeback / Card Refunds</option>
                  <option>Platform Infrastructure OpEx</option>
                </select>
<MsIcon name="expand_more" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[16px] text-tsc pointer-events-none" />
              </div>
            </div>
            <div>
              <label className="block text-[10px] font-bold text-tsc uppercase tracking-wider mb-1">Settlement Window</label>
              <div className="flex items-center gap-2 bg-surface-container-low px-3 py-1.5 rounded-xl">
<MsIcon name="date_range" className="text-[16px] text-tsc" />
                <span className="text-xs font-medium text-on-surface font-mono">May 01, 2025 – May 18, 2025</span>
              </div>
            </div>
            <div>
              <label className="block text-[10px] font-bold text-tsc uppercase tracking-wider mb-1">Amount Range (USD)</label>
              <div className="flex items-center gap-2">
<input className="w-full bg-surface-container-low py-1.5 px-2.5 rounded-lg text-xs font-mono text-on-surface focus:outline-none focus:ring-1 focus:ring-primary" type="text" defaultValue="$0.00" />
                <span className="text-tsc font-mono text-xs">to</span>
<input className="w-full bg-surface-container-low py-1.5 px-2.5 rounded-lg text-xs font-mono text-on-surface focus:outline-none focus:ring-1 focus:ring-primary" type="text" defaultValue="$50,000.00" />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-surface-container-high rounded-xl px-5 py-3 shadow-md flex flex-wrap items-center justify-between gap-4 transition-all" id="bulk-toolbar">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center text-on-primary"><MsIcon name="check" className="text-[18px]" /></div>
            <div>
              <div className="text-xs font-bold text-on-surface flex items-center gap-2">
                <span>3 Transactions Selected</span>
                <span className="px-2 py-0.5 rounded bg-error-container text-on-error-container font-mono text-[11px] font-bold">Total Delta: -$42,180.00</span>
              </div>
              <p className="text-[11px] text-tsc font-medium">Ready for instantaneous cryptographic dual-entry ledger reconciliation</p>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <button className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-primary hover:opacity-95 text-xs font-bold text-on-primary shadow-sm transition-all" id="btn-bulk-reconcile">
<MsIcon name="done_all" className="text-[16px]" />
              <span>Reconcile Selected (3)</span>
            </button>
            <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface-container-lowest hover:bg-surface-container text-xs font-semibold text-error shadow-sm transition-all" onClick={() => setSo0(true)}>
<MsIcon name="flag" className="text-[16px]" />
              <span>Flag Discrepancy</span>
            </button>
            <button className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface-container-lowest hover:bg-surface-container text-xs font-semibold text-on-surface shadow-sm transition-all">
<MsIcon name="file_download" className="text-[16px]" />
              <span>Export Lines</span>
            </button>
            <button className="text-xs font-bold text-tsc hover:text-on-surface px-2 py-1">              Clear Selection</button>
          </div>
        </div>
        <div className="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-surface-container-low text-[10px] font-bold uppercase tracking-wider text-tsc">
                  <th className="py-3.5 pl-5 pr-2 w-10"><input defaultChecked className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></th>
                  <th className="py-3.5 px-3">Reference / Trace ID</th>
                  <th className="py-3.5 px-3">Category</th>
                  <th className="py-3.5 px-3">Description &amp; Counterparty</th>
                  <th className="py-3.5 px-3 text-right">Ledger Amount</th>
                  <th className="py-3.5 px-3 text-right">Bank Statement / Rail</th>
                  <th className="py-3.5 px-3">Confidence &amp; Delta</th>
                  <th className="py-3.5 px-3">Matching Status</th>
                  <th className="py-3.5 pr-5 pl-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-container text-xs text-on-surface">
                <tr className="bg-surface-container-low/40 hover:bg-surface-container-low transition-colors">
                  <td className="py-4 pl-5 pr-2"><input defaultChecked className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94180</div>
                    <div className="text-[10px] text-tsc">WSE-9948201A</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary-container text-on-secondary-container">                      Affiliate Payout</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">Alpha Capital Media — May 2025 RevShare</div>
                    <div className="text-[11px] text-tsc font-mono">Contract: #ACM-2024-GLOBAL</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-error">                    -$18,220.00</td>
                  <td className="py-4 px-3 text-right font-mono">
                    <div className="font-bold text-on-surface">-$18,220.00</div>
                    <div className="text-[10px] text-tsc">Wise Business (USD)</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="flex items-center gap-1.5 text-primary font-semibold text-[11px]">
<MsIcon name="check_circle" className="text-[14px]" />
                      <span>100% Exact</span>
                    </div>
                    <div className="text-[10px] text-tsc font-mono">$0.00 Delta</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Suggested Match
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-90 text-[11px] font-semibold text-on-primary shadow-xs">                        Reconcile</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
                <tr className="bg-surface-container-low/40 hover:bg-surface-container-low transition-colors">
                  <td className="py-4 pl-5 pr-2"><input defaultChecked className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94181</div>
                    <div className="text-[10px] text-tsc">JPM-WIRE-88410</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">                      Trader Payout</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">Elena Althaus (MT5-882049) — Profit Split</div>
                    <div className="text-[11px] text-tsc font-mono">80/20 Trader Tier 1 Milestone</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-error">                    -$24,500.00</td>
                  <td className="py-4 px-3 text-right font-mono">
                    <div className="font-bold text-on-surface">-$24,500.00</div>
                    <div className="text-[10px] text-tsc">JPM Chase Wire Fed#9910</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="flex items-center gap-1.5 text-primary font-semibold text-[11px]">
<MsIcon name="check_circle" className="text-[14px]" />
                      <span>100% Exact</span>
                    </div>
                    <div className="text-[10px] text-tsc font-mono">$0.00 Delta</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Suggested Match
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-90 text-[11px] font-semibold text-on-primary shadow-xs">                        Reconcile</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
                <tr className="bg-surface-container-low/40 hover:bg-surface-container-low transition-colors">
                  <td className="py-4 pl-5 pr-2"><input defaultChecked className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94182</div>
                    <div className="text-[10px] text-tsc">STR-CHG-3Nx901</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-primary-fixed text-on-primary-fixed-variant">                      Challenge Fee</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">Elena Althaus — Two-Phase $100k Evaluation</div>
                    <div className="text-[11px] text-tsc font-mono">Invoice #INV-2025-05-18-99</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-primary">                    +$540.00</td>
                  <td className="py-4 px-3 text-right font-mono">
                    <div className="font-bold text-on-surface">+$540.00</div>
                    <div className="text-[10px] text-tsc">Stripe Direct Settled</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="flex items-center gap-1.5 text-primary font-semibold text-[11px]">
<MsIcon name="check_circle" className="text-[14px]" />
                      <span>100% Exact</span>
                    </div>
                    <div className="text-[10px] text-tsc font-mono">$0.00 Delta</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Suggested Match
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-primary hover:opacity-90 text-[11px] font-semibold text-on-primary shadow-xs">                        Reconcile</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
                <tr className="hover:bg-surface-container-low/60 transition-colors">
                  <td className="py-4 pl-5 pr-2"><input className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94175</div>
                    <div className="text-[10px] text-tsc">BARC-DD-44189</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary-container text-on-secondary-container">                      Platform OpEx</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">Equinix LD4 Dedicated FIX Cross-Connect</div>
                    <div className="text-[11px] text-tsc font-mono">NY4 - LD4 Point-to-Point Transit</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-error">                    -$1,250.00</td>
                  <td className="py-4 px-3 text-right font-mono">
                    <div className="font-bold text-on-surface">-$1,265.00</div>
                    <div className="text-[10px] text-tsc">Barclays Direct Debit</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="flex items-center gap-1.5 text-error font-semibold text-[11px]">
<MsIcon name="warning" className="text-[14px]" />
                      <span>Variance: -$15.00</span>
                    </div>
                    <div className="text-[10px] text-tsc">Interbank Cable Fee</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-error-container text-on-error-container">
                      <span className="w-1.5 h-1.5 rounded-full bg-error"></span>
                      Discrepancy Flagged
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-[11px] font-bold text-error transition-colors">                        Resolve Fee</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
                <tr className="hover:bg-surface-container-low/60 transition-colors">
                  <td className="py-4 pl-5 pr-2"><input className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94178</div>
                    <div className="text-[10px] text-tsc">STR-RFD-00291</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-secondary-container text-on-secondary-container">                      Refund Reversal</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">Liam Chen — Double Charge Reversal (DX-449102)</div>
                    <div className="text-[11px] text-tsc font-mono">Merchant Auth Cancelled</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-error">                    -$540.00</td>
                  <td className="py-4 px-3 text-right font-mono">
                    <div className="font-bold text-on-surface">-$540.00</div>
                    <div className="text-[10px] text-tsc">Stripe Platform Refund</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="flex items-center gap-1.5 text-primary font-semibold text-[11px]">
<MsIcon name="check_circle" className="text-[14px]" />
                      <span>100% Match</span>
                    </div>
                    <div className="text-[10px] text-tsc font-mono">$0.00 Delta</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-primary-fixed text-on-primary-fixed-variant">
                      <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                      Suggested Match
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-surface-container-high hover:bg-surface-variant text-[11px] font-semibold text-on-surface">                        Reconcile</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
                <tr className="hover:bg-surface-container-low/60 transition-colors">
                  <td className="py-4 pl-5 pr-2"><input className="rounded accent-primary w-4 h-4 cursor-pointer" type="checkbox" /></td>
                  <td className="py-4 px-3 font-mono">
                    <div className="font-bold text-on-surface">TX-94170</div>
                    <div className="text-[10px] text-tsc font-italic">Unassigned Bank Ref</div>
                  </td>
                  <td className="py-4 px-3">                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-tertiary-fixed text-on-tertiary-fixed">                      SaaS Subscription</span></td>
                  <td className="py-4 px-3 max-w-xs">
                    <div className="font-semibold truncate">TraderView L2 Feed — May 2025 Subscriptions</div>
                    <div className="text-[11px] text-tsc font-mono">Vendor recurring direct debits</div>
                  </td>
                  <td className="py-4 px-3 text-right font-mono font-bold text-primary">                    +$145.00</td>
                  <td className="py-4 px-3 text-right">
                    <div className="text-xs font-semibold text-tsc italic">Missing Bank Line</div>
                    <div className="text-[10px] text-error font-medium">No clearing match</div>
                  </td>
                  <td className="py-4 px-3">
                    <div className="text-xs font-semibold text-tsc">0% Paired</div>
                    <div className="text-[10px] text-tsc font-mono">+$145.00 Delta</div>
                  </td>
                  <td className="py-4 px-3">
                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-surface-container-high text-tsc">
                      <span className="w-1.5 h-1.5 rounded-full bg-tsc"></span>
                      Pending Matching
                    </span>
                  </td>
                  <td className="py-4 pr-5 pl-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button className="px-2.5 py-1 rounded-lg bg-surface-container hover:bg-surface-container-high text-[11px] font-semibold text-primary">                        Search Bank</button>
                      <button className="p-1 rounded-md text-tsc hover:text-on-surface hover:bg-surface-container"><MsIcon name="more_vert" className="text-[18px]" /></button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="bg-surface-container-low px-5 py-4 flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3 text-xs text-tsc">
              <span>Showing <span className="font-bold text-on-surface">1 - 6</span> of <span className="font-bold text-on-surface">14</span> pending reconciliation items</span>
              <span className="text-outline-variant font-mono">•</span>
              <span className="text-[11px]">Filtered from 4,812 total ledger entries (4,798 reconciled hidden)</span>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 text-xs text-tsc">
                <span>Rows per page:</span>
                <select className="bg-surface-container py-1 px-2 rounded-lg text-xs font-semibold text-on-surface focus:outline-none">
                  <option>15</option>
                  <option>25</option>
                  <option>50</option>
                </select>
              </div>
              <div className="flex items-center gap-1">
                <button className="p-1.5 rounded-lg bg-surface-container-lowest text-tsc hover:text-on-surface disabled:opacity-40" disabled><MsIcon name="chevron_left" className="text-[16px]" /></button>
                <button className="px-2.5 py-1 rounded-lg bg-primary text-on-primary font-bold text-xs shadow-xs">1</button>
                <button className="px-2.5 py-1 rounded-lg bg-surface-container-lowest text-on-surface font-semibold text-xs hover:bg-surface-container">2</button>
                <button className="p-1.5 rounded-lg bg-surface-container-lowest text-tsc hover:text-on-surface"><MsIcon name="chevron_right" className="text-[16px]" /></button>
              </div>
            </div>
          </div>
        </div>
        <div className="rounded-xl bg-surface-container p-4 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 text-xs">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-surface-container-highest flex items-center justify-center text-primary shrink-0"><MsIcon name="verified" className="text-[18px]" /></div>
            <div>
              <div className="font-bold text-on-surface font-mono text-[11px]">SEC Rule 17a-4 / FINRA WORM AUDIT STAMP</div>
              <p className="text-[11px] text-tsc font-mono tracking-tight">sha256:7f9b8c0649d11e2f7b889312e09bc8721ad441c9f00192e88a0</p>
            </div>
          </div>
          <div className="flex items-center gap-4 self-stretch md:self-auto justify-between md:justify-end">
            <div className="flex flex-col md:items-end">
              <span className="text-[10px] font-bold text-tsc uppercase tracking-wider">Dual-Entry Balance Check</span>
              <span className="font-mono font-bold text-primary flex items-center gap-1">
<MsIcon name="check" className="text-[14px]" />
                DR/CR Delta: $0.00 (PERFECT BALANCE)
              </span>
            </div>
            <div className="h-6 w-px bg-surface-container-highest hidden sm:block"></div>
            <button className="px-3 py-1.5 rounded-lg bg-surface-container-highest hover:bg-surface-variant font-semibold text-[11px] text-on-surface transition-colors flex items-center gap-1">
<MsIcon name="history_edu" className="text-[14px]" />
              <span>View Full Audit Log</span>
            </button>
          </div>
        </div>
        <div className="fixed inset-0 bg-inverse-surface/40 backdrop-blur-sm z-50 hidden transition-opacity" id="import-sheet-backdrop">
          <div className="absolute right-0 top-0 bottom-0 w-full max-w-lg bg-surface-container-lowest p-6 shadow-2xl flex flex-col justify-between overflow-y-auto">
            <div className="space-y-6">
              <div className="flex items-center justify-between pb-4">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-xl bg-primary-fixed flex items-center justify-center text-on-primary-fixed-variant"><MsIcon name="upload_file" className="text-[20px]" /></div>
                  <div>
                    <h2 className="text-lg font-headline font-bold text-on-surface">Import Bank Statement</h2>
                    <p className="text-xs text-tsc">Ingest statement files for automatic dual-entry matching</p>
                  </div>
                </div>
                <button className="p-2 rounded-lg hover:bg-surface-container text-tsc hover:text-on-surface" id="btn-close-import"><MsIcon name="close" className="text-[20px]" /></button>
              </div>
              <div className="space-y-1.5">
                <label className="block text-xs font-bold text-tsc uppercase tracking-wider">Target Settlement Account</label>
                <div className="relative">
                  <select className="w-full bg-surface-container-low py-2.5 pl-3 pr-8 rounded-xl text-xs font-medium text-on-surface focus:outline-none focus:ring-1 focus:ring-primary">
                    <option>JPMorgan Chase Institutional Operating (USD • ...4091)</option>
                    <option>Wise Business Multi-Currency Main (EUR / GBP • ...8821)</option>
                    <option>Stripe Clearing Balance Account</option>
                    <option>Fireblocks USDT Vault (Corporate Custody)</option>
                  </select>
<MsIcon name="expand_more" className="absolute right-3 top-1/2 -translate-y-1/2 text-[18px] text-tsc pointer-events-none" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="block text-xs font-bold text-tsc uppercase tracking-wider">File Standard</label>
                  <select className="w-full bg-surface-container-low py-2 px-3 rounded-xl text-xs font-medium text-on-surface focus:outline-none">
                    <option>Auto-Detect (.OFX, .CSV, .QIF)</option>
                    <option>Open Financial Exchange (.OFX)</option>
                    <option>Standard Comma-Separated (.CSV)</option>
                    <option>SWIFT MT940 / CAMT.053</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="block text-xs font-bold text-tsc uppercase tracking-wider">Statement Currency</label>
                  <select className="w-full bg-surface-container-low py-2 px-3 rounded-xl text-xs font-medium text-on-surface focus:outline-none">
                    <option>USD — US Dollar ($)</option>
                    <option>EUR — Euro (€)</option>
                    <option>GBP — British Pound (£)</option>
                    <option>USDT — Tether USD</option>
                  </select>
                </div>
              </div>
              <div className="rounded-xl p-8 bg-surface-container-low flex flex-col items-center justify-center text-center space-y-3 cursor-pointer hover:bg-surface-container transition-colors">
                <div className="w-12 h-12 rounded-full bg-surface-container flex items-center justify-center text-primary"><MsIcon name="cloud_upload" className="text-[28px]" /></div>
                <div className="space-y-1">
                  <p className="text-xs font-bold text-on-surface">Click to upload statement or drag &amp; drop</p>
                  <p className="text-[11px] text-tsc">Supports OFX, QIF, CAMT.053 or CSV up to 128MB</p>
                </div>
                <span className="px-3 py-1 rounded-full bg-surface-container text-[10px] font-mono text-tsc">WORM Encryption Automated</span>
              </div>
              <div className="bg-surface-container-low rounded-xl p-4 space-y-3">
                <span className="text-xs font-bold text-on-surface">Ingestion &amp; Auto-Clearing Rules</span>
                <div className="space-y-2">
                  <label className="flex items-center gap-2 cursor-pointer">
<input defaultChecked className="rounded accent-primary w-4 h-4" type="checkbox" />
                    <span className="text-xs text-on-surface font-medium">Auto-clear exact matches with 100% confidence</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
<input defaultChecked className="rounded accent-primary w-4 h-4" type="checkbox" />
                    <span className="text-xs text-on-surface font-medium">Permit FX cable fee variance up to $25.00</span>
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
<input className="rounded accent-primary w-4 h-4" type="checkbox" />
                    <span className="text-xs text-on-surface font-medium">Notify compliance officer of discrepancies immediately</span>
                  </label>
                </div>
              </div>
            </div>
            <div className="pt-6 flex items-center justify-end gap-3">
              <button className="px-4 py-2 rounded-xl bg-surface-container text-xs font-semibold text-on-surface hover:bg-surface-container-high transition-colors" id="btn-cancel-import">                Cancel</button>
              <button className="px-5 py-2 rounded-xl bg-primary hover:opacity-95 text-xs font-bold text-on-primary shadow-sm transition-all flex items-center gap-1.5">
<MsIcon name="play_arrow" className="text-[16px]" />
                <span>Start Ingestion &amp; Match</span>
              </button>
            </div>
          </div>
        </div>
        <div className="fixed inset-0 bg-inverse-surface/40 backdrop-blur-sm z-50 hidden flex items-center justify-center p-4" id="reconcile-modal">
          <div className="w-full max-w-md bg-surface-container-lowest rounded-2xl p-6 shadow-2xl space-y-5 animate-in fade-in zoom-in-95">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-primary-fixed text-on-primary-fixed-variant flex items-center justify-center shrink-0"><MsIcon name="verified" className="text-[24px]" /></div>
              <div className="space-y-1">
                <h3 className="text-base font-headline font-bold text-on-surface">Confirm Ledger Clearing</h3>
                <p className="text-xs text-tsc leading-relaxed">

            You are about to cryptographically reconcile <span className="font-bold text-on-surface">3 selected transactions</span> totaling <span className="font-mono font-bold text-on-surface">-$42,180.00</span>.
          
                </p>
              </div>
            </div>
            <div className="bg-surface-container-low rounded-xl p-3.5 space-y-2 text-xs">
              <div className="flex items-center justify-between font-mono">
                <span className="text-tsc">WORM Hash Generation:</span>
                <span className="text-primary font-bold">Enabled (SHA-256)</span>
              </div>
              <div className="flex items-center justify-between font-mono">
                <span className="text-tsc">Double-Entry Balance:</span>
                <span className="text-primary font-bold">DR/CR $0.00 Delta</span>
              </div>
              <div className="flex items-center justify-between font-mono">
                <span className="text-tsc">Audit Trail Target:</span>
                <span className="text-on-surface">SEC Rule 17a-4 Archive</span>
              </div>
            </div>
            <div className="flex items-center justify-end gap-3 pt-2">
              <button className="px-4 py-2 rounded-xl bg-surface-container text-xs font-semibold text-on-surface hover:bg-surface-container-high transition-colors" id="btn-cancel-modal">                Cancel</button>
              <button className="px-4 py-2 rounded-xl bg-primary hover:opacity-95 text-xs font-bold text-on-primary shadow-sm transition-all flex items-center gap-1.5" id="btn-confirm-reconcile">
<MsIcon name="task_alt" className="text-[16px]" />
                <span>Clear &amp; Commit (3)</span>
              </button>
            </div>
          </div>
        </div>
      </div>
      {so0 && (
        <>
        <aside aria-labelledby="sheet-title" aria-modal="true" className="fixed right-0 top-16 bottom-0 w-full max-w-2xl bg-surface-container-lowest shadow-[0_4px_30px_rgba(46,50,48,0.18)] z-50 flex flex-col overflow-hidden transition-transform duration-300 ease-out" id="investigation-sheet" role="dialog">
          <div className="px-7 py-5 bg-surface-container-low/70 border-b border-surface-container flex flex-col gap-2 shrink-0">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="flex h-2 w-2 rounded-full bg-tertiary"></span>
                <span className="text-[11px] font-mono font-bold tracking-wider uppercase text-tertiary">                  {"             SETTLEMENT AUDIT // DISCREPANCY INVESTIGATION #DISC-89410           "}</span>
              </div>
              <button aria-label="Close Investigation Drawer" className="p-1.5 rounded-lg text-tsc hover:text-on-surface hover:bg-surface-container-high transition-colors" id="close-sheet-btn" onClick={() => setSo0(false)}><MsIcon name="close" className="text-[20px]" /></button>
            </div>
            <div>
              <h2 className="font-headline font-bold text-xl text-on-surface tracking-tight" id="sheet-title">                Flag &amp; Investigate Settlement Discrepancy</h2>
              <p className="text-xs text-tsc leading-relaxed mt-0.5">                Record an audit dispute or variance between the internal accounting ledger and custodial bank records. Enforces dual-signoff under SEC Rule 17a-4.</p>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto px-7 py-6 space-y-6">
            <div className="bg-surface-container-low rounded-xl p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
<MsIcon name="receipt_long" className="text-primary text-[18px]" />
                  <span className="text-xs font-bold uppercase tracking-wider text-tsc">Transaction in Scope</span>
                </div>
                <span className="text-[11px] font-mono bg-surface-container-highest px-2 py-0.5 rounded text-on-surface-variant font-medium">                  TX-94175 (BARC-DD-44189)</span>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                <div className="space-y-0.5">
                  <span className="text-[10px] text-tsc uppercase font-semibold">Description</span>
                  <div className="font-semibold text-on-surface">Equinix LD4 Dedicated FIX Cross-Connect</div>
                  <div className="text-[11px] text-tsc">NY4 to LD4 Point-to-Point Transit</div>
                </div>
                <div className="space-y-0.5">
                  <span className="text-[10px] text-tsc uppercase font-semibold">Counterparty</span>
                  <div className="font-semibold text-on-surface">Barclays Direct Debit Corporate</div>
                  <div className="text-[11px] text-tsc">Category: OpEx Infrastructure</div>
                </div>
              </div>
              <div className="pt-2 border-t border-surface-container flex items-center justify-between text-[11px] text-tsc">
                <div className="flex items-center gap-1.5 font-mono">
<MsIcon name="schedule" className="text-[14px]" />
                  <span>May 17, 2025 • 23:40:11 UTC</span>
                </div>
                <span className="text-primary font-medium flex items-center gap-1">
<MsIcon name="lock" className="text-[13px]" />
                  WORM Audit Anchor #9921
                </span>
              </div>
            </div>
            <div className="space-y-3">
              <span className="text-xs font-bold uppercase tracking-wider text-tsc">Financial Delta Comparison</span>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="bg-surface-container p-4 rounded-xl space-y-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-tsc">Internal Ledger Amount</span>
                  <div className="text-2xl font-headline font-bold text-on-surface font-mono">-$1,250.00 <span className="text-xs font-sans text-tsc font-medium">USD</span></div>
                  <p className="text-[11px] text-tsc">Expected per contract #EQX-FIX-2024-Q2</p>
                </div>
                <div className="bg-surface-container p-4 rounded-xl space-y-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-tsc">Bank Cleared Amount</span>
                  <div className="text-2xl font-headline font-bold text-error font-mono">-$1,265.00 <span className="text-xs font-sans text-tsc font-medium">USD</span></div>
                  <p className="text-[11px] text-tsc">Debited by Barclays Bank UK (Direct Debit)</p>
                </div>
              </div>
              <div className="bg-error-container text-on-error-container rounded-xl p-3 flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-7 h-7 rounded-lg bg-error text-on-error flex items-center justify-center shrink-0"><MsIcon name="trending_down" className="text-[16px]" /></div>
                  <div>
                    <div className="text-xs font-bold">-$15.00 USD Unreconciled Variance</div>
                    <div className="text-[11px] opacity-90">Debit in bank exceeds internal ledger authorization by 1.20%</div>
                  </div>
                </div>
                <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-error/20 font-mono">DR OVERAGE</span>
              </div>
            </div>
            <div className="space-y-2">
              <label className="block text-xs font-bold uppercase tracking-wider text-tsc" htmlFor="discrepancy-category">
                Discrepancy Classification
                <span className="text-error">*</span>
              </label>
              <div className="relative">
                <select className="w-full bg-surface-container-low text-on-surface text-xs font-medium rounded-xl px-4 py-3 appearance-none focus:outline-none focus:ring-1 focus:ring-primary shadow-sm pr-10" id="discrepancy-category" defaultValue="wire_fee">
                  <option value="wire_fee">Interbank Wire / Cable Surcharge Variance (Fee Mismatch)</option>
                  <option value="fx_slippage">Exchange Rate / FX Slippage Variance</option>
                  <option value="duplicate_debit">Double Billing / Duplicate Debit</option>
                  <option value="split_transfer">Incomplete Settlement / Split Transfer</option>
                  <option value="unauthorized">Unauthorized Charge / Fraud Review</option>
                </select>
<MsIcon name="arrow_drop_down" className="absolute right-3 top-1/2 -translate-y-1/2 text-tsc pointer-events-none text-[18px]" />
              </div>
              <p className="text-[11px] text-tsc">Identifies which regulatory accounting bucket this audit exception is assigned to.</p>
            </div>
            <div className="space-y-2">
              <span className="block text-xs font-bold uppercase tracking-wider text-tsc">
                Resolution Strategy &amp; Remediation
                <span className="text-error">*</span>
              </span>
              <div className="space-y-2">
                <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
<input defaultChecked className="mt-1 accent-[#4a7c59]" name="remediation" type="radio" defaultValue="adjust_entry" />
                  <div className="space-y-0.5 min-w-0">
                    <div className="text-xs font-bold text-on-surface">Post Automatic Adjusting OpEx Journal Entry (-$15.00)</div>
                    <div className="text-[11px] text-tsc">Absorb as clearing cable fee into Broker OpEx (Account #5210). Immediately satisfies reconciliation.</div>
                  </div>
                </label>
                <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
<input className="mt-1 accent-[#4a7c59]" name="remediation" type="radio" defaultValue="clawback" />
                  <div className="space-y-0.5 min-w-0">
                    <div className="text-xs font-bold text-on-surface">Request Bank Refund / Clawback from Barclays UK</div>
                    <div className="text-[11px] text-tsc">Dispatches automated dispute inquiry to Barclays Corporate Treasury Operations Desk.</div>
                  </div>
                </label>
                <label className="flex items-start gap-3 p-3 rounded-xl bg-surface-container-low cursor-pointer hover:bg-surface-container transition-colors">
<input className="mt-1 accent-[#4a7c59]" name="remediation" type="radio" defaultValue="escrow_suspense" />
                  <div className="space-y-0.5 min-w-0">
                    <div className="text-xs font-bold text-on-surface">Hold in Escrow Suspense Account until Next Monthly Settlement Cycle</div>
                    <div className="text-[11px] text-tsc">Allocates to general clearing clearing suspense account #1990 pending Equinix credit note.</div>
                  </div>
                </label>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-bold uppercase tracking-wider text-tsc" htmlFor="audit-notes">
                  Audit Notes &amp; Justification
                  <span className="text-error">*</span>
                </label>
                <span className="text-[10px] text-tsc font-mono">SEC Rule 17a-4 Compliant</span>
              </div>
<textarea className="w-full bg-surface-container-low text-on-surface text-xs leading-relaxed p-3.5 rounded-xl focus:outline-none focus:ring-1 focus:ring-primary shadow-sm resize-none" id="audit-notes" rows={3} defaultValue="Barclays levied an unannounced £12.00 ($15.00 USD equiv) intermediate correspondent cable routing fee on the monthly Equinix transit direct debit. Contractor invoice stipulates net-settle terms. Recommending absorbing into Broker OpEx ledger with an adjusting WORM entry." />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-tsc">Supporting Evidence (Immutable Storage)</span>
                <span className="text-[11px] text-primary font-semibold cursor-pointer hover:underline">+ Attach New File</span>
              </div>
              <div className="space-y-1.5">
                <div className="flex items-center justify-between bg-surface-container p-2.5 rounded-lg text-xs">
                  <div className="flex items-center gap-2 min-w-0">
<MsIcon name="description" className="text-tsc text-[16px]" />
                    <span className="font-medium text-on-surface truncate">barclays_debit_advice_44189.pdf</span>
                    <span className="text-[10px] text-tsc">(1.2 MB)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-bold text-primary bg-primary-fixed px-2 py-0.5 rounded">Validated</span>
<MsIcon name="visibility" className="text-tsc text-[16px] cursor-pointer hover:text-on-surface" />
                  </div>
                </div>
                <div className="flex items-center justify-between bg-surface-container p-2.5 rounded-lg text-xs">
                  <div className="flex items-center gap-2 min-w-0">
<MsIcon name="description" className="text-tsc text-[16px]" />
                    <span className="font-medium text-on-surface truncate">equinix_invoice_INV-LD4-90412.pdf</span>
                    <span className="text-[10px] text-tsc">(840 KB)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-bold text-tsc bg-surface-container-highest px-2 py-0.5 rounded">Contract terms verified</span>
<MsIcon name="visibility" className="text-tsc text-[16px] cursor-pointer hover:text-on-surface" />
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-secondary-container/60 rounded-xl p-3.5 space-y-2">
              <label className="flex items-start gap-2.5 cursor-pointer">
<input defaultChecked className="mt-0.5 accent-[#4a7c59] rounded" type="checkbox" />
                <span className="text-xs text-on-secondary-container leading-snug">
                  I confirm this discrepancy investigation complies with
                  <span className="font-bold">FINRA Rule 4511</span>
                  recordkeeping and GAAP dual-entry integrity. Actions will be logged permanently to the compliance blotter under Marcus Vance (CRO).
                </span>
              </label>
            </div>
          </div>
          <div className="px-7 py-4 bg-surface-container-low border-t border-surface-container shrink-0 flex flex-col sm:flex-row items-center justify-between gap-3">
            <button className="w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-semibold text-tsc hover:text-on-surface hover:bg-surface-container-high transition-colors" id="cancel-return-btn" onClick={() => setSo0(false)}>              Cancel &amp; Return</button>
            <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
              <button className="w-full sm:w-auto px-3.5 py-2.5 rounded-xl text-xs font-semibold text-on-surface-variant bg-surface-container hover:bg-surface-container-high transition-colors flex items-center justify-center gap-1.5" id="escalate-btn" onClick={() => setSo0(false)}>
<MsIcon name="flag" className="text-[16px] text-tertiary" />
                <span>Escalate to CRO / Finance</span>
              </button>
              <button className="w-full sm:w-auto px-5 py-2.5 rounded-xl text-xs font-semibold text-on-primary bg-primary hover:bg-[#3f6d4d] transition-all shadow-sm flex items-center justify-center gap-1.5" id="submit-discrepancy-btn" onClick={() => setSo0(false)}>
                <span>Submit &amp; Post Adjusting Entry</span>
<MsIcon name="arrow_forward" className="text-[16px]" />
              </button>
            </div>
          </div>
        </aside>
        </>
      )}
      {so1 && (
        <>
        <div className="fixed top-0 right-0 h-full w-[640px] max-w-[95vw] bg-surface-container-lowest z-50 shadow-2xl flex flex-col justify-between overflow-hidden animate-in slide-in-from-right duration-300">
          <div className="px-8 pt-7 pb-6 bg-surface-container-lowest border-b border-surface-container">
            <div className="flex items-center justify-between mb-3">
              <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-surface-container text-on-surface text-[10px] font-bold tracking-widest uppercase">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
                </span>
                <span>{"Statement Ingestion Engine // Multi-Rail Feed V4.8"}</span>
              </div>
              <button aria-label="Close sheet" className="w-8 h-8 rounded-full bg-surface-container hover:bg-surface-container-high flex items-center justify-center text-tsc hover:text-on-surface transition-colors" id="closeSheetBtn" type="button" onClick={() => setSo1(false)}><MsIcon name="close" className="text-[18px]" /></button>
            </div>
            <h2 className="font-headline text-2xl font-bold tracking-tight text-on-surface">Import Bank &amp; Settlement Statement</h2>
            <p className="text-xs text-tsc mt-1.5 leading-relaxed">              Upload multi-currency statement files (.CSV, .OFX, .QIF, .MT940) or sync clearing feeds for automated transaction pairing and dual-entry WORM ledger reconciliation.</p>
          </div>
          <div className="flex-1 overflow-y-auto px-8 py-6 space-y-7 text-xs">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="font-bold text-on-surface uppercase tracking-wider text-[11px]">1. Target Bank &amp; Custody Account</label>
                <span className="text-[10px] text-primary font-semibold flex items-center gap-1">
<MsIcon name="verified" className="text-[13px]" />
                  Institutional Node
                </span>
              </div>
              <div className="relative">
                <select className="w-full bg-surface-container-low text-on-surface text-xs rounded-xl px-4 py-3 appearance-none focus:outline-none focus:ring-2 focus:ring-primary/20 shadow-sm cursor-pointer pr-10 font-medium" defaultValue="JPMorgan Chase Institutional Primary Operating (USD • ...4091) — NYC Custody">
                  <option>JPMorgan Chase Institutional Primary Operating (USD • ...4091) — NYC Custody</option>
                  <option>BNY Mellon Tri-Party Settlement Master (USD • ...8832) — Sec Lending</option>
                  <option>Barclays Euroclear Clearing Node (EUR • ...1029) — London Desk</option>
                  <option>Silvergate Liquidity Escrow Archive (USD • ...0044) — Segregated</option>
                </select>
<MsIcon name="expand_more" className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[18px] text-tsc pointer-events-none" />
              </div>
              <div className="flex items-center gap-1.5 text-[11px] text-tsc pt-0.5">
<MsIcon name="history" className="text-[14px] text-primary" />
                <span>Last reconciled: <strong className="text-on-surface font-semibold">May 18, 2025 at 14:15 UTC</strong> (2,180 records processed)</span>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="font-bold text-on-surface uppercase tracking-wider text-[11px]">2. Statement Date Range Covered</label>
                <span className="bg-primary/10 text-primary px-2.5 py-0.5 rounded-full font-bold text-[10px] tracking-wide">                  18-Day Settlement Window</span>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-surface-container-low rounded-xl px-4 py-2.5 flex items-center justify-between shadow-sm">
                  <div>
                    <div className="text-[10px] uppercase font-bold text-tsc tracking-wider">Start Date</div>
                    <div className="text-xs font-semibold text-on-surface mt-0.5">May 01, 2025</div>
                  </div>
<MsIcon name="calendar_today" className="text-[18px] text-tsc" />
                </div>
                <div className="bg-surface-container-low rounded-xl px-4 py-2.5 flex items-center justify-between shadow-sm">
                  <div>
                    <div className="text-[10px] uppercase font-bold text-tsc tracking-wider">End Date</div>
                    <div className="text-xs font-semibold text-on-surface mt-0.5">May 18, 2025 (Today)</div>
                  </div>
<MsIcon name="event_available" className="text-[18px] text-tsc" />
                </div>
              </div>
            </div>
            <div className="space-y-2.5">
              <label className="font-bold text-on-surface uppercase tracking-wider text-[11px]">3. File Upload Dropzone</label>
              <div className="bg-surface-container-low rounded-xl p-4 shadow-sm space-y-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/15 text-primary flex items-center justify-center shrink-0"><MsIcon name="cloud_done" className="text-[22px]" /></div>
                    <div className="min-w-0">
                      <div className="text-xs font-bold text-on-surface tracking-tight truncate">                        JPMC_CORP_OP_STMT_20250518_CLEARED.OFX</div>
                      <div className="text-[11px] text-tsc mt-0.5 flex items-center gap-2">
                        <span>3.8 MB</span>
                        <span className="text-outline-variant">•</span>
                        <span>2,180 records</span>
                        <span className="text-outline-variant">•</span>
                        <span>Validated OFX 2.2 schema</span>
                      </div>
                    </div>
                  </div>
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-primary text-on-primary text-[10px] font-bold tracking-wide">
<MsIcon name="check" className="text-[12px]" />
                    PARSED &amp; VALIDATED
                  </span>
                </div>
                <div className="w-full bg-surface-container-high rounded-full h-1.5 overflow-hidden">                  <div className="bg-primary h-full rounded-full w-full"></div></div>
              </div>
              <div className="flex items-center gap-2 pt-1 flex-wrap">
                <span className="text-[10px] uppercase font-bold text-tsc tracking-wider mr-1">Supported Schemes:</span>
                <span className="px-2 py-0.5 bg-surface-container rounded text-[10px] font-semibold text-on-surface">.CSV</span>
                <span className="px-2 py-0.5 bg-primary/15 text-primary rounded text-[10px] font-bold">.OFX 2.2</span>
                <span className="px-2 py-0.5 bg-surface-container rounded text-[10px] font-semibold text-on-surface">.QIF</span>
                <span className="px-2 py-0.5 bg-surface-container rounded text-[10px] font-semibold text-on-surface">.XLSX</span>
                <span className="px-2 py-0.5 bg-surface-container rounded text-[10px] font-semibold text-on-surface">.MT940</span>
              </div>
            </div>
            <div className="space-y-3.5">
              <label className="font-bold text-on-surface uppercase tracking-wider text-[11px]">4. Ingestion &amp; Reconciliation Engine Parameters</label>
              <div className="bg-surface-container-low rounded-xl p-3.5 flex items-start justify-between gap-4 shadow-sm">
                <div className="space-y-0.5">
                  <div className="font-bold text-on-surface text-xs">Automated Dual-Entry Pairing (Auto-Match)</div>
                  <div className="text-[11px] text-tsc leading-snug">Automatically clear matches with 100% exact delta and identical trace IDs.</div>
                </div>
                <label className="relative inline-flex items-center cursor-pointer shrink-0 mt-0.5">
<input defaultChecked className="sr-only peer" type="checkbox" />
                  <div className="w-10 h-6 bg-surface-container-highest peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-surface-container-lowest after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface-container-lowest after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                </label>
              </div>
              <div className="bg-surface-container-low rounded-xl p-3.5 flex items-start justify-between gap-4 shadow-sm">
                <div className="space-y-0.5">
                  <div className="font-bold text-on-surface text-xs">Tolerance Threshold Window (±2 Calendar Days)</div>
                  <div className="text-[11px] text-tsc leading-snug">Allow settlement lag compensation for international SWIFT wires.</div>
                </div>
                <label className="relative inline-flex items-center cursor-pointer shrink-0 mt-0.5">
<input defaultChecked className="sr-only peer" type="checkbox" />
                  <div className="w-10 h-6 bg-surface-container-highest peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-surface-container-lowest after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-surface-container-lowest after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                </label>
              </div>
              <div className="bg-surface-container-low rounded-xl p-3.5 flex items-center justify-between shadow-sm">
                <div>
                  <div className="font-bold text-on-surface text-xs">Match Variance Tolerance</div>
                  <div className="text-[11px] text-tsc">FX conversion micro-slippage &amp; rounding limits</div>
                </div>
                <div className="bg-surface-container px-3 py-1.5 rounded-lg font-mono font-bold text-xs text-on-surface">
                  ±$0.01 USD
                  <span className="text-[10px] text-tsc font-normal">(Strict)</span>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <label className="font-bold text-on-surface uppercase tracking-wider text-[11px]">5. Ingestion Dry-Run Simulation Preview</label>
              <div className="bg-surface-container rounded-xl p-4 shadow-sm space-y-3.5">
                <div className="flex items-center justify-between text-xs pb-2 border-b border-surface-container-highest/60">
                  <span className="text-tsc font-medium">Total Statement Lines Parsed</span>
                  <span className="font-mono font-bold text-on-surface">2,180</span>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-surface-container-lowest rounded-lg p-2.5">
                    <div className="text-[10px] font-bold uppercase tracking-wider text-tsc">Projected Auto-Match</div>
                    <div className="text-base font-bold text-primary mt-1 font-mono">2,168 <span className="text-xs font-normal">(99.4%)</span></div>
                    <div className="text-[10px] text-tsc mt-0.5">Direct WORM ledger write</div>
                  </div>
                  <div className="bg-surface-container-lowest rounded-lg p-2.5">
                    <div className="text-[10px] font-bold uppercase tracking-wider text-tsc">Flagged Variance</div>
                    <div className="text-base font-bold text-error mt-1 font-mono">12 <span className="text-xs font-normal">entries</span></div>
                    <div className="text-[10px] text-tsc mt-0.5">Pending desk human review</div>
                  </div>
                </div>
                <div className="pt-1 flex items-center justify-between text-[10px] text-tsc font-mono bg-surface-container-high/40 px-3 py-1.5 rounded">
                  <span>AUDIT HASH:</span>
                  <span className="font-bold text-on-surface select-all">sha256:4b29-e81a-9f44-c71b-09ad8f</span>
                </div>
              </div>
            </div>
            <div className="bg-secondary-container/50 rounded-xl p-3.5 flex items-start gap-3">
<MsIcon name="policy" className="text-[18px] text-tertiary shrink-0 mt-0.5" />
              <div className="text-[11px] text-on-secondary-container leading-relaxed">
                <strong className="font-bold">SEC Rule 17a-4 / FINRA Notice:</strong>
                All uploaded statement artifacts are written to immutable AWS S3 Glacier WORM lock with zero overwrite permissions. Reconciled entries are ledger-certified.
              </div>
            </div>
          </div>
          <div className="px-8 py-5 bg-surface-container-lowest border-t border-surface-container flex items-center justify-between gap-3">
            <button className="px-4 py-2.5 rounded-xl text-xs font-bold text-tsc hover:text-on-surface hover:bg-surface-container transition-colors" id="cancelBtn" type="button" onClick={() => setSo1(false)}>              Cancel &amp; Close</button>
            <div className="flex items-center gap-2.5">
              <button className="px-4 py-2.5 rounded-xl text-xs font-bold text-primary bg-primary/10 hover:bg-primary/15 transition-colors" type="button">                Dry-Run Simulation Only</button>
              <button className="px-5 py-2.5 rounded-xl text-xs font-bold text-on-primary bg-primary hover:bg-primary/90 transition-all shadow-md flex items-center gap-2 active:scale-95" id="executeMatchBtn" type="button" onClick={() => setSo1(false)}>
                <span>Import &amp; Execute Auto-Match (2,180 Lines)</span>
<MsIcon name="arrow_forward" className="text-[16px]" />
              </button>
            </div>
          </div>
        </div>
        </>
      )}
    </>
  );
}
