"use client";

/**
 * Performance — Stitch conversion (view-id: `marketing-performance`)
 *
 * Source: stitch_screens/marketing_performance
 * Spec: [EXISTING] · overlay states: 0/2 wired
 * States: marketing_performance_channel_attribution_drill_down_sheet_state✗, marketing_performance_export_attribution_model_modal_state✗
 *
 * Generated by tools/stitch2tsx.py — regenerate with the pipeline
 * instead of hand-editing generated markup.
 */

import { MsIcon } from "@/components/stitch/stitch";

export function MarketingPerformanceStitchPage() {
  return (
    <>
      <div className="flex flex-col w-full">
        <div className="flex flex-col gap-4 pb-6">
          <div className="flex flex-wrap items-center justify-between gap-3 text-[11px] tracking-wider font-semibold uppercase">
            <div className="flex items-center gap-2 text-tsc">
              <span>MARKETING &amp; GROWTH</span>
              <span className="text-outline-variant">/</span>
              <span>PERFORMANCE &amp; ATTRIBUTION</span>
              <span className="text-outline-variant">/</span>
              <span className="text-primary font-bold">CHANNEL PERFORMANCE</span>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant flex items-center gap-1.5 shadow-sm">
                <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                ATTRIBUTION: MARKOV MULTI-TOUCH V2.4
              </span>
              <span className="px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant flex items-center gap-1.5 shadow-sm">
                <span className="w-1.5 h-1.5 rounded-full bg-tertiary"></span>
                CLICKHOUSE AGGREGATION: NY4-MKT-01
              </span>
              <span className="px-2.5 py-1 rounded-full bg-surface-container-high text-on-surface-variant flex items-center gap-1.5 shadow-sm">
                <span className="w-1.5 h-1.5 rounded-full bg-primary-container"></span>
                REAL-TIME SYNC: 14 ACTIVE CHANNELS
              </span>
            </div>
          </div>
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pt-1">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary shrink-0 shadow-sm"><MsIcon name="trending_up" className="text-[28px]" /></div>
              <div className="space-y-1">
                <div className="flex items-center gap-3">
                  <h1 className="font-headline font-bold text-2xl text-on-surface tracking-tight">Performance</h1>
                  <span className="px-2.5 py-0.5 rounded-full bg-surface-container-high text-on-surface-variant text-[11px] font-bold tracking-wide uppercase">Channel Aggregate View</span>
                </div>
                <p className="text-tsc text-sm leading-relaxed max-w-3xl">                  Cross-channel multi-touch attribution comparing gross funded trader revenue, conversion volume, and paid acquisition spend side-by-side.</p>
              </div>
            </div>
            <div className="flex items-center gap-2 self-start lg:self-center bg-surface-container px-3.5 py-1.5 rounded-xl shadow-sm">
<MsIcon name="calendar_today" className="text-tsc text-[18px]" />
              <span className="text-xs font-semibold text-on-surface tracking-tight">Reporting Window: Last 30 Days (Apr 19 – May 18, 2025)</span>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
          <div className="bg-surface-container-low rounded-2xl p-5 shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
            <div className="absolute -right-3 -top-3 w-20 h-20 bg-primary/5 rounded-full blur-xl group-hover:bg-primary/10 transition-colors"></div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs uppercase font-bold tracking-wider text-tsc">Blended Gross Revenue</span>
              <span className="flex items-center gap-1 text-[11px] font-bold text-primary bg-primary-fixed/40 px-2 py-0.5 rounded-full">
<MsIcon name="arrow_upward" className="text-[13px]" />
                +28.4% MoM
              </span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-headline font-bold text-2xl text-on-surface">$549,420.00</span>
              <span className="text-xs text-tsc font-medium">USD</span>
            </div>
            <div className="mt-3 pt-3 border-t-0 flex items-center justify-between text-[11px] text-tsc">
              <span>Funded challenge fees</span>
              <span className="font-semibold text-on-surface">30-day trailing</span>
            </div>
          </div>
          <div className="bg-surface-container-low rounded-2xl p-5 shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
            <div className="absolute -right-3 -top-3 w-20 h-20 bg-tertiary/5 rounded-full blur-xl group-hover:bg-tertiary/10 transition-colors"></div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs uppercase font-bold tracking-wider text-tsc">Cohort Funded Traders</span>
              <span className="flex items-center gap-1 text-[11px] font-bold text-primary bg-primary-fixed/40 px-2 py-0.5 rounded-full">
<MsIcon name="arrow_upward" className="text-[13px]" />
                +22.4% MoM
              </span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-headline font-bold text-2xl text-on-surface">1,842</span>
              <span className="text-xs text-tsc font-medium">Traders Cleared</span>
            </div>
            <div className="mt-3 pt-3 border-t-0 flex items-center justify-between text-[11px] text-tsc">
              <span>Evaluation tier accounts</span>
              <span className="font-semibold text-on-surface">98.1% KyC verified</span>
            </div>
          </div>
          <div className="bg-surface-container-low rounded-2xl p-5 shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between relative overflow-hidden group hover:bg-surface-container transition-all">
            <div className="absolute -right-3 -top-3 w-20 h-20 bg-surface-variant/40 rounded-full blur-xl group-hover:bg-primary/5 transition-colors"></div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs uppercase font-bold tracking-wider text-tsc">Capital Outlay &amp; ROAS</span>
              <span className="flex items-center gap-1 text-[11px] font-bold text-on-tertiary-container bg-tertiary-fixed px-2 py-0.5 rounded-full">                ROAS 3.85x</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-headline font-bold text-2xl text-on-surface">$142,850.00</span>
              <span className="text-xs font-bold text-primary">ROI +284.6%</span>
            </div>
            <div className="mt-3 pt-3 border-t-0 flex items-center justify-between text-[11px] text-tsc">
              <span>Across 6 active ingress vectors</span>
              <span className="font-semibold text-on-surface">Avg CAC $77.55</span>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <div className="bg-surface-container-low rounded-2xl p-6 shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <div className="flex items-center gap-2">
                  <h2 className="font-headline font-bold text-lg text-on-surface">Revenue by Channel</h2>
                  <span className="px-2 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-bold uppercase tracking-wider">Top Ingress</span>
                </div>
                <span className="text-xs font-semibold text-tsc">Scale: $0 – $200k</span>
              </div>
              <p className="text-xs text-tsc mb-6 leading-relaxed">                Gross revenue generated from challenge account purchases by acquisition channel.</p>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="search" className="text-[16px] text-primary" />
                      <span className="font-semibold text-on-surface">Paid Search (Google PPC &amp; PMax)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $48.5k</span>
                      <span className="font-mono font-bold text-on-surface">$184,200</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+379% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-primary rounded-full transition-all duration-500" style={{ width: '92.1%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>33.5% of total revenue</span>
                    <span>Capacity utilization: High</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="play_circle" className="text-[16px] text-[#6b9075]" />
                      <span className="font-semibold text-on-surface">Video &amp; Creator Ingress (YouTube)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $36.2k</span>
                      <span className="font-mono font-bold text-on-surface">$126,500</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+336% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#6b9075] rounded-full transition-all duration-500" style={{ width: '63.25%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>23.0% of total revenue</span>
                    <span>Case studies &amp; scalper breakdowns</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="candlestick_chart" className="text-[16px] text-[#a66a44]" />
                      <span className="font-semibold text-on-surface">Display &amp; Direct Partner (TradingView)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $24.8k</span>
                      <span className="font-mono font-bold text-on-surface">$89,400</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+297% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#a66a44] rounded-full transition-all duration-500" style={{ width: '44.7%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>16.3% of total revenue</span>
                    <span>Top chart sponsorship &amp; native feeds</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="campaign" className="text-[16px] text-[#c99355]" />
                      <span className="font-semibold text-on-surface">Social Media Ads (Twitter/X &amp; Meta)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $16.9k</span>
                      <span className="font-mono font-bold text-on-surface">$64,800</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+256% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#c99355] rounded-full transition-all duration-500" style={{ width: '32.4%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>11.8% of total revenue</span>
                    <span>High click-through in scalper subcultures</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="hub" className="text-[16px] text-[#36533f]" />
                      <span className="font-semibold text-on-surface">Affiliate &amp; Partner Syndication</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $11.45k</span>
                      <span className="font-mono font-bold text-on-surface">$52,300</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+147% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#36533f] rounded-full transition-all duration-500" style={{ width: '26.15%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>9.5% of total revenue</span>
                    <span>Tier 1 prop review affiliate networks</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="forum" className="text-[16px] text-[#8c9a86]" />
                      <span className="font-semibold text-on-surface">Community &amp; Direct (Discord / Bot)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Spend: $5.0k</span>
                      <span className="font-mono font-bold text-on-surface">$32,220</span>
                      <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-primary-fixed/50 text-on-primary-fixed-variant">+136% ROI</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#8c9a86] rounded-full transition-all duration-500" style={{ width: '16.11%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>5.9% of total revenue</span>
                    <span>Telegram signal integrations &amp; bot commands</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-6 pt-4 bg-surface-container rounded-xl p-3.5 flex flex-wrap items-center justify-between text-xs">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-primary"></span>
                <span className="text-tsc font-medium">Top Performing Channel:</span>
                <span className="font-bold text-on-surface">Google PPC ($184.2k)</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-tsc font-medium">Highest Efficiency:</span>
                <span className="font-bold text-primary">Discord Bot (6.44x ROAS)</span>
              </div>
            </div>
          </div>
          <div className="bg-surface-container-low rounded-2xl p-6 shadow-[0_4px_20px_rgba(46,50,48,0.04)] flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <div className="flex items-center gap-2">
                  <h2 className="font-headline font-bold text-lg text-on-surface">Conversions by Channel</h2>
                  <span className="px-2 py-0.5 rounded-full bg-tertiary/10 text-tertiary text-[10px] font-bold uppercase tracking-wider">Funded Traders</span>
                </div>
                <span className="text-xs font-semibold text-tsc">Total: 1,842 Accounts</span>
              </div>
              <p className="text-xs text-tsc mb-6 leading-relaxed">                Total verified challenge evaluation purchases &amp; funded trader accounts by channel.</p>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="person_check" className="text-[16px] text-primary" />
                      <span className="font-semibold text-on-surface">Paid Search (Google Ads)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Avg CAC: $83.05</span>
                      <span className="font-mono font-bold text-on-surface">584 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">31.7% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-primary rounded-full transition-all duration-500" style={{ width: '31.7%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 19.4 traders/day</span>
                    <span>Pass rate: 18.2%</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="videocam" className="text-[16px] text-[#6b9075]" />
                      <span className="font-semibold text-on-surface">Video &amp; Streaming (YouTube Partner)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Avg CAC: $87.86</span>
                      <span className="font-mono font-bold text-on-surface">412 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">22.4% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#6b9075] rounded-full transition-all duration-500" style={{ width: '22.4%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 13.7 traders/day</span>
                    <span>Pass rate: 21.4% (Highest Quality)</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="share" className="text-[16px] text-[#c99355]" />
                      <span className="font-semibold text-on-surface">Social Media Ads (Meta / X)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc font-bold text-primary">Avg CAC: $51.52</span>
                      <span className="font-mono font-bold text-on-surface">328 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">17.8% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#c99355] rounded-full transition-all duration-500" style={{ width: '17.8%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 10.9 traders/day</span>
                    <span>Pass rate: 14.1%</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="ads_click" className="text-[16px] text-[#a66a44]" />
                      <span className="font-semibold text-on-surface">Display &amp; Retargeting (TradingView)</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Avg CAC: $93.94</span>
                      <span className="font-mono font-bold text-on-surface">264 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">14.3% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#a66a44] rounded-full transition-all duration-500" style={{ width: '14.3%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 8.8 traders/day</span>
                    <span>Pass rate: 17.6%</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="group_add" className="text-[16px] text-[#36533f]" />
                      <span className="font-semibold text-on-surface">Affiliate Network</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Avg CAC: $68.15</span>
                      <span className="font-mono font-bold text-on-surface">168 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">9.1% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#36533f] rounded-full transition-all duration-500" style={{ width: '9.1%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 5.6 traders/day</span>
                    <span>Pass rate: 15.3%</span>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
<MsIcon name="chat" className="text-[16px] text-[#8c9a86]" />
                      <span className="font-semibold text-on-surface">Community &amp; Organic Discord</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] text-tsc">Avg CAC: $58.14</span>
                      <span className="font-mono font-bold text-on-surface">86 Traders</span>
                      <span className="text-[10px] font-semibold text-tsc bg-surface-container px-2 py-0.5 rounded-full">4.7% Vol</span>
                    </div>
                  </div>
                  <div className="h-2.5 w-full bg-surface-container rounded-full overflow-hidden flex">                    <div className="h-full bg-[#8c9a86] rounded-full transition-all duration-500" style={{ width: '4.7%' }}></div></div>
                  <div className="flex justify-between text-[10px] text-tsc px-0.5">
                    <span>Conversion velocity: 2.9 traders/day</span>
                    <span>Pass rate: 23.8%</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-6 pt-4 bg-surface-container rounded-xl p-3.5 flex flex-wrap items-center justify-between text-xs">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[#c99355]"></span>
                <span className="text-tsc font-medium">Lowest Blended CAC:</span>
                <span className="font-bold text-on-surface">Meta / Social ($51.52 / trader)</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-tsc font-medium">Highest Volume:</span>
                <span className="font-bold text-primary">Google Search (584 traders)</span>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-surface-container-low rounded-2xl p-6 lg:p-8 shadow-[0_4px_20px_rgba(46,50,48,0.04)] mb-8">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-2">
            <div className="flex items-center gap-3">
              <h2 className="font-headline font-bold text-xl text-on-surface">Spend Distribution</h2>
              <span className="px-2.5 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold tracking-wide uppercase">                Multi-Channel Budget Allocation ($142,850.00 Total)</span>
            </div>
            <div className="text-xs text-tsc font-semibold">              Aggregated Ingress Trailing 30 Days</div>
          </div>
          <p className="text-xs text-tsc mb-8 leading-relaxed max-w-2xl">            Cross-platform spend breakdown and capital efficiency across paid channels, tracking marginal returns on ad spend.</p>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-5 flex flex-col items-center justify-center p-4">
              <div className="relative w-64 h-64 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 200 200">
                  <circle className="text-surface-container" cx={100} cy={100} fill="none" r={76} stroke="currentColor" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#4a7c59" strokeDasharray="162.35 477.52" strokeDashoffset="0" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#6b9075" strokeDasharray="120.81 477.52" strokeDashoffset="-162.35" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#a66a44" strokeDasharray="83.08 477.52" strokeDashoffset="-283.16" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#c99355" strokeDasharray="56.34 477.52" strokeDashoffset="-366.24" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#36533f" strokeDasharray="38.20 477.52" strokeDashoffset="-422.58" strokeWidth={24}></circle>
                  <circle className="transition-all duration-700" cx={100} cy={100} fill="none" r={76} stroke="#8c9a86" strokeDasharray="16.71 477.52" strokeDashoffset="-460.78" strokeWidth={24}></circle>
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center text-center pointer-events-none">
                  <span className="text-[11px] font-bold text-tsc uppercase tracking-widest">Total Spend</span>
                  <span className="font-headline font-bold text-2xl text-on-surface">$142,850</span>
                  <span className="text-[10px] font-semibold text-primary mt-0.5">6 Active Channels</span>
                </div>
              </div>
            </div>
            <div className="lg:col-span-7 flex flex-col gap-2.5">
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#4a7c59] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Paid Search (Google PPC &amp; PMax)</div>
                    <div className="text-[11px] text-tsc">34.0% of Total Budget · $48,500.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$184,200 Ret</div>
                    <div className="text-[11px] text-tsc">584 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">3.80x</span>
                    <div className="text-[10px] text-primary font-semibold">Scaling</div>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#6b9075] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Video &amp; Streaming (YouTube Reviews)</div>
                    <div className="text-[11px] text-tsc">25.3% of Total Budget · $36,200.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$126,500 Ret</div>
                    <div className="text-[11px] text-tsc">412 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">3.50x</span>
                    <div className="text-[10px] text-primary font-semibold">Optimal</div>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#a66a44] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Display &amp; Direct Partner (TradingView)</div>
                    <div className="text-[11px] text-tsc">17.4% of Total Budget · $24,800.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$89,400 Ret</div>
                    <div className="text-[11px] text-tsc">264 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">3.60x</span>
                    <div className="text-[10px] text-primary font-semibold">Optimal</div>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#c99355] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Social &amp; Influencers (Meta &amp; X)</div>
                    <div className="text-[11px] text-tsc">11.8% of Total Budget · $16,900.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$64,800 Ret</div>
                    <div className="text-[11px] text-tsc">328 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">3.83x</span>
                    <div className="text-[10px] text-primary font-semibold">Scaling</div>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#36533f] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Affiliate Sponsorships (Review Portals)</div>
                    <div className="text-[11px] text-tsc">8.0% of Total Budget · $11,450.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$52,300 Ret</div>
                    <div className="text-[11px] text-tsc">168 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">4.57x</span>
                    <div className="text-[10px] text-on-tertiary-container font-semibold">Efficient</div>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-surface-container hover:bg-surface-container-high transition-colors">
                <div className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-[#8c9a86] shrink-0"></span>
                  <div>
                    <div className="text-xs font-bold text-on-surface">Community &amp; Direct (Discord &amp; Bots)</div>
                    <div className="text-[11px] text-tsc">3.5% of Total Budget · $5,000.00</div>
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-xs font-mono font-bold text-on-surface">$32,220 Ret</div>
                    <div className="text-[11px] text-tsc">86 Traders</div>
                  </div>
                  <div className="w-16 text-right">
                    <span className="text-xs font-bold text-on-surface">6.44x</span>
                    <div className="text-[10px] text-primary font-semibold">Efficient</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-6 p-4 rounded-xl bg-surface-container flex items-start gap-3 text-xs text-on-surface">
<MsIcon name="tips_and_updates" className="text-primary text-[20px] shrink-0 mt-0.5" />
            <div className="leading-relaxed">
              <span className="font-bold text-primary">Channel Efficiency Takeaway:</span>
              Community &amp; Direct and Social Ads deliver the highest ROAS multipliers (&gt;4.5x), while Paid Search remains the primary volume anchor driving 33.5% of gross revenue. Recommended action: increment YouTube creator budget by 12% for the Q3 evaluation cycle without diluting blended CAC.
            </div>
          </div>
        </div>
        <div className="pt-4 border-t-0 flex flex-wrap items-center justify-between gap-4 text-[11px] text-tsc">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-primary"></span>
            <span>Cluster: LDN-01A (Equinix LD4)</span>
            <span className="text-outline-variant">·</span>
            <span>Ingestion Engine: ClickHouse NY4-MKT-01</span>
            <span className="text-outline-variant">·</span>
            <span>Attribution Model: Markov Multi-Touch v2.4 (SEC &amp; FTC Compliant)</span>
          </div>
          <div className="flex items-center gap-2 font-mono text-[10px] bg-surface-container px-2.5 py-1 rounded-md">
            <span className="text-primary font-bold">lon-mkt-ingest-01</span>
            <span className="text-tsc">READY · 0 LEDGER OVERHEAD</span>
          </div>
        </div>
      </div>
    </>
  );
}
